# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load("//:COMPONENTS_DEFS", "COMPONENTS_ASSERTJ_TARGET", "COMPONENTS_DIFFUTILS_TARGET", "COMPONENTS_GUAVA_TARGET", "COMPONENTS_JAVA_TARGET", "COMPONENTS_JSR_TARGET", "COMPONENTS_JUNIT_TARGET", "COMPONENTS_ROBOLECTRIC_TARGET", "litho_android_library", "make_dep_path")

litho_android_library(
    name = "viewtree",
    srcs = glob(["*.java"]),
    exported_deps = [
        COMPONENTS_ASSERTJ_TARGET,
    ],
    provided_deps = [
        COMPONENTS_ROBOLECTRIC_TARGET,
    ],
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/testing/viewtree:viewtree"),
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        COMPONENTS_DIFFUTILS_TARGET,
        COMPONENTS_GUAVA_TARGET,
        COMPONENTS_JAVA_TARGET,
        COMPONENTS_JSR_TARGET,
        COMPONENTS_JUNIT_TARGET,
    ],
)
