# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load("//:LITHO_DEFS", "LITHO_ASSERTJ_TARGET", "LITHO_DIFFUTILS_TARGET", "LITHO_GUAVA_TARGET", "LITHO_JAVA_TARGET", "LITHO_JSR_TARGET", "LITHO_JUNIT_TARGET", "LITHO_ROBOLECTRIC_TARGET", "litho_android_library", "make_dep_path")

litho_android_library(
    name = "viewtree",
    srcs = glob(["*.java"]),
    exported_deps = [
        LITHO_ASSERTJ_TARGET,
    ],
    provided_deps = [
        LITHO_ROBOLECTRIC_TARGET,
    ],
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/testing/viewtree:viewtree"),
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_DIFFUTILS_TARGET,
        LITHO_GUAVA_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JSR_TARGET,
        LITHO_JUNIT_TARGET,
    ],
)
