include_defs("//COMPONENTS_DEFS")

android_library(
    name = "fresco",
    srcs = glob(
        ["*.java"],
        excludes = ["common/**/*"],
    ),
    plugins = [
        COMPONENTS_PROCESSOR_TARGET,
    ],
    visibility = [
        "PUBLIC",
    ],
    deps =
        COMPONENTS_FRESCO_TARGETS + [
            COMPONENTS_OSS_TARGET,
            COMPONENTS_COMPONENTS_FRESCO_COMMON_TARGET,
            COMPONENTS_UTILS_TARGET,
            COMPONENTS_ANDROIDSUPPORT_TARGET,
        ],
)
