# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

android_library(
    name = "fresco",
    srcs = glob(
        ["*.java"],
        excludes = ["common/**/*"],
    ),
    plugins = [
        COMPONENTS_PROCESSOR_TARGET,
    ],
    visibility = [
        "PUBLIC",
    ],
    deps =
        COMPONENTS_FRESCO_TARGETS + [
            COMPONENTS_OSS_TARGET,
            COMPONENTS_COMPONENTS_FRESCO_COMMON_TARGET,
            COMPONENTS_UTILS_TARGET,
            COMPONENTS_ANDROIDSUPPORT_TARGET,
        ],
)
