# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_SWIPEREFRESHLAYOUT_TARGET",
    "LITHO_ANDROIDSUPPORT_TESTING_CORE_TARGET",
    "LITHO_ASSERTJ_TARGET",
    "LITHO_BUILD_CONFIG_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_JUNIT_TARGET",
    "LITHO_MOCKITO_KOTLIN_V2_TARGET",
    "LITHO_ROBOLECTRIC_V4_TARGET",
    "LITHO_SECTIONS_ANNOTATIONS_TARGET",
    "LITHO_SECTIONS_COMMON_TARGET",
    "LITHO_SECTIONS_TARGET",
    "LITHO_SECTIONS_WIDGET_KOTLIN_TARGET",
    "LITHO_SECTIONS_WIDGET_TARGET",
    "LITHO_TESTING_ASSERTJ_TARGET",
    "LITHO_TESTING_TARGET",
    "LITHO_VIEWCOMPAT_TARGET",
    "LITHO_WIDGET_KOTLIN_COLLECTION_TARGET",
    "LITHO_WIDGET_KOTLIN_TARGET",
    "LITHO_WIDGET_TARGET",
    "LITHO_YOGA_TARGET",
    "litho_robolectric4_test",
    "make_dep_path",
)

litho_robolectric4_test(
    name = "testing",
    srcs = glob([
        "*Test.kt",
    ]),
    contacts = ["oncall+components_for_android@xmail.facebook.com"],
    friend_paths = [
        LITHO_TESTING_TARGET,
    ],
    language = "KOTLIN",
    source = "8",
    target = "8",
    deps = [
        LITHO_ANDROIDSUPPORT_TESTING_CORE_TARGET,
        LITHO_ASSERTJ_TARGET,
        LITHO_BUILD_CONFIG_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JUNIT_TARGET,
        LITHO_MOCKITO_KOTLIN_V2_TARGET,
        LITHO_ROBOLECTRIC_V4_TARGET,
        LITHO_SECTIONS_ANNOTATIONS_TARGET,
        LITHO_SECTIONS_COMMON_TARGET,
        LITHO_SECTIONS_TARGET,
        LITHO_SECTIONS_WIDGET_TARGET,
        LITHO_SECTIONS_WIDGET_KOTLIN_TARGET,
        LITHO_TESTING_ASSERTJ_TARGET,
        LITHO_TESTING_TARGET,
        LITHO_VIEWCOMPAT_TARGET,
        LITHO_WIDGET_KOTLIN_COLLECTION_TARGET,
        LITHO_WIDGET_KOTLIN_TARGET,
        LITHO_WIDGET_TARGET,
        LITHO_ANDROIDSUPPORT_SWIPEREFRESHLAYOUT_TARGET,
        LITHO_YOGA_TARGET,
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/inlinelayoutspec:inlinelayoutspec"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/testrunner:testrunner"),
    ],
)
