# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load("//tools/build_defs/oss:litho_defs.bzl", "LITHO_ANDROIDSUPPORT_TARGET", "fb_java_library")

fb_java_library(
    name = "annotations",
    srcs = glob(["*.java"]),
    is_androidx = True,
    labels = ["supermodule:android/default/litho.core"],
    provided_deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
    ],
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
)
