load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")

# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "litho_android_library",
)

litho_android_library(
    name = "annotations",
    srcs = glob([
        "*.java",
        "*.kt",
    ]),
    autoglob = False,
    feature = FBApp_UIFrameworks_Litho_Litho,
    k2 = True,
    labels = [],
    provided_deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
    ],
    pure_kotlin = False,
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
)
