# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_APPCOMPAT_TARGET",
    "LITHO_INFERANNOTATIONS_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_KOTLIN_STDLIB_TARGET",
    "litho_android_library",
    "make_dep_path",
)

oncall("playgroundapps")

litho_android_library(
    name = "litho-permissions",
    srcs = glob(["src/main/**/*.kt"]),
    abi_generation_mode = "source_only",
    autoglob = False,
    feature = FBApp_UIFrameworks_Litho_Litho,
    k2 = False,
    labels = [],
    provided_deps = [
    ],
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        make_dep_path("litho-coroutines-kotlin/src/main/kotlin/com/facebook/litho:litho-coroutines-kotlin"),
        LITHO_JAVA_TARGET,
        LITHO_ANDROIDSUPPORT_APPCOMPAT_TARGET,
        LITHO_KOTLIN_STDLIB_TARGET,
        LITHO_INFERANNOTATIONS_TARGET,
    ],
    exported_deps = [
        LITHO_JAVA_TARGET,
    ],
)
