#
# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//LITHO_DEFS")

litho_android_library(
    name = "sections",
    srcs = glob(["*.java"]),
    exported_deps = [
        LITHO_SECTIONS_ANNOTATIONS_TARGET,
    ],
    required_for_source_only_abi = True,
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/sections:sections"),
    ],
    visibility = LITHO_VISIBILITY,
    deps = [
        LITHO_JAVA_TARGET,
        LITHO_YOGA_TARGET,
        LITHO_JSR_TARGET,
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_WIDGET_TARGET,
        make_dep_path("litho-sections-core/src/main/java/com/facebook/litho/sections/config:config"),
        make_dep_path("litho-sections-core/src/main/java/com/facebook/litho/sections/logger:logger"),
    ],
)
