# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
# of patent rights can be found in the PATENTS file in the same directory.

load("//tools/build_defs/oss:litho_defs.bzl", "LITHO_ANDROIDSUPPORT_TARGET", "LITHO_INFERANNOTATIONS_TARGET", "LITHO_JAVA_TARGET", "LITHO_JSR_TARGET", "LITHO_SECTIONS_ANNOTATIONS_TARGET", "LITHO_STATS_TARGET", "LITHO_VISIBILITY", "LITHO_WIDGET_TARGET", "LITHO_YOGA_TARGET", "litho_android_library", "make_dep_path")

litho_android_library(
    name = "sections",
    srcs = glob(["*.java"]),
    is_androidx = True,
    required_for_source_only_abi = True,
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/sections:sections"),
    ],
    visibility = LITHO_VISIBILITY,
    deps = [
        LITHO_INFERANNOTATIONS_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_STATS_TARGET,
        LITHO_YOGA_TARGET,
        LITHO_JSR_TARGET,
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_WIDGET_TARGET,
        make_dep_path("litho-sections-core/src/main/java/com/facebook/litho/sections/config:config"),
        make_dep_path("litho-sections-core/src/main/java/com/facebook/litho/sections/logger:logger"),
    ],
    exported_deps = [
        LITHO_SECTIONS_ANNOTATIONS_TARGET,
    ],
)
