# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
# of patent rights can be found in the PATENTS file in the same directory.

load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_INFERANNOTATIONS_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_JSR_TARGET",
    "LITHO_PERF_LOGGER",
    "LITHO_SECTIONS_ANNOTATIONS_TARGET",
    "LITHO_STATS_TARGET",
    "LITHO_VISIBILITY",
    "LITHO_WIDGET_TARGET",
    "LITHO_YOGA_TARGET",
    "litho_android_library",
    "make_dep_path",
)

litho_android_library(
    name = "sections",
    feature = FBApp_UIFrameworks_Litho_Litho,
    labels = [],
    language = "JAVA",
    required_for_source_only_abi = True,
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho:litho"),
    ],
    visibility = LITHO_VISIBILITY,
    deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_INFERANNOTATIONS_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JSR_TARGET,
        LITHO_STATS_TARGET,
        LITHO_WIDGET_TARGET,
        LITHO_PERF_LOGGER,
        LITHO_YOGA_TARGET,
        make_dep_path("litho-sections-core/src/main/java/com/facebook/litho/sections/config:config"),
        make_dep_path("litho-sections-core/src/main/java/com/facebook/litho/sections/logger:logger"),
    ],
    exported_deps = [
        LITHO_SECTIONS_ANNOTATIONS_TARGET,
    ],
)
