# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//:LITHO_DEFS", "LITHO_ASSERTJ_TARGET", "make_dep_path")

android_library(
    name = "specmodels",
    srcs = glob(["*.java"]),
    exported_deps = [
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_ASSERTJ_TARGET,
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels:specmodels"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/internal:internal"),
    ],
)
