# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load("//:COMPONENTS_DEFS", "COMPONENTS_ASSERTJ_TARGET", "make_dep_path")

android_library(
    name = "specmodels",
    srcs = glob(["*.java"]),
    exported_deps = [
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        COMPONENTS_ASSERTJ_TARGET,
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels:specmodels"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/internal:internal"),
    ],
)
