include_defs("//COMPONENTS_DEFS")

android_library(
    name = "components",
    srcs = glob(["*.java"]),
    visibility = [
        COMPONENTS_VISIBILITY,
    ],
    deps = [
        COMPONENTS_INFERANNOTATIONS_TARGET,
        COMPONENTS_JAVA_TARGET,
        COMPONENTS_JSR_TARGET,
        COMPONENTS_STETHO_TARGET,
    ],
)
