# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

android_library(
    name = "components",
    srcs = glob(["*.java"]),
    provided_deps = [
        COMPONENTS_YOGA_TARGET,
    ],
    visibility = [
        COMPONENTS_VISIBILITY,
    ],
    deps = [
        COMPONENTS_ANDROIDSUPPORT_TARGET,
        COMPONENTS_INFERANNOTATIONS_TARGET,
        COMPONENTS_JAVA_TARGET,
        COMPONENTS_JSR_TARGET,
        COMPONENTS_STETHO_TARGET,
