# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ROBOLECTRIC_V4_TARGET",
    "litho_android_library",
    "make_dep_path",
)

litho_android_library(
    name = "testrunner",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_ROBOLECTRIC_V4_TARGET,
        make_dep_path("litho-core/src/main/java/com/facebook/litho:litho"),
    ],
)
