# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ROBOLECTRIC_V3_TARGET",
    "LITHO_ROBOLECTRIC_V4_TARGET",
    "litho_android_library",
)

litho_android_library(
    name = "testrunner",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_ROBOLECTRIC_V3_TARGET,
    ],
)

litho_android_library(
    name = "testrunner-v4",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_ROBOLECTRIC_V4_TARGET,
    ],
)
