# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//:LITHO_DEFS.bzl", "LITHO_BUILD_CONFIG_TARGET", "LITHO_JAVA_TARGET", "LITHO_JSR_TARGET", "LITHO_JUNIT_TARGET", "LITHO_ROBOLECTRIC_TARGET", "LITHO_TESTING_TARGET", "make_dep_path", "components_robolectric_test")

components_robolectric_test(
    name = "assertj",
    srcs = glob(["*Test.java"]),
    contacts = ["oncall+components_for_android@xmail.facebook.com"],
    source = "8",
    target = "8",
    deps = [
        LITHO_BUILD_CONFIG_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JSR_TARGET,
        LITHO_JUNIT_TARGET,
        LITHO_ROBOLECTRIC_TARGET,
        make_dep_path("litho-widget/src/main/java/com/facebook/litho/widget:widget"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/util:util"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/testrunner:testrunner"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/assertj:assertj"),
        LITHO_TESTING_TARGET,
    ],
)
