load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_JAVA_TARGET",
    "litho_android_library",
)

litho_android_library(
    name = "tooling",
    srcs = glob(["**/*.kt"]),
    abi_generation_mode = "source_only",
    autoglob = False,
    k2 = True,
    labels = [],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_JAVA_TARGET,
    ],
)
