# Copyright (c) Facebook, Inc. and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("//tools/build_defs/oss:fb_native_wrapper.bzl", "fb_native")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_SAMPLE_CODELAB_JAVA",
    "fb_android_resource",
)

fb_native.android_binary(
    name = "sample-codelab",
    includes_vector_drawables = True,
    keystore = ":debug_keystore",
    manifest = "src/main/AndroidManifest.xml",
    aapt_mode = "aapt2",
    deps = [
        LITHO_SAMPLE_CODELAB_JAVA,
    ],
)

fb_android_resource(
    name = "res",
    package = "com.facebook.samples.lithocodelab",
    res = "src/main/res",
    visibility = [
        "PUBLIC",
    ],
)

fb_native.keystore(
    name = "debug_keystore",
    properties = "debug.keystore.properties",
    store = "debug.keystore",
)
