# BUILD FILE SYNTAX: SKYLARK
# Copyright 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE-examples file in the root directory of this source tree.

load("//:LITHO_DEFS.bzl", "LITHO_SAMPLE_CODELAB_JAVA", "fb_android_resource")

android_binary(
    name = "sample-codelab",
    includes_vector_drawables = True,
    keystore = ":debug_keystore",
    manifest = "src/main/AndroidManifest.xml",
    deps = [
        LITHO_SAMPLE_CODELAB_JAVA,
    ],
)

fb_android_resource(
    name = "res",
    package = "com.facebook.samples.lithocodelab",
    res = "src/main/res",
    visibility = [
        "PUBLIC",
    ],
)

keystore(
    name = "debug_keystore",
    properties = "debug.keystore.properties",
    store = "debug.keystore",
)
