# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_ASSERTJ_TARGET",
    "LITHO_BUILD_CONFIG_TARGET",
    "LITHO_INFERANNOTATIONS_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_JUNIT_TARGET",
    "LITHO_MOCKITO_TARGET",
    "LITHO_POWERMOCK_MOCKITO_TARGET",
    "LITHO_ROBOLECTRIC_V3_TARGET",
    "LITHO_SOLOADER_TARGET",
    "LITHO_TESTING_V3_TARGET",
    "LITHO_TESTING_WHITEBOX_TARGET",
    "LITHO_TEST_RES",
    "LITHO_VIEWCOMPAT_TARGET",
    "LITHO_WIDGET_TARGET",
    "LITHO_YOGA_TARGET",
    "components_robolectric_powermock_test",
    "make_dep_path",
)

components_robolectric_powermock_test(
    name = "litho",
    srcs = glob([
        "*Test.java",
        "widget/*Test.java",
    ]),
    contacts = ["oncall+components_for_android@xmail.facebook.com"],
    # This is our secret sauce for PowerMock.
    fork_mode = "per_test",
    provided_deps = [
        LITHO_ROBOLECTRIC_V3_TARGET,
    ],
    deps = [
        LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_ASSERTJ_TARGET,
        LITHO_BUILD_CONFIG_TARGET,
        LITHO_INFERANNOTATIONS_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JUNIT_TARGET,
        LITHO_MOCKITO_TARGET,
        LITHO_POWERMOCK_MOCKITO_TARGET,
        LITHO_SOLOADER_TARGET,
        LITHO_TESTING_V3_TARGET,
        LITHO_TESTING_WHITEBOX_TARGET,
        LITHO_TEST_RES,
        LITHO_VIEWCOMPAT_TARGET,
        LITHO_WIDGET_TARGET,
        LITHO_YOGA_TARGET,
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/assertj:assertj"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/shadows:shadows"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/testrunner:testrunner"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/util:util"),
    ],
)
