include_defs("//COMPONENTS_DEFS")

android_binary(
    name = "sample-barebones",
    keystore = ":debug_keystore",
    manifest = "src/main/AndroidManifest.xml",
    deps = [
        COMPONENTS_SAMPLE_BAREBONES_JAVA,
    ],
)

keystore(
    name = "debug_keystore",
    properties = "debug.keystore.properties",
    store = "debug.keystore",
)
