# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load("//:LITHO_DEFS", "LITHO_VISIBILITY")

java_library(
    name = "truth",
    exported_deps = [
        ":truth-prebuilt",
    ],
    visibility = LITHO_VISIBILITY,
)

prebuilt_jar(
    name = "truth-prebuilt",
    binary_jar = ":truth.jar",
)

remote_file(
    name = "truth.jar",
    sha1 = "7485219d2c1d341097a19382c02bde07e69ff5d2",
    url = "mvn:com.google.truth:truth:jar:0.36",
)
