load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_INFERANNOTATIONS_TARGET",
    "LITHO_JSR_TARGET",
    "LITHO_PROGUARD_ANNOTATIONS_TARGET",
    "LITHO_RENDERCORE_TARGET",
    "fb_android_library",
)

oncall("litho_components_for_android")

fb_android_library(
    name = "rendercore-transitions-stub",
    srcs = glob([
        "src/main/java/**/*.java",
        "src/main/java/**/*.kt",
    ]),
    autoglob = False,
    extra_kotlinc_arguments = ["-Xjvm-default=all"],
    feature = FBApp_UIFrameworks_Litho,
    labels = [],
    provided_deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_JSR_TARGET,
        LITHO_PROGUARD_ANNOTATIONS_TARGET,
    ],
    pure_kotlin = False,
    required_for_source_only_abi = True,
    visibility = ["PUBLIC"],
    deps = [
        LITHO_RENDERCORE_TARGET,
        LITHO_INFERANNOTATIONS_TARGET,
    ],
)
