# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load("//:COMPONENTS_DEFS", "litho_android_library")

litho_android_library(
    name = "viewcompat",
    srcs = glob(["**/*.java"]),
    visibility = [
        "PUBLIC",
    ],
)
