# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//LITHO_DEFS")

java_library(
    name = "model",
    srcs = glob([
        "*.java",
        "**/*.java",
    ]),
    source = "8",
    target = "8",
    visibility = [
        make_dep_path("litho-sections-processor/src/main/java/com/facebook/litho/sections/specmodels/processor:processor-lib"),
    ],
    deps = [
        LITHO_SECTIONS_ANNOTATIONS_TARGET,
        LITHO_ANNOTATIONS_TARGET,
        LITHO_PROCESSOR_LIB_TARGET,
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels:specmodels"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/internal:internal"),
    ],
)
