load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")

# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANNOTATIONS_TARGET",
    "LITHO_JAVAPOET_TARGET",
    "LITHO_JSR_TARGET",
    "LITHO_PROCESSOR_LIB_TARGET",
    "LITHO_SECTIONS_ANNOTATIONS_TARGET",
    "fb_java_library",
    "make_dep_path",
)

fb_java_library(
    name = "model",
    srcs = glob([
        "*.java",
        "**/*.java",
    ]),
    feature = FBApp_UIFrameworks_Litho_Litho,
    labels = [],
    source = "8",
    target = "8",
    visibility = [
        make_dep_path("litho-sections-processor/src/main/java/com/facebook/litho/sections/specmodels/processor:processor-lib"),
        make_dep_path("litho-sections-processor/src/test/java/com/facebook/litho/sections/specmodels/processor:processor"),
        make_dep_path("litho-intellij-plugin/src/test/java/com/facebook/litho:test"),
        make_dep_path("litho-it/src/test/java/com/facebook/litho/sections/specmodels/processor:processor"),
    ],
    deps = [
        LITHO_ANNOTATIONS_TARGET,
        LITHO_PROCESSOR_LIB_TARGET,
        LITHO_SECTIONS_ANNOTATIONS_TARGET,
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels:specmodels"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/internal:internal"),
    ],
)

fb_java_library(
    name = "model4idea",
    srcs = glob([
        "*.java",
        "**/*.java",
    ]),
    feature = FBApp_UIFrameworks_Litho_Litho,
    labels = [],
    provided_deps = [
        LITHO_JAVAPOET_TARGET,
        LITHO_JSR_TARGET,
        LITHO_ANNOTATIONS_TARGET,
        LITHO_SECTIONS_ANNOTATIONS_TARGET,
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/processor:processor-lib-bare4idea"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels:specmodels-bare4idea"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/internal:internal4idea"),
    ],
    source = "8",
    target = "8",
    visibility = [
        make_dep_path("litho-sections-processor/src/main/java/com/facebook/litho/sections/specmodels/processor:processor-lib-bare4idea"),
        make_dep_path("litho-intellij-plugin/src/main:main"),
    ],
)
