# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANNOTATIONS_TARGET",
    "LITHO_ASSERTJ_TARGET",
    "LITHO_COMPILE_TESTING_TARGET",
    "LITHO_GUAVA_JRE_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_JUNIT_TARGET",
    "LITHO_MOCKITO_KOTLIN_V2_TARGET",
    "LITHO_MOCKITO_V2_TARGET",
    "LITHO_PROCESSOR_LIB_TARGET",
    "LITHO_ROBOLECTRIC_V4_TARGET",
    "LITHO_SECTIONS_TARGET",
    "litho_robolectric4_test",
    "make_dep_path",
)

oncall("litho_components_for_android")

litho_robolectric4_test(
    name = "specmodels",
    srcs = glob(
        [
            "**/*Test.java",
            "**/*Test.kt",
        ],
        exclude = glob(["processor/**/*.java"]),
    ),
    contacts = ["oncall+litho_components_for_android@xmail.facebook.com"],
    source = "11",
    target = "11",
    target_sdk_levels = ["33"],
    vm_args = [
        "--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED",
    ],
    deps = [
        LITHO_ROBOLECTRIC_V4_TARGET,
        LITHO_ANNOTATIONS_TARGET,
        LITHO_ASSERTJ_TARGET,
        LITHO_COMPILE_TESTING_TARGET,
        LITHO_GUAVA_JRE_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JUNIT_TARGET,
        LITHO_MOCKITO_KOTLIN_V2_TARGET,
        LITHO_MOCKITO_V2_TARGET,
        LITHO_PROCESSOR_LIB_TARGET,
        LITHO_SECTIONS_TARGET,
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels:specmodels"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/internal:internal"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/model/testing:testing"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/specmodels:specmodels"),
    ],
)
