# BUILD FILE SYNTAX: SKYLARK
# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//:LITHO_DEFS.bzl", "LITHO_ANDROIDSUPPORT_TARGET", "LITHO_JSR_TARGET", "litho_android_library", "make_dep_path")

litho_android_library(
    name = "internal",
    srcs = glob(["*.java"]),
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/internal:internal"),
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_JSR_TARGET,
    ],
)
