# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

components_robolectric_test(
    name = "litho",
    srcs = glob(["**/*Test.java"]),
    contacts = ["oncall+components_for_android@xmail.facebook.com"],
    source = "8",
    target = "8",
    deps = [
        ":testspecs",
        make_dep_path("sample/src/main/java/com/facebook/samples/litho:litho"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/testrunner:testrunner"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/assertj:assertj"),
        COMPONENTS_JAVA_TARGET,
        COMPONENTS_TESTING_TARGET,
        COMPONENTS_JUNIT_TARGET,
        COMPONENTS_ROBOLECTRIC_TARGET,
        COMPONENTS_ASSERTJ_TARGET,
        COMPONENTS_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        COMPONENTS_WIDGET_TARGET,
        COMPONENTS_MOCKITO_TARGET,
        COMPONENTS_SECTIONS_WIDGET_TARGET,
    ],
)

android_library(
    name = "testspecs",
    srcs = glob(["**/Test*ComponentSpec.java"]),
    annotation_processor_deps = [
        COMPONENTS_PROCESSOR_LIB_TARGET,
    ],
    annotation_processors = [
        "com.facebook.litho.specmodels.processor.testing.ComponentsTestingProcessor",
    ],
    deps = [
        make_dep_path("sample/src/main/java/com/facebook/samples/litho:litho"),
        COMPONENTS_JAVA_TARGET,
        COMPONENTS_ANNOTATIONS_TARGET,
        COMPONENTS_ANDROIDSUPPORT_TARGET,
        COMPONENTS_TESTING_TARGET,
        COMPONENTS_TESTING_ASSERTJ_TARGET,
        COMPONENTS_JSR_TARGET,
        COMPONENTS_HAMCREST_CORE_TARGET,
        COMPONENTS_HAMCREST_LIBRARY_TARGET,
    ],
)
