# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_ANNOTATIONS_TARGET",
    "LITHO_ASSERTJ_TARGET",
    "LITHO_HAMCREST_CORE_TARGET",
    "LITHO_HAMCREST_LIBRARY_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_JSR_TARGET",
    "LITHO_JUNIT_TARGET",
    "LITHO_MOCKITO_TARGET",
    "LITHO_PROCESSOR_LIB_TARGET",
    "LITHO_ROBOLECTRIC_V3_TARGET",
    "LITHO_SECTIONS_WIDGET_TARGET",
    "LITHO_TESTING_ASSERTJ_V3_TARGET",
    "LITHO_TESTING_V3_TARGET",
    "LITHO_TESTING_WIDGET_TARGET",
    "LITHO_WIDGET_TARGET",
    "components_robolectric_test",
    "fb_core_android_library",
    "make_dep_path",
)

components_robolectric_test(
    name = "litho",
    srcs = glob(["**/*Test.java"]),
    contacts = ["oncall+components_for_android@xmail.facebook.com"],
    source = "8",
    target = "8",
    deps = [
        ":testspecs",
        LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        LITHO_ASSERTJ_TARGET,
        LITHO_HAMCREST_LIBRARY_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JUNIT_TARGET,
        LITHO_MOCKITO_TARGET,
        LITHO_ROBOLECTRIC_V3_TARGET,
        LITHO_SECTIONS_WIDGET_TARGET,
        LITHO_TESTING_V3_TARGET,
        LITHO_TESTING_WIDGET_TARGET,
        LITHO_WIDGET_TARGET,
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/assertj:assertj"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/testrunner:testrunner"),
        make_dep_path("sample/src/main/java/com/facebook/samples/litho:litho"),
    ],
)

fb_core_android_library(
    name = "testspecs",
    srcs = glob(["**/Test*ComponentSpec.java"]),
    annotation_processor_deps = [
        LITHO_PROCESSOR_LIB_TARGET,
    ],
    annotation_processors = [
        "com.facebook.litho.specmodels.processor.testing.ComponentsTestingProcessor",
    ],
    deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_ANNOTATIONS_TARGET,
        LITHO_HAMCREST_CORE_TARGET,
        LITHO_HAMCREST_LIBRARY_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JSR_TARGET,
        LITHO_TESTING_ASSERTJ_V3_TARGET,
        LITHO_TESTING_V3_TARGET,
        make_dep_path("sample/src/main/java/com/facebook/samples/litho:litho"),
    ],
    exported_deps = [
        make_dep_path("litho-testing/src/main/java/com/facebook/litho:litho"),
    ],
)
