# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//tools/build_defs/oss:fb_native_wrapper.bzl", "fb_native")
load("//tools/build_defs/oss:litho_defs.bzl", "LITHO_VISIBILITY")

fb_native.prebuilt_jar(
    name = "vtd-xml",
    binary_jar = ":vtd-xml.jar",
    visibility = LITHO_VISIBILITY,
)

fb_native.remote_file(
    name = "vtd-xml.jar",
    sha1 = "ee5bcf62c1acf76434ee9f1c67a840bafef72a6d",
    url = "mvn:com.ximpleware:vtd-xml:jar:2.11",
)
