include_defs("//COMPONENTS_DEFS")

prebuilt_jar(
    name = "vtd-xml",
    binary_jar = ":vtd-xml.jar",
    visibility = [
        COMPONENTS_VISIBILITY,
    ],
)

remote_file(
    name = "vtd-xml.jar",
    sha1 = "ee5bcf62c1acf76434ee9f1c67a840bafef72a6d",
    url = "mvn:com.ximpleware:vtd-xml:jar:2.11",
)
