# Copyright (c) Facebook, Inc. and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_JAVA_TARGET",
    "litho_android_library",
    "make_dep_path",
)

oncall("playgroundapps")

litho_android_library(
    name = "litho-compose",
    srcs = glob(["**/*.kt"]),
    autoglob = False,
    feature = FBApp_UIFrameworks_Litho_Litho,
    k2 = True,
    labels = [],
    provided_deps = [
    ],
    required_for_source_only_abi = True,
    tests = [make_dep_path("litho-compose/src/test/kotlin/com/facebook/litho:litho-compose")],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_JAVA_TARGET,
        "//fbandroid/libraries/components/litho-widget/src/main/java/com/facebook/litho/widget:widget-bare",
        "//fbandroid/libraries/rendercore/rendercore-primitive-components/compose:compose",
        "//fbandroid/third-party/android/androidx/compose:runtime",
    ],
    exported_deps = ["//fbandroid/libraries/rendercore/rendercore-primitive-components/compose:compose"],
)
