# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//LITHO_DEFS")

fb_java_test(
    name = "sections",
    srcs = glob(["*Test.java"]),
    source = "1.8",
    target = "1.8",
    deps = [
        LITHO_COMPILE_TESTING_TARGET,
        LITHO_TRUTH_TARGET,
        LITHO_ASSERTJ_TARGET,
        LITHO_TESTING_TARGET,
        LITHO_TESTING_ASSERTJ_TARGET,
        LITHO_GUAVA_TARGET,
        LITHO_JAVAC_TOOLS_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JUNIT_TARGET,
        LITHO_PROCESSOR_LIB_TARGET,
        LITHO_ROBOLECTRIC_TARGET,
        LITHO_PROCESSOR_LIB_TARGET,
        LITHO_SECTIONS_TARGET,
        LITHO_SECTIONS_PROCESSOR_LIB_TARGET,
        make_dep_path("litho-it/src/test/resources:resources"),
    ],
)
