# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//tools/build_defs/oss:litho_defs.bzl", "LITHO_ASSERTJ_TARGET", "LITHO_COMPILE_TESTING_TARGET", "LITHO_GUAVA_TARGET", "LITHO_JAVAC_TOOLS_TARGET", "LITHO_JAVA_TARGET", "LITHO_JUNIT_TARGET", "LITHO_PROCESSOR_LIB_TARGET", "LITHO_ROBOLECTRIC_V3_TARGET", "LITHO_SECTIONS_PROCESSOR_LIB_TARGET", "LITHO_SECTIONS_TARGET", "LITHO_TESTING_ASSERTJ_TARGET", "LITHO_TESTING_TARGET", "LITHO_TRUTH_TARGET", "fb_java_test", "make_dep_path")

fb_java_test(
    name = "sections",
    # T41117446 Enable them after switching target to AndroidX
    srcs = glob(["*Test.java"]),
    source = "1.8",
    target = "1.8",
    deps = [
        LITHO_COMPILE_TESTING_TARGET,
        LITHO_TRUTH_TARGET,
        LITHO_ASSERTJ_TARGET,
        LITHO_TESTING_TARGET,
        LITHO_TESTING_ASSERTJ_TARGET,
        LITHO_GUAVA_TARGET,
        LITHO_JAVAC_TOOLS_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JUNIT_TARGET,
        LITHO_PROCESSOR_LIB_TARGET,
        LITHO_ROBOLECTRIC_V3_TARGET,
        LITHO_PROCESSOR_LIB_TARGET,
        LITHO_SECTIONS_TARGET,
        LITHO_SECTIONS_PROCESSOR_LIB_TARGET,
        make_dep_path("litho-it/src/test/resources:resources"),
    ],
)
