# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

fb_java_test(
    name = "sections",
    srcs = glob(["*Test.java"]),
    source = "1.8",
    target = "1.8",
    deps = [
        COMPONENTS_COMPILE_TESTING_TARGET,
        COMPONENTS_TRUTH_TARGET,
        COMPONENTS_ASSERTJ_TARGET,
        COMPONENTS_TESTING_TARGET,
        COMPONENTS_TESTING_ASSERTJ_TARGET,
        COMPONENTS_GUAVA_TARGET,
        COMPONENTS_JAVAC_TOOLS_TARGET,
        COMPONENTS_JAVA_TARGET,
        COMPONENTS_JUNIT_TARGET,
        COMPONENTS_PROCESSOR_LIB_TARGET,
        COMPONENTS_ROBOLECTRIC_TARGET,
        COMPONENTS_PROCESSOR_LIB_TARGET,
        COMPONENTS_SECTIONS_TARGET,
        COMPONENTS_SECTIONS_PROCESSOR_LIB_TARGET,
        make_dep_path("litho-it/src/test/resources:resources"),
    ],
)
