# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANNOTATIONS_TARGET",
    "LITHO_ASSERTJ_TARGET",
    "LITHO_BUILD_CONFIG_TARGET",
    "LITHO_COMPILE_TESTING_TARGET",
    "LITHO_JAVAC_TOOLS_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_MOCKITO_TARGET",
    "LITHO_PROCESSOR_LIB_TARGET",
    "LITHO_ROBOLECTRIC_V3_TARGET",
    "LITHO_SECTIONS_TARGET",
    "components_robolectric_test",
    "make_dep_path",
)

components_robolectric_test(
    name = "processor",
    srcs = glob(
        ["*Test.java"],
    ),
    provided_deps = [
        LITHO_ROBOLECTRIC_V3_TARGET,
    ],
    source = "8",
    target = "8",
    deps = [
        LITHO_ANNOTATIONS_TARGET,
        LITHO_ASSERTJ_TARGET,
        LITHO_BUILD_CONFIG_TARGET,
        LITHO_COMPILE_TESTING_TARGET,
        LITHO_JAVAC_TOOLS_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_MOCKITO_TARGET,
        LITHO_PROCESSOR_LIB_TARGET,
        LITHO_SECTIONS_TARGET,
        make_dep_path("litho-it/src/main/java/com/facebook/litho/testing/treeprop:treeprop"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/assertj:assertj"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/sections:sections"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/testrunner:testrunner"),
    ],
)
