load("//tools/build_defs/oss:fb_native_wrapper.bzl", "fb_native")
load("//tools/build_defs/oss:litho_defs.bzl", "fb_java_library")

fb_java_library(
    name = "guava",
    visibility = ["PUBLIC"],
    exported_deps = [
        ":guava-prebuilt",
    ],
)

fb_native.prebuilt_jar(
    name = "guava-prebuilt",
    binary_jar = ":guava.jar",
)

fb_native.remote_file(
    name = "guava.jar",
    sha1 = "89507701249388e1ed5ddcf8c41f4ce1be7831ef",
    url = "mvn:com.google.guava:guava:jar:20.0",
)
