# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//tools/build_defs/oss:fb_native_wrapper.bzl", "fb_native")

fb_native.android_prebuilt_aar(
    name = "soloader",
    aar = ":soloader.aar",
    visibility = ["PUBLIC"],
)

fb_native.remote_file(
    name = "soloader.aar",
    sha1 = "4de8f64830aff60beb52fb27dffb2fcbe54c39df",
    url = "mvn:com.facebook.soloader:soloader:aar:0.6.0",
)
