# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_PROCESSOR_LIB_TARGET",
    "fb_java_library",
    "make_dep_path",
)

fb_java_library(
    name = "processor",
    srcs = ["TestingDIComponentProcessor.java"],
    source = "8",
    target = "8",
    visibility = [
        make_dep_path("litho-it/..."),
    ],
    deps = [
        LITHO_PROCESSOR_LIB_TARGET,
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels:specmodels-bare"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/generator/testing:testing"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/internal:internal"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/model/testing:testing"),
    ],
)
