# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_TESTING_TARGET",
    "LITHO_ESPRESSO_TARGET",
    "LITHO_HAMCREST_LIBRARY_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_JUNIT_TARGET",
    "LITHO_SOLOADER_TARGET",
    "fb_core_android_library",
)

fb_core_android_library(
    name = "espresso",
    srcs = glob(["*.java"]),
    is_androidx = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_ANDROIDSUPPORT_TESTING_TARGET,
        LITHO_ESPRESSO_TARGET,
        LITHO_HAMCREST_LIBRARY_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JUNIT_TARGET,
        LITHO_SOLOADER_TARGET,
    ],
)
