include_defs("//COMPONENTS_DEFS")

components_robolectric_test(
    name = "viewtree",
    srcs = glob(["*Test.java"]),
    contacts = ["oncall+components_for_android@xmail.facebook.com"],
    deps = [
