include_defs("//COMPONENTS_DEFS")

components_robolectric_test(
    name = "viewtree",
    srcs = glob(["*Test.java"]),
    contacts = ["oncall+components_for_android@xmail.facebook.com"],
    deps = [
        COMPONENTS_GUAVA_TARGET,
        COMPONENTS_JAVA_TARGET,
        COMPONENTS_JSR_TARGET,
        COMPONENTS_JUNIT_TARGET,
        COMPONENTS_ROBOLECTRIC_TARGET,
        make_dep_path("litho-widget/src/main/java/com/facebook/litho/widget:widget"),
