# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//LITHO_DEFS")

components_robolectric_test(
    name = "internal",
    srcs = glob(["*Test.java"]),
    source = "8",
    target = "8",
    deps = [
        make_dep_path("litho-core/src/main/java/com/facebook/litho/internal:internal"),
        LITHO_JUNIT_TARGET,
        LITHO_ASSERTJ_TARGET,
    ],
)
