# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ASSERTJ_TARGET",
    "LITHO_JUNIT_TARGET",
    "litho_robolectric4_test",
    "make_dep_path",
)

litho_robolectric4_test(
    name = "internal",
    srcs = glob(["*Test.java"]),
    source = "8",
    target = "8",
    deps = [
        LITHO_ASSERTJ_TARGET,
        LITHO_JUNIT_TARGET,
        make_dep_path("litho-core/src/main/java/com/facebook/litho/internal:internal"),
    ],
)
