# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//:LITHO_DEFS.bzl", "LITHO_ASSERTJ_TARGET", "LITHO_JUNIT_TARGET", "make_dep_path", "components_robolectric_test")

components_robolectric_test(
    name = "internal",
    srcs = glob(["*Test.java"]),
    source = "8",
    target = "8",
    deps = [
        make_dep_path("litho-core/src/main/java/com/facebook/litho/internal:internal"),
        LITHO_JUNIT_TARGET,
        LITHO_ASSERTJ_TARGET,
    ],
)
