# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ASSERTJ_TARGET",
    "LITHO_JUNIT_TARGET",
    "LITHO_VISIBILITY",
    "fb_java_test",
    "make_dep_path",
)

fb_java_test(
    name = "processor",
    srcs = glob(
        ["**/*.java"],
        exclude = [""],
        include_dotfiles = False,
    ),
    source = "8",
    target = "8",
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/specmodels/processor:processor"),
    ],
    visibility = LITHO_VISIBILITY,
    deps = [
        LITHO_ASSERTJ_TARGET,
        LITHO_JUNIT_TARGET,
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels:specmodels"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/internal:internal"),
    ],
)
