# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_JSR_TARGET",
    "litho_android_library",
    "make_dep_path",
)

litho_android_library(
    name = "config",
    feature = FBApp_UIFrameworks_Litho_Litho,
    labels = [],
    language = "JAVA",
    visibility = ["PUBLIC"],
    deps = [
        LITHO_JSR_TARGET,
        make_dep_path("litho-sections-core/src/main/java/com/facebook/litho/sections/logger:logger"),
    ],
)
