# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

prebuilt_jar(
    name = "CSSLayoutDEPRECATED-jar",
    binary_jar = "CSSLayoutDEPRECATED.jar",
)

java_library(
    name = "CSSLayoutDEPRECATED",
    exported_deps = [
        ":CSSLayoutDEPRECATED-jar",
    ],
    visibility = [
        COMPONENTS_VISIBILITY,
    ],
)
