include_defs("//COMPONENTS_DEFS")

prebuilt_jar(
    name = "CSSLayoutDEPRECATED-jar",
    binary_jar = "CSSLayoutDEPRECATED.jar",
)

java_library(
    name = "CSSLayoutDEPRECATED",
    exported_deps = [
        ":CSSLayoutDEPRECATED-jar",
    ],
    visibility = [
        COMPONENTS_VISIBILITY,
    ],
)
