# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_TESTING_CORE_TARGET",
    "LITHO_BUILD_CONFIG_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_PROCESSOR_TARGET",
    "LITHO_PROGUARD_ANNOTATIONS_TARGET",
    "LITHO_ROBOLECTRIC_V4_TARGET",
    "LITHO_SECTIONS_ANNOTATIONS_TARGET",
    "LITHO_SECTIONS_COMMON_TARGET",
    "LITHO_SECTIONS_PROCESSOR_TARGET",
    "LITHO_SECTIONS_TARGET",
    "LITHO_SECTIONS_WIDGET_TARGET",
    "LITHO_TESTING_V4_TARGET",
    "LITHO_WIDGET_TARGET",
    "litho_robolectric4_test",
    "make_dep_path",
)

litho_robolectric4_test(
    name = "litho",
    srcs = glob([
        "**/*.java",
    ]),
    contacts = ["oncall+components_for_android@xmail.facebook.com"],
    is_androidx = True,
    plugins = [
        LITHO_PROCESSOR_TARGET,
        LITHO_SECTIONS_PROCESSOR_TARGET,
    ],
    provided_deps = [
        LITHO_PROGUARD_ANNOTATIONS_TARGET,
        LITHO_ROBOLECTRIC_V4_TARGET,
    ],
    deps = [
        LITHO_ANDROIDSUPPORT_TESTING_CORE_TARGET,
        LITHO_BUILD_CONFIG_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_SECTIONS_ANNOTATIONS_TARGET,
        LITHO_SECTIONS_COMMON_TARGET,
        LITHO_SECTIONS_TARGET,
        LITHO_SECTIONS_WIDGET_TARGET,
        LITHO_TESTING_V4_TARGET,
        LITHO_WIDGET_TARGET,
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/assertj:assertj-v4"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/testrunner:testrunner-v4"),
    ],
)
