# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load("//tools/build_defs/oss:fb_native_wrapper.bzl", "fb_native")
load("//tools/build_defs/oss:litho_defs.bzl", "LITHO_VISIBILITY", "fb_java_library", "make_dep_path")

fb_java_library(
    name = "compile-testing",
    visibility = LITHO_VISIBILITY,
    exported_deps = [
        ":compile-testing-prebuilt",
        make_dep_path("lib/junit:junit"),
        make_dep_path("lib/guava:guava"),
        make_dep_path("lib/truth:truth"),
    ],
)

fb_native.prebuilt_jar(
    name = "compile-testing-prebuilt",
    binary_jar = ":compile-testing.jar",
    visibility = LITHO_VISIBILITY,
)

fb_native.remote_file(
    name = "compile-testing.jar",
    sha1 = "3d9e885e2dfe4e6ceabc4402419abf3879c7429e",
    url = "mvn:com.google.testing.compile:compile-testing:jar:0.14",
)
