# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

java_library(
    name = "compile-testing",
    exported_deps = [
        ":compile-testing-prebuilt",
        make_dep_path("lib/junit:junit"),
        make_dep_path("lib/guava:guava"),
        make_dep_path("lib/truth:truth"),
    ],
    visibility = [
        COMPONENTS_VISIBILITY,
    ],
)

prebuilt_jar(
    name = "compile-testing-prebuilt",
    binary_jar = ":compile-testing.jar",
    visibility = [
        COMPONENTS_VISIBILITY,
    ],
)

remote_file(
    name = "compile-testing.jar",
    sha1 = "51e6189be9d2861d1eb22b4009c8f3430319490c",
    url = "mvn:com.google.testing.compile:compile-testing:jar:0.10",
)
