# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET",
    "LITHO_ASSERTJ_TARGET",
    "LITHO_HAMCREST_LIBRARY_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_JUNIT_TARGET",
    "LITHO_MOCKITO_TARGET",
    "LITHO_ROBOLECTRIC_V4_TARGET",
    "LITHO_SECTIONS_WIDGET_TARGET",
    "LITHO_TESTING_TARGET",
    "LITHO_TESTING_WIDGET_TARGET",
    "LITHO_WIDGET_TARGET",
    "litho_robolectric4_test",
    "make_dep_path",
)

litho_robolectric4_test(
    name = "modules",
    srcs = glob(["**/*Test.java"]),
    contacts = ["oncall+components_for_android@xmail.facebook.com"],
    source = "8",
    target = "8",
    deps = [
        LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        LITHO_ASSERTJ_TARGET,
        LITHO_HAMCREST_LIBRARY_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JUNIT_TARGET,
        LITHO_MOCKITO_TARGET,
        LITHO_ROBOLECTRIC_V4_TARGET,
        LITHO_SECTIONS_WIDGET_TARGET,
        LITHO_TESTING_TARGET,
        LITHO_TESTING_WIDGET_TARGET,
        LITHO_WIDGET_TARGET,
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/assertj:assertj"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/testrunner:testrunner"),
        make_dep_path("sample-codelab/src/main/java/com/facebook/samples/lithocodelab:lithocodelab"),
    ],
)
