# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_JAVA_TARGET",
    "LITHO_PERF_LOGGER",
    "LITHO_TESTING_CORE_TARGET",
    "litho_android_library",
)

litho_android_library(
    name = "logging",
    language = "JAVA",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//fbandroid/third-party/java/infer-annotations:infer-annotations",
        "//third-party/java/androidx/annotation/annotation:annotation",
        LITHO_JAVA_TARGET,
        LITHO_PERF_LOGGER,
        LITHO_TESTING_CORE_TARGET,
    ],
    exported_deps = [
        LITHO_PERF_LOGGER,
    ],
)
