include_defs("//COMPONENTS_DEFS")

android_library(
    name = "components",
    srcs = glob([
        "*.java",
        "reference/*.java",
        "displaylist/*.java",
    ]),
    exported_deps = [
        COMPONENTS_ANDROIDSUPPORT_TARGET,
        COMPONENTS_ANNOTATIONS_TARGET,
        COMPONENTS_CONFIG_TARGET,
        COMPONENTS_CSSLAYOUT_TARGET,
        COMPONENTS_PROGUARDANNOTATIONS_TARGET,
        COMPONENTS_RELAYOUT_TARGET,
        COMPONENTS_YOGA_TARGET,
    ],
    provided_deps = [
        COMPONENTS_DISPLAYLISTSUBS_TARGET,
    ],
    visibility = [
        COMPONENTS_VISIBILITY,
    ],
    deps = [
        COMPONENTS_INFERANNOTATIONS_TARGET,
        COMPONENTS_JSR_TARGET,
        COMPONENTS_RES_TARGET,
        COMPONENTS_VIEWCOMPATCREATOR_TARGET,
    ],
)
