load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_ANNOTATION_TARGET",
    "LITHO_RENDERCORE_TARGET",
    "fb_android_library",
)

fb_android_library(
    name = "rendercore-primitives",
    srcs = glob(
        ["src/main/java/**/*.kt"],
    ),
    autoglob = False,
    feature = FBApp_UIFrameworks_Litho,
    labels = [],
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_RENDERCORE_TARGET,
        LITHO_ANDROIDSUPPORT_ANNOTATION_TARGET,
    ],
)
