# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANNOTATIONS_TARGET",
    "LITHO_ASSERTJ_TARGET",
    "LITHO_BUILD_CONFIG_TARGET",
    "LITHO_COMPILE_TESTING_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_MOCKITO_V2_TARGET",
    "LITHO_PROCESSOR_LIB_TARGET",
    "LITHO_ROBOLECTRIC_V4_TARGET",
    "LITHO_TESTING_TARGET",
    "LITHO_TESTING_WIDGET_TARGET",
    "LITHO_WIDGET_TARGET",
    "litho_robolectric4_test",
    "make_dep_path",
)

litho_robolectric4_test(
    name = "testing",
    srcs = glob(["*Test.java"]),
    provided_deps = [
        LITHO_ROBOLECTRIC_V4_TARGET,
    ],
    source = "8",
    target = "8",
    deps = [
        LITHO_ANNOTATIONS_TARGET,
        LITHO_ASSERTJ_TARGET,
        LITHO_BUILD_CONFIG_TARGET,
        LITHO_COMPILE_TESTING_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_MOCKITO_V2_TARGET,
        LITHO_PROCESSOR_LIB_TARGET,
        LITHO_TESTING_TARGET,
        LITHO_TESTING_WIDGET_TARGET,
        LITHO_WIDGET_TARGET,
        make_dep_path("litho-it/specs/src/main/java/com/facebook/litho/testing/specmodels:specmodels"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels:specmodels"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/internal:internal"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/model/testing:testing"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/assertj:assertj"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/testrunner:testrunner"),
    ],
)
