# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_MATERIAL_TARGET",
    "LITHO_JSR_TARGET",
    "LITHO_OSS_TARGET",
    "LITHO_PROCESSOR_TARGET",
    "LITHO_UTILS_TARGET",
    "LITHO_WIDGET_TARGET",
    "litho_android_library",
)

litho_android_library(
    name = "widget",
    is_androidx = True,
    labels = ["supermodule:android/default/litho.core"],
    plugins = [
        LITHO_PROCESSOR_TARGET,
    ],
    provided_deps = [
        LITHO_JSR_TARGET,
        LITHO_OSS_TARGET,
        LITHO_UTILS_TARGET,
    ],
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_ANDROIDSUPPORT_MATERIAL_TARGET,
        LITHO_WIDGET_TARGET,
    ],
)
