# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

android_library(
    name = "eventhandler",
    srcs = glob(["*.java"]),
    visibility = [
        "//instrumentation_tests/...",
        "//javatests/...",
    ],
    deps = [
        "//libraries/components/src/main/java/com/facebook/components:components",
        "//third-party/java/mockito:mockito",
    ],
)
