android_library(
    name = "eventhandler",
    srcs = glob(["*.java"]),
    visibility = [
        "//instrumentation_tests/...",
        "//javatests/...",
    ],
    deps = [
        "//libraries/components/src/main/java/com/facebook/components:components",
        "//third-party/java/mockito:mockito",
    ],
)
