load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_INFERANNOTATIONS_TARGET",
    "LITHO_RENDERCORE_TARGET",
    "LITHO_YOGA_TARGET",
)

android_library(
    name = "litho-rendercore-yoga",
    srcs = glob(["src/main/java/**/*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_RENDERCORE_TARGET,
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_INFERANNOTATIONS_TARGET,
    ],
    exported_deps = [
        LITHO_YOGA_TARGET,
    ],
)
