include_defs("//COMPONENTS_DEFS")

# This target is only used in open source and will break the monobuild
# because we cannot define `soname` multiple times.
if COMPONENTS_IS_OSS_BUILD:
  cxx_library(
    name = 'jni',
    soname = 'libyoga.$(ext)',
    srcs = glob(['jni/*.cpp']),
    header_namespace = '',
    compiler_flags = [
      '-fno-omit-frame-pointer',
      '-fexceptions',
      '-Wall',
      '-Werror',
      '-O3',
      '-std=c++11',
    ],
    deps = [
      ":yoga",
      COMPONENTS_FBJNI_TARGET,
    ],
    visibility = [COMPONENTS_VISIBILITY],
  )
