# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

include_defs("//LITHO_DEFS")

# This target is only used in open source and will break the monobuild
# because we cannot define `soname` multiple times.
if LITHO_IS_OSS_BUILD:
  fb_prebuilt_cxx_library(
      name = "ndklog",
      exported_platform_linker_flags = [
          (
              "^android.*",
              ["-llog"],
          ),
      ],
      header_only = True,
      visibility = LITHO_VISIBILITY,
  )

  fb_xplat_cxx_library(
    name = 'jni',
    soname = 'libyoga.$(ext)',
    srcs = glob(['src/main/cpp/jni/*.cpp']),
    header_namespace = '',
    compiler_flags = [
      '-fno-omit-frame-pointer',
      '-fexceptions',
      '-Wall',
      '-Werror',
      '-O3',
      '-std=c++11',
    ],
    deps = [
      make_dep_path("lib/yoga/src/main/cpp:yoga"),
      LITHO_FBJNI_TARGET,
      ":ndklog",
    ],
    visibility = LITHO_VISIBILITY,
  )
