prebuilt_jar(
    name = "commons-cli",
    binary_jar = "commons-cli-1.3.1.jar",
    javadoc_url = "http://commons.apache.org/proper/commons-cli/javadocs/api-1.3.1/",
    visibility = [
        "PUBLIC",
    ],
)
