# BUILD FILE SYNTAX: SKYLARK
# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//:LITHO_DEFS.bzl", "LITHO_VISIBILITY")

prebuilt_jar(
    name = "commons-cli",
    binary_jar = ":commons-cli.jar",
    visibility = LITHO_VISIBILITY,
)

remote_file(
    name = "commons-cli.jar",
    sha1 = "1303efbc4b181e5a58bf2e967dc156a3132b97c0",
    url = "mvn:commons-cli:commons-cli:jar:1.3.1",
)
