# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

java_library(
    name = "assertj",
    exported_deps = [
        ":assertj-core-prebuilt",
    ],
    visibility = ["PUBLIC"],
)

prebuilt_jar(
    name = "assertj-core-prebuilt",
    binary_jar = ":assertj-core.jar",
)

remote_file(
    name = "assertj-core.jar",
    sha1 = "716730b203ba8bbc075241e9f13ccbae6ddbdf13",
    url = "mvn:org.assertj:assertj-core:jar:2.8.0",
)
