include_defs("//COMPONENTS_DEFS")

oss_components_robolectric_test(
    name = "oss_components",
    srcs = glob(["*Test.java"]),
    contacts = ["oncall+components_for_android@xmail.facebook.com"],
    provided_deps = [
        COMPONENTS_ROBOLECTRIC_TARGET,
    ],
    deps = [
        COMPONENTS_JAVA_TARGET,
        COMPONENTS_JUNIT_TARGET,
        COMPONENTS_ASSERTJ_TARGET,
        COMPONENTS_MOCKITO_TARGET,
        COMPONENTS_POWERMOCK_REFLECT_TARGET,
        COMPONENTS_SOLOADER_TARGET,
        COMPONENTS_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        make_dep_path("src/main/java/com/facebook/components/widget:widget"),
        make_dep_path("src/debug/java/com/facebook/components/testing:testing"),
        make_dep_path("src/debug/java/com/facebook/components/testing/testrunner:testrunner"),
    ],
)
