# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_TESTING_CORE_TARGET",
    "LITHO_BUILD_CONFIG_TARGET",
    "LITHO_GUAVA_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_ROBOLECTRIC_V4_TARGET",
    "LITHO_TESTING_TARGET",
    "LITHO_TEST_RES",
    "LITHO_WIDGET_TARGET",
    "litho_robolectric4_test",
    "make_dep_path",
)

litho_robolectric4_test(
    name = "viewtree",
    srcs = glob(["*Test.java"]),
    contacts = ["oncall+components_for_android@xmail.facebook.com"],
    fork_mode = "per_test",
    source = "8",
    target = "8",
    deps = [
        LITHO_ANDROIDSUPPORT_TESTING_CORE_TARGET,
        LITHO_BUILD_CONFIG_TARGET,
        LITHO_GUAVA_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_ROBOLECTRIC_V4_TARGET,
        LITHO_TESTING_TARGET,
        LITHO_TEST_RES,
        LITHO_WIDGET_TARGET,
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/assertj:assertj"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/shadows:shadows"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/testrunner:testrunner"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/viewtree:viewtree"),
    ],
)
