load("//tools/build_defs/oss:litho_defs.bzl", "LITHO_BUILD_CONFIG_TARGET", "LITHO_GUAVA_TARGET", "LITHO_JAVA_TARGET", "LITHO_ROBOLECTRIC_V3_TARGET", "LITHO_TESTING_V3_TARGET", "LITHO_TEST_RES", "components_robolectric_test", "make_dep_path")

components_robolectric_test(
    name = "viewtree",
    srcs = glob(["*Test.java"]),
    contacts = ["oncall+components_for_android@xmail.facebook.com"],
    deps = [
        LITHO_BUILD_CONFIG_TARGET,
        LITHO_GUAVA_TARGET,
        make_dep_path("litho-widget/src/main/java/com/facebook/litho/widget:widget"),
        LITHO_JAVA_TARGET,
        LITHO_ROBOLECTRIC_V3_TARGET,
        LITHO_TESTING_V3_TARGET,
        LITHO_TEST_RES,
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/shadows:shadows"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/testrunner:testrunner"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/viewtree:viewtree"),
    ],
)
