include_defs("//COMPONENTS_DEFS")

android_library(
    name = "lithobarebones",
    srcs = glob(["**/*.java"]),
    annotation_processor_deps = [
        COMPONENTS_PROCESSOR_LIB_TARGET,
    ],
    annotation_processors = [
        "com.facebook.components.processor.ComponentsProcessor",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        COMPONENTS_ROOT_TARGET,
        COMPONENTS_WIDGET_TARGET,
        COMPONENTS_SOLOADER_TARGET,
        COMPONENTS_ANDROIDSUPPORT_TARGET,
        COMPONENTS_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
    ],
)
