# BUILD FILE SYNTAX: SKYLARK
# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

# This is a package of stubs, to allow the calling of a hidden DisplayList
# methods. They must be referenced as provided_deps. Since future platforms
# may change this hidden API, callers should handle LinkageError gracefully.

load("//:LITHO_DEFS.bzl", "LITHO_STUBS_VISIBILITY", "fb_android_library")

fb_android_library(
    name = "stubs",
    srcs = glob([
        "src/**/*.java",
    ]),
    visibility = LITHO_STUBS_VISIBILITY,
)
