# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

# This target is only used in open source
if COMPONENTS_IS_OSS_BUILD:
  cxx_library(
    name = 'jni',
    soname = 'libfb.$(ext)',
    srcs = glob(['*.cpp', 'jni/*.cpp', 'lyra/*.cpp']),
    header_namespace = '',
    compiler_flags = [
      '-fno-omit-frame-pointer',
      '-fexceptions',
      '-Wall',
      '-std=c++11',
      '-DDISABLE_CPUCAP',
      '-DDISABLE_XPLAT',
    ],
    exported_headers = subdir_glob([
      ('include', 'fb/**/*.h'),
      ('include', 'jni/*.h'),
    ]),
    deps = [
