# Copyright 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE-examples file in the root directory of this source tree.

include_defs("//COMPONENTS_DEFS")

android_library(
    name = "litho",
    srcs = glob(["**/*.java"]),
    annotation_processor_deps = [
        COMPONENTS_PROCESSOR_LIB_TARGET,
    ],
    annotation_processors = [
        "com.facebook.litho.specmodels.processor.ComponentsProcessor",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        COMPONENTS_ROOT_TARGET,
        COMPONENTS_RES_TARGET,
        COMPONENTS_UTILS_TARGET,
        COMPONENTS_WIDGET_TARGET,
        COMPONENTS_SAMPLE_CODELAB_RES,
        COMPONENTS_SOLOADER_TARGET,
        COMPONENTS_ANDROIDSUPPORT_TARGET,
        COMPONENTS_ANDROIDSUPPORT_APPCOMPAT_TARGET,
        COMPONENTS_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        COMPONENTS_JSR_TARGET,
        COMPONENTS_YOGA_TARGET,
        COMPONENTS_YOGAJNI_TARGET,
    ],
)
