include_defs("//COMPONENTS_DEFS")

android_library(
    name = "testing",
    srcs = glob(["*.java"]),
    provided_deps = [
        COMPONENTS_ROBOLECTRIC_TARGET,
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        COMPONENTS_JAVA_TARGET,
        COMPONENTS_RES_TARGET,
        COMPONENTS_JSR_TARGET,
        "//libraries/components/src/main/java/com/facebook/components/widget:widget",
        "//libraries/fresco/drawee/src/main/java/com/facebook/drawee/drawable:drawable",
        "//third-party/java/powermock/reflect:reflect",
    ],
)
