include_defs("//COMPONENTS_DEFS")

android_library(
    name = "testing",
    srcs = glob(["*.java"]),
    provided_deps = [
        COMPONENTS_ROBOLECTRIC_TARGET,
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        COMPONENTS_JAVA_TARGET,
        COMPONENTS_RES_TARGET,
        COMPONENTS_JSR_TARGET,
        COMPONENTS_FRESCO_TARGET,
        COMPONENTS_POWERMOCK_REFLECT_TARGET,
        make_dep_path("src/main/java/com/facebook/components/widget:widget"),
    ],
)
