standard_android_library(
    provided_deps = [
        "//third-party/java/robolectric3/robolectric:robolectric",
    ],
    deps = [
        "//libraries/components:components",
        "//libraries/components:res",
        "//libraries/components/src/main/java/com/facebook/components/widget:widget",
        "//libraries/fresco/drawee/src/main/java/com/facebook/drawee/drawable:drawable",
        "//third-party/java/jsr-305:jsr-305",
        "//third-party/java/powermock/reflect:reflect",
    ],
)
