load("//tools/build_defs/oss:litho_defs.bzl", "fb_java_library")

fb_java_library(
    name = "editor",
    srcs = glob(["**/*.java"]),
    labels = ["supermodule:android/default/litho.core"],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//fbandroid/third-party/java/jsr-305:jsr-305",
    ],
)
