# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

android_prebuilt_aar(
    name = "stetho",
    aar = ":stetho-aar",
    visibility = COMPONENTS_VISIBILITY,
    deps = [
        COMPONENTS_COMMONS_CLI_TARGET,
    ],
)

remote_file(
    name = "stetho-aar",
    sha1 = "9ed0e0a9ab9134f34a5bce11ea543f432f9b08b3",
    url = "mvn:com.facebook.stetho:stetho:aar:1.5.0",
)
