# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load("//:LITHO_DEFS", "LITHO_ANDROIDSUPPORT_TARGET", "LITHO_ROBOLECTRIC_TARGET", "LITHO_JAVA_TARGET", "LITHO_POWERMOCK_REFLECT_TARGET", "LITHO_TESTING_SUBCOMPONENTS_TARGET", "litho_android_library")

litho_android_library(
    name = "helper",
    srcs = glob(["*.java"]),
    provided_deps = [
        LITHO_ROBOLECTRIC_TARGET,
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_JAVA_TARGET,
        LITHO_TESTING_SUBCOMPONENTS_TARGET,
        LITHO_POWERMOCK_REFLECT_TARGET,
        LITHO_ANDROIDSUPPORT_TARGET,
    ],
)
