# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load("//:COMPONENTS_DEFS", "COMPONENTS_ANDROIDSUPPORT_TARGET", "COMPONENTS_ROBOLECTRIC_TARGET", "COMPONENTS_JAVA_TARGET", "COMPONENTS_POWERMOCK_REFLECT_TARGET", "COMPONENTS_TESTING_SUBCOMPONENTS_TARGET", "litho_android_library")

litho_android_library(
    name = "helper",
    srcs = glob(["*.java"]),
    provided_deps = [
        COMPONENTS_ROBOLECTRIC_TARGET,
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        COMPONENTS_JAVA_TARGET,
        COMPONENTS_TESTING_SUBCOMPONENTS_TARGET,
        COMPONENTS_POWERMOCK_REFLECT_TARGET,
        COMPONENTS_ANDROIDSUPPORT_TARGET,
    ],
)
