# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_ANNOTATIONS_TARGET",
    "LITHO_ASSERTJ_TARGET",
    "LITHO_COMPILE_TESTING_TARGET",
    "LITHO_HAMCREST_CORE_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_MOCKITO_V2_TARGET",
    "LITHO_PROCESSOR_LIB_TARGET",
    "LITHO_TESTING_ASSERTJ_TARGET",
    "LITHO_TESTING_CORE_TARGET",
    "LITHO_TESTING_SUBCOMPONENTS_TARGET",
    "LITHO_WIDGET_TARGET",
    "LITHO_YOGA_TARGET",
    "fb_core_android_library",
    "make_dep_path",
)

fb_core_android_library(
    name = "specmodels",
    srcs = glob(["*.java"]),
    annotation_processor_deps = [
        make_dep_path("litho-it/processor/src/main/java/com/facebook/litho/testing/processor:processor"),
    ],
    annotation_processors = [
        "com.facebook.litho.testing.processor.TestingDIComponentProcessor",
    ],
    source = "8",
    target = "8",
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/specmodels/processor/testing:testing"),
    ],
    visibility = [
        make_dep_path("litho-it/..."),
    ],
    deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_ANNOTATIONS_TARGET,
        LITHO_ASSERTJ_TARGET,
        LITHO_COMPILE_TESTING_TARGET,
        LITHO_HAMCREST_CORE_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_MOCKITO_V2_TARGET,
        LITHO_PROCESSOR_LIB_TARGET,
        LITHO_TESTING_ASSERTJ_TARGET,
        LITHO_TESTING_SUBCOMPONENTS_TARGET,
        LITHO_WIDGET_TARGET,
        LITHO_YOGA_TARGET,
    ],
    exported_deps = [
        LITHO_TESTING_CORE_TARGET,
    ],
)
