# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

android_library(
    name = "specmodels",
    srcs = glob(["*.java"]),
    annotation_processor_deps = [
        make_dep_path("litho-it/processor/src/main/java/com/facebook/litho/testing/processor:processor"),
    ],
    annotation_processors = [
        "com.facebook.litho.testing.processor.TestingDIComponentProcessor",
        "com.facebook.litho.specmodels.processor.testing.ComponentsTestingProcessor",
    ],
    source = "8",
    target = "8",
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/specmodels/processor/testing:testing"),
    ],
    visibility = [
        make_dep_path("litho-it/..."),
    ],
    deps = [
        COMPONENTS_JAVA_TARGET,
        COMPONENTS_ANNOTATIONS_TARGET,
        COMPONENTS_ASSERTJ_TARGET,
        COMPONENTS_COMPILE_TESTING_TARGET,
        COMPONENTS_JAVAC_TOOLS_TARGET,
        COMPONENTS_MOCKITO_TARGET,
        COMPONENTS_PROCESSOR_LIB_TARGET,
        COMPONENTS_ANDROIDSUPPORT_TARGET,
        COMPONENTS_ASSERTJ_TARGET,
        COMPONENTS_TESTING_ASSERTJ_TARGET,
        COMPONENTS_TESTING_SUBCOMPONENTS_TARGET,
        COMPONENTS_YOGA_TARGET,
    ],
)
