# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load("//:LITHO_DEFS", "LITHO_ANNOTATIONS_TARGET", "LITHO_JAVAC_TOOLS_TARGET", "LITHO_JAVAPOET_TARGET", "LITHO_JSR_TARGET", "make_dep_path")

java_annotation_processor(
    name = "processor",
    processor_class = "com.facebook.litho.specmodels.processor.ComponentsProcessor",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":processor-lib",
    ],
)

java_annotation_processor(
    name = "testing-processor",
    processor_class = "com.facebook.litho.specmodels.processor.testing.ComponentsTestingProcessor",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":processor-lib",
    ],
)

java_library(
    name = "processor-lib",
    exported_deps = [
        ":processor-lib-bare",
        LITHO_JAVAPOET_TARGET,
        LITHO_JSR_TARGET,
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/generator/testing:testing"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/processor/testing:testing"),
    ],
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/specmodels/processor:processor"),
    ],
    visibility = [
        "PUBLIC",
    ],
)

java_library(
    name = "processor-lib-bare",
    srcs = glob(["*.java"]),
    provided_deps = [
        LITHO_JAVAC_TOOLS_TARGET,
        LITHO_JAVAPOET_TARGET,
        LITHO_JSR_TARGET,
    ],
    source = "8",
    target = "8",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_ANNOTATIONS_TARGET,
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels:specmodels-bare"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/generator/testing:testing"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/internal:internal"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/model/testing:testing"),
    ],
)
