# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load("//tools/build_defs/oss:fb_native_wrapper.bzl", "fb_native")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANNOTATIONS_TARGET",
    "LITHO_JAVAPOET_TARGET",
    "LITHO_JSR_TARGET",
    "fb_java_library",
    "make_dep_path",
)

fb_native.java_annotation_processor(
    name = "processor",
    processor_class = "com.facebook.litho.specmodels.processor.ComponentsProcessor",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":processor-lib",
    ],
    supports_abi_generation_from_source = True,
)

fb_native.java_annotation_processor(
    name = "testing-processor",
    processor_class = "com.facebook.litho.specmodels.processor.testing.ComponentsTestingProcessor",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":processor-lib",
    ],
)

fb_java_library(
    name = "processor-lib",
    labels = ["supermodule:android/default/litho.core"],
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/specmodels/processor:processor"),
    ],
    visibility = [
        "PUBLIC",
    ],
    exported_deps = [
        ":processor-lib-bare",
        LITHO_JAVAPOET_TARGET,
        LITHO_JSR_TARGET,
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/generator/testing:testing"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/processor/testing:testing"),
    ],
)

fb_java_library(
    name = "processor-lib-bare",
    srcs = glob(["*.java"]),
    extra_arguments = [
        "--add-exports",
        "jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED",
        "--add-exports",
        "jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED",
    ],
    labels = ["supermodule:android/default/litho.core"],
    provided_deps = [
        LITHO_JAVAPOET_TARGET,
        LITHO_JSR_TARGET,
    ],
    source = "11",
    target = "11",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_ANNOTATIONS_TARGET,
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels:specmodels-bare"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/generator/testing:testing"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/internal:internal"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/model/testing:testing"),
    ],
)

# Copy of the target to use in intellij plugin with java 8
fb_java_library(
    name = "processor-lib-bare4idea",
    srcs = glob(
        ["*.java"],
        exclude = ["ParamNameExtractor.java"],
    ),
    labels = ["supermodule:android/default/litho.core"],
    provided_deps = [
        LITHO_JAVAPOET_TARGET,
        LITHO_JSR_TARGET,
        LITHO_ANNOTATIONS_TARGET,
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels:specmodels-bare4idea"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/internal:internal4idea"),
        make_dep_path("litho-processor/src/main/java8:files4idea"),
    ],
    source = "8",
    target = "8",
    visibility = [
        "PUBLIC",
    ],
)
