# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load("//tools/build_defs/oss:fb_native_wrapper.bzl", "fb_native")
load("//tools/build_defs/oss:litho_defs.bzl", "LITHO_ANNOTATIONS_TARGET", "LITHO_JAVAC_TOOLS_TARGET", "LITHO_JAVAPOET_TARGET", "LITHO_JSR_TARGET", "fb_java_library", "make_dep_path")

fb_native.java_annotation_processor(
    name = "processor",
    processor_class = "com.facebook.litho.specmodels.processor.ComponentsProcessor",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":processor-lib",
    ],
    supports_abi_generation_from_source = True,
)

fb_native.java_annotation_processor(
    name = "testing-processor",
    processor_class = "com.facebook.litho.specmodels.processor.testing.ComponentsTestingProcessor",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":processor-lib",
    ],
)

fb_java_library(
    name = "processor-lib",
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/specmodels/processor:processor"),
    ],
    visibility = [
        "PUBLIC",
    ],
    exported_deps = [
        ":processor-lib-bare",
        LITHO_JAVAPOET_TARGET,
        LITHO_JSR_TARGET,
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/generator/testing:testing"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/processor/testing:testing"),
    ],
)

fb_java_library(
    name = "processor-lib-bare",
    srcs = glob(["*.java"]),
    provided_deps = [
        LITHO_JAVAC_TOOLS_TARGET,
        LITHO_JAVAPOET_TARGET,
        LITHO_JSR_TARGET,
    ],
    source = "8",
    target = "8",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_ANNOTATIONS_TARGET,
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels:specmodels-bare"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/generator/testing:testing"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/internal:internal"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/model/testing:testing"),
    ],
)
