# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ASSERTJ_TARGET",
    "LITHO_HAMCREST_TARGET",
    "LITHO_INFERANNOTATIONS_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_JSR_TARGET",
    "LITHO_MOCKITO_V3_TARGET",
    "LITHO_PERF_LOGGER",
    "LITHO_ROBOLECTRIC_V4_TARGET",
    "LITHO_TESTING_ASSERTJ_TARGET",
    "LITHO_TESTING_TARGET",
    "litho_android_library",
    "make_dep_path",
)

oncall("components_for_android")

litho_android_library(
    name = "litho",
    srcs = glob(
        [
            "*.java",
            "config/*.kt",
        ],
        # It has its own module
        exclude = ["BenchmarkTestHelper.java"],
    ),
    autoglob = False,
    provided_deps = [
        LITHO_MOCKITO_V3_TARGET,
        LITHO_ROBOLECTRIC_V4_TARGET,
    ],
    pure_kotlin = False,
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/testing:testing"),
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//fbandroid/third-party/java/infer-annotations:infer-annotations",
        "//fbandroid/third-party/java/jsr-305:jsr-305",
        LITHO_ASSERTJ_TARGET,
        LITHO_HAMCREST_TARGET,
        LITHO_INFERANNOTATIONS_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JSR_TARGET,
        LITHO_PERF_LOGGER,
        LITHO_TESTING_ASSERTJ_TARGET,
        LITHO_TESTING_TARGET,
    ],
)

litho_android_library(
    name = "benchmarkhelper",
    srcs = glob(["BenchmarkTestHelper.java"]),
    autoglob = False,
    language = "JAVA",
    deps = [
        "//fbandroid/third-party/java/infer-annotations:infer-annotations",
        LITHO_JAVA_TARGET,
    ],
)
