# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load(
    "//:LITHO_DEFS",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_ASSERTJ_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_JSR_TARGET",
    "LITHO_TESTING_ASSERTJ_TARGET",
    "LITHO_HAMCREST_CORE_TARGET",
    "LITHO_TESTING_TARGET",
    "litho_android_library",
    "make_dep_path",
)

litho_android_library(
    name = "litho",
    srcs = glob(["*.java"]),
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/testing:testing"),
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_TESTING_ASSERTJ_TARGET,
        LITHO_TESTING_TARGET,
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_ASSERTJ_TARGET,
        LITHO_HAMCREST_CORE_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JSR_TARGET,
    ],
)
