# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_ASSERTJ_TARGET",
    "LITHO_HAMCREST_CORE_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_JSR_TARGET",
    "LITHO_TESTING_ASSERTJ_V3_TARGET",
    "LITHO_TESTING_ASSERTJ_V4_TARGET",
    "LITHO_TESTING_V3_TARGET",
    "LITHO_TESTING_V4_TARGET",
    "litho_android_library",
    "make_dep_path",
)

COMMON_DEPS = [
    LITHO_ANDROIDSUPPORT_TARGET,
    LITHO_ASSERTJ_TARGET,
    LITHO_HAMCREST_CORE_TARGET,
    LITHO_JAVA_TARGET,
    LITHO_JSR_TARGET,
]

litho_android_library(
    name = "litho",
    srcs = glob(
        ["*.java"],
        # It has its own module
        exclude = ["BenchmarkTestHelper.java"],
    ),
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/testing:testing"),
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_TESTING_ASSERTJ_V3_TARGET,
        LITHO_TESTING_V3_TARGET,
    ] + COMMON_DEPS,
)

litho_android_library(
    name = "litho-v4",
    srcs = glob(
        ["*.java"],
        # It has its own module
        exclude = ["BenchmarkTestHelper.java"],
    ),
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/testing:testing"),
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_TESTING_ASSERTJ_V4_TARGET,
        LITHO_TESTING_V4_TARGET,
    ] + COMMON_DEPS,
)

litho_android_library(
    name = "benchmarkhelper",
    srcs = glob(["BenchmarkTestHelper.java"]),
    deps = [
        LITHO_JAVA_TARGET,
    ],
)
