#
# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.
load("//:LITHO_DEFS", "fb_java_library")

include_defs("//LITHO_DEFS")

java_annotation_processor(
    name = "processor",
    processor_class = "com.facebook.litho.sections.specmodels.processor.SectionsComponentProcessor",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":processor-lib",
    ],
)

fb_java_library(
    name = "processor-lib",
    srcs = glob([
        "*.java",
        "**/*.java",
    ]),
    exported_deps = [
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/processor:processor-lib"),
        make_dep_path("litho-sections-processor/src/main/java/com/facebook/litho/sections/specmodels/model:model"),
    ],
    source = "8",
    target = "8",
    visibility = ["PUBLIC"],
    deps = [
        LITHO_SECTIONS_ANNOTATIONS_TARGET,
        LITHO_ANNOTATIONS_TARGET,
        LITHO_PROCESSOR_LIB_TARGET,
        make_dep_path("litho-sections-processor/src/main/java/com/facebook/litho/sections/specmodels/model:model"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels:specmodels"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/internal:internal"),
    ],
)
