# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_TEST_TARGET",
    "litho_android_library",
)

litho_android_library(
    name = "stats",
    feature = FBApp_UIFrameworks_Litho_Litho,
    labels = [],
    language = "JAVA",
    provided_deps = [LITHO_ANDROIDSUPPORT_TARGET],
    required_for_source_only_abi = True,
    tests = [
        LITHO_TEST_TARGET,
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//fbandroid/third-party/java/infer-annotations:infer-annotations",
    ],
)
