# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//tools/build_defs/oss:litho_defs.bzl", "LITHO_TEST_TARGET", "litho_android_library")

litho_android_library(
    name = "stats",
    srcs = glob([
        "*.java",
    ]),
    required_for_source_only_abi = True,
    tests = [
        LITHO_TEST_TARGET,
    ],
    visibility = ["PUBLIC"],
)
