# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//tools/build_defs/oss:litho_defs.bzl", "LITHO_ANDROIDSUPPORT_TARGET", "LITHO_ANNOTATIONS_TARGET", "LITHO_CONFIG_TARGET", "LITHO_DISPLAYLISTSTUBS_TARGET", "LITHO_INFERANNOTATIONS_TARGET", "LITHO_JSR_TARGET", "LITHO_PROGUARDANNOTATIONS_TARGET", "LITHO_RES_TARGET", "LITHO_TEST_TARGET", "LITHO_VIEWCOMPAT_TARGET", "LITHO_VISIBILITY", "LITHO_YOGA_TARGET", "litho_android_library", "make_dep_path")

litho_android_library(
    name = "stats",
    srcs = glob([
        "*.java",
    ]),
    required_for_source_only_abi = True,
    tests = [
        LITHO_TEST_TARGET,
    ],
    visibility = ["PUBLIC"],
)
