# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load("//tools/build_defs/oss:litho_defs.bzl", "LITHO_ANDROIDSUPPORT_TARGET", "LITHO_JAVAPOET_TARGET", "LITHO_JSR_TARGET", "LITHO_VISIBILITY", "fb_java_library", "make_dep_path")

fb_java_library(
    name = "testing",
    srcs = glob(["*.java"]),
    is_androidx = True,
    labels = ["supermodule:android/default/litho.core"],
    source = "8",
    target = "8",
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/specmodels:specmodels"),
    ],
    visibility = LITHO_VISIBILITY,
    deps = [
        LITHO_JAVAPOET_TARGET,
        LITHO_JSR_TARGET,
        LITHO_ANDROIDSUPPORT_TARGET,
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels:specmodels-bare"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/generator/testing:testing"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/internal:internal"),
    ],
)
