# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//tools/build_defs/oss:litho_defs.bzl", "LITHO_ASSERTJ_TARGET", "LITHO_BUILD_CONFIG_TARGET", "LITHO_JAVA_TARGET", "LITHO_JUNIT_TARGET", "LITHO_ROBOLECTRIC_V3_TARGET", "LITHO_TESTING_ASSERTJ_V3_TARGET", "LITHO_TESTING_V3_TARGET", "LITHO_WIDGET_TARGET", "components_robolectric_test", "make_dep_path")

components_robolectric_test(
    name = "testing",
    srcs = glob(["*Test.java"]),
    contacts = ["oncall+components_for_android@xmail.facebook.com"],
    source = "8",
    target = "8",
    deps = [
        LITHO_JUNIT_TARGET,
        LITHO_ROBOLECTRIC_V3_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_WIDGET_TARGET,
        LITHO_TESTING_V3_TARGET,
        LITHO_BUILD_CONFIG_TARGET,
        LITHO_TESTING_ASSERTJ_V3_TARGET,
        LITHO_ASSERTJ_TARGET,
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/testrunner:testrunner"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/util:util"),
    ],
)
