include_defs("//COMPONENTS_DEFS")

android_library(
    name = "utils",
    srcs = glob(["*.java"]),
    tests = [
        "//javatests/com/facebook/components/utils:utils",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        COMPONENTS_ROOT_TARGET,
        COMPONENTS_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        COMPONENTS_JSR_TARGET,
    ],
)
