# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

android_library(
    name = "utils",
    srcs = glob(["*.java"]),
    tests = [
        "//javatests/com/facebook/components/utils:utils",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        COMPONENTS_JAVA_TARGET,
        COMPONENTS_ANDROIDSUPPORT_TARGET,
        COMPONENTS_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        COMPONENTS_JSR_TARGET,
    ],
