# BUILD FILE SYNTAX: SKYLARK
# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//:LITHO_DEFS.bzl", "LITHO_VISIBILITY")

prebuilt_jar(
    name = "javapoet",
    binary_jar = ":javapoet.jar",
    visibility = LITHO_VISIBILITY,
)

remote_file(
    name = "javapoet.jar",
    sha1 = "00ecc5cf9c221d55481163e773b24336db149e51",
    url = "mvn:com.squareup:javapoet:jar:1.9.0",
)
