# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_ANDROIDSUPPORT_TESTING_TARGET",
    "LITHO_ANNOTATIONS_TARGET",
    "LITHO_CONTACT_NAME",
    "LITHO_ESPRESSO_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_JUNIT_TARGET",
    "LITHO_PROCESSOR_TARGET",
    "LITHO_SCREENSHOT_TARGET",
    "LITHO_WIDGET_TARGET",
    "LITHO_YOGA_TARGET",
    "fb_core_android_library",
    "instrumentation_test",
    "make_dep_path",
)

instrumentation_test(
    name = "espresso",
    srcs = glob(["*Test.java"]),
    apk_under_test = "litho",
    contacts = LITHO_CONTACT_NAME,
    is_androidx = True,
    deps = [
        ":testutil",
        LITHO_ANDROIDSUPPORT_TESTING_TARGET,
        LITHO_ESPRESSO_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JUNIT_TARGET,
        LITHO_SCREENSHOT_TARGET,
        LITHO_WIDGET_TARGET,
        LITHO_YOGA_TARGET,
        make_dep_path("litho-espresso/src/main/java/com/facebook/litho/testing/espresso:espresso"),
    ],
)

fb_core_android_library(
    name = "testutil",
    srcs = glob(["MyComponentSpec.java"]),
    is_androidx = True,
    plugins = [
        LITHO_PROCESSOR_TARGET,
    ],
    provided_deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_ANNOTATIONS_TARGET,
    ],
    deps = [
        LITHO_JAVA_TARGET,
        LITHO_WIDGET_TARGET,
        LITHO_YOGA_TARGET,
    ],
)
