load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_ANNOTATION_TARGET",
    "litho_android_library",
)

oncall("litho_components_for_android")

litho_android_library(
    name = "litho-perf-logger",
    srcs = glob([
        "**/*.kt",
    ]),
    autoglob = False,
    feature = FBApp_UIFrameworks_Litho_Litho,
    k2 = True,
    labels = [],
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//fbandroid/third-party/java/infer-annotations:infer-annotations",
        LITHO_ANDROIDSUPPORT_ANNOTATION_TARGET,
    ],
)
