load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_ANNOTATION_TARGET",
    "litho_android_library",
)

litho_android_library(
    name = "litho-perf-logger",
    srcs = glob([
        "**/*.kt",
        "**/*.java",
    ]),
    autoglob = False,
    feature = FBApp_UIFrameworks_Litho_Litho,
    labels = [],
    pure_kotlin = False,
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_ANDROIDSUPPORT_ANNOTATION_TARGET,
    ],
)
