# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.
load("//:LITHO_DEFS", "fb_android_resource", "make_dep_path")

fb_android_resource(
    name = "res",
    package = "com.facebook.litho.it",
    res = "res",
    visibility = [
        make_dep_path("litho-it/src/test/..."),
        make_dep_path("litho-it-powermock/src/test/..."),
    ],
)
