load("@fbsource//tools/build_defs:fb_native_wrapper.bzl", "fb_native")

# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "fb_android_resource",
    "make_dep_path",
)

fb_android_resource(
    name = "res",
    package = "com.facebook.litho.it",
    res = "res",
    visibility = [
        make_dep_path("litho-it/src/test/..."),
        make_dep_path("litho-it-powermock/src/test/..."),
    ],
)

fb_native.android_manifest(
    name = "manifest",
    skeleton = "AndroidManifest.xml",
    visibility = ["PUBLIC"],
)
