# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_ASSERTJ_TARGET",
    "LITHO_BUILD_CONFIG_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_JSR_TARGET",
    "LITHO_JUNIT_TARGET",
    "LITHO_MOCKITO_TARGET",
    "LITHO_ROBOLECTRIC_V3_TARGET",
    "LITHO_SOLOADER_TARGET",
    "LITHO_STATS_TARGET",
    "LITHO_TESTING_CORE_V3_TARGET",
    "LITHO_TESTING_V3_TARGET",
    "LITHO_TESTING_WHITEBOX_TARGET",
    "LITHO_TEST_RES",
    "LITHO_VIEWCOMPAT_TARGET",
    "LITHO_WIDGET_TARGET",
    "LITHO_YOGA_TARGET",
    "components_robolectric_test",
    "litho_android_library",
    "make_dep_path",
)

components_robolectric_test(
    name = "litho",
    srcs = glob([
        "*Test.java",
        "animation/*.java",
        "choreographercompat/*.java",
        "dataflow/*.java",
        "drawable/*.java",
    ]),
    contacts = ["oncall+components_for_android@xmail.facebook.com"],
    is_androidx = True,
    provided_deps = [
        LITHO_ROBOLECTRIC_V3_TARGET,
    ],
    source = "8",
    target = "8",
    deps = [
        ":testutil",
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_ASSERTJ_TARGET,
        LITHO_BUILD_CONFIG_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JUNIT_TARGET,
        LITHO_MOCKITO_TARGET,
        LITHO_SOLOADER_TARGET,
        LITHO_STATS_TARGET,
        LITHO_TESTING_V3_TARGET,
        LITHO_TESTING_WHITEBOX_TARGET,
        LITHO_TEST_RES,
        LITHO_VIEWCOMPAT_TARGET,
        LITHO_WIDGET_TARGET,
        LITHO_YOGA_TARGET,
        make_dep_path("litho-core/src/main/java/com/facebook/litho/utils:utils"),
        make_dep_path("litho-it/src/main/java/com/facebook/litho:litho-testing"),
        make_dep_path("litho-it/src/main/java/com/facebook/litho/components:components"),
        make_dep_path("litho-it/src/main/java/com/facebook/litho/testing/drawable:drawable"),
        make_dep_path("litho-it/src/main/java/com/facebook/litho/testing/error:error"),
        make_dep_path("litho-it/src/main/java/com/facebook/litho/widget:widget"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/internal:internal"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho:litho"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/assertj:assertj"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/eventhandler:eventhandler"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/logging:logging"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/shadows:shadows"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/testrunner:testrunner"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/util:util"),
    ],
)

litho_android_library(
    name = "testutil",
    srcs = [
        "StateUpdateTestComponent.java",
        "TouchExpansionTestInternalNode.java",
    ],
    source = "8",
    target = "8",
    visibility = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/..."),
    ],
    deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JSR_TARGET,
        LITHO_TESTING_CORE_V3_TARGET,
        LITHO_YOGA_TARGET,
    ],
)
