include_defs("//COMPONENTS_DEFS")

java_library(
    name = "specmodels",
    srcs = glob(
        ["**/*.java"],
        excludes = glob(["processor/*.java"]),
    ),
    exported_deps = [
        make_dep_path("src/main/java/com/facebook/components/annotations:annotations"),
    ],
    tests = [
        "//javatests/com/facebook/components/specmodels:specmodels",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        make_dep_path("src/main/java/com/facebook/components/javapoet:javapoet"),
        COMPONENTS_FBCORE_TARGET,
        COMPONENTS_JSR_TARGET,
    ],
)
