# Copyright (c) Facebook, Inc. and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_DYNAMICANIMATION_TARGET",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_INFERANNOTATIONS_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_KOTLIN_STDLIB_TARGET",
    "LITHO_YOGA_TARGET",
    "litho_android_library",
    "make_dep_path",
)

litho_android_library(
    name = "litho-kotlin",
    srcs = glob(["**/*.kt"]),
    autoglob = False,
    is_androidx = True,
    labels = ["supermodule:android/default/litho.core"],
    language = "KOTLIN",
    provided_deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
    ],
    required_for_source_only_abi = True,
    tests = [make_dep_path("litho-core-kotlin/src/test/kotlin/com/facebook/litho:litho")],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_YOGA_TARGET,
        LITHO_KOTLIN_STDLIB_TARGET,
        LITHO_ANDROIDSUPPORT_DYNAMICANIMATION_TARGET,
        LITHO_INFERANNOTATIONS_TARGET,
    ],
    exported_deps = [
        LITHO_JAVA_TARGET,
    ],
)
