android_library(
    name = "testrunner",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//third-party/java/robolectric3/robolectric:robolectric",
    ],
)
