include_defs("//COMPONENTS_DEFS")

android_library(
    name = "testrunner",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        COMPONENTS_ROBOLECTRIC_TARGET,
    ],
)
