# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

# This target is only used in open source and will break the monobuild
# because we cannot define `soname` multiple times.
if COMPONENTS_IS_OSS_BUILD:
  prebuilt_cxx_library(
      name = "ndklog",
      exported_platform_linker_flags = [
          (
              "^android.*",
              ["-llog"],
          ),
      ],
      header_only = True,
      visibility = COMPONENTS_VISIBILITY,
  )

  fb_xplat_cxx_library(
      name = "yoga",
      srcs = glob(["yoga/*.cpp"]),
      deps = [
        ":ndklog",
      ],
      compiler_flags = [
          "-fno-omit-frame-pointer",
          "-fexceptions",
          "-Wall",
          "-Werror",
          "-std=c++1y",
          "-O3",
      ],
      exported_headers = glob(["yoga/*.h"]),
      force_static = True,
      header_namespace = "",
      visibility = COMPONENTS_VISIBILITY,
  )
