# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

java_library(
    name = "testing",
    srcs = glob(["*.java"]),
    provided_deps = [
        COMPONENTS_JSR_TARGET,
        COMPONENTS_JAVAPOET_TARGET,
        COMPONENTS_JAVAC_TOOLS_TARGET,
    ],
    source = "8",
    target = "8",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels:specmodels-bare"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/processor:processor-lib-bare"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/generator/testing:testing"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/model/testing:testing"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/internal:internal"),
        COMPONENTS_ANNOTATIONS_TARGET,
    ],
)
