# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load("//:LITHO_DEFS.bzl", "LITHO_ANNOTATIONS_TARGET", "LITHO_JAVAC_TOOLS_TARGET", "LITHO_JAVAPOET_TARGET", "LITHO_JSR_TARGET", "make_dep_path", "fb_java_library")

fb_java_library(
    name = "testing",
    srcs = glob(["*.java"]),
    provided_deps = [
        LITHO_JAVAC_TOOLS_TARGET,
        LITHO_JAVAPOET_TARGET,
        LITHO_JSR_TARGET,
    ],
    source = "8",
    target = "8",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_ANNOTATIONS_TARGET,
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels:specmodels-bare"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/generator/testing:testing"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/internal:internal"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/model/testing:testing"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/processor:processor-lib-bare"),
    ],
)
