# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_FRESCO_TARGETS",
    "LITHO_OSS_TARGET",
    "LITHO_PROCESSOR_TARGET",
    "LITHO_UTILS_TARGET",
    "litho_android_library",
)

litho_android_library(
    name = "fresco",
    srcs = glob(
        ["*.java"],
        exclude = ["common/**/*"],
    ),
    labels = ["supermodule:android/default/litho.core"],
    plugins = [
        LITHO_PROCESSOR_TARGET,
    ],
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
    deps =
        LITHO_FRESCO_TARGETS + [
            LITHO_OSS_TARGET,
            LITHO_UTILS_TARGET,
        ],
)
