# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_FRESCO_EXPORTED_TARGETS",
    "LITHO_FRESCO_TARGETS",
    "LITHO_OSS_TARGET",
    "LITHO_PROCESSOR_TARGET",
    "LITHO_UTILS_TARGET",
    "litho_android_library",
)

litho_android_library(
    name = "fresco",
    feature = FBApp_UIFrameworks_Litho_Litho,
    labels = [],
    language = "JAVA",
    plugins = [
        LITHO_PROCESSOR_TARGET,
    ],
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
    deps =
        LITHO_FRESCO_TARGETS + [
            LITHO_OSS_TARGET,
            LITHO_UTILS_TARGET,
        ],
    exported_deps = LITHO_FRESCO_EXPORTED_TARGETS,
)
