# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load("//:LITHO_DEFS", "LITHO_FRESCO_TARGETS", "LITHO_OSS_TARGET", "LITHO_PROCESSOR_TARGET", "LITHO_UTILS_TARGET", "litho_android_library")

litho_android_library(
    name = "fresco",
    srcs = glob(
        ["*.java"],
        exclude = ["common/**/*"],
    ),
    plugins = [
        LITHO_PROCESSOR_TARGET,
    ],
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
    deps =
        LITHO_FRESCO_TARGETS + [
            LITHO_OSS_TARGET,
            LITHO_UTILS_TARGET,
        ],
)
