# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load("//:LITHO_DEFS", "LITHO_ASSERTJ_TARGET", "LITHO_JAVA_TARGET", "LITHO_JSR_TARGET", "LITHO_YOGA_TARGET", "litho_android_library")

litho_android_library(
    name = "subcomponents",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_JAVA_TARGET,
        LITHO_ASSERTJ_TARGET,
        LITHO_YOGA_TARGET,
        LITHO_JSR_TARGET,
    ],
)
