# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_ASSERTJ_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_JSR_TARGET",
    "LITHO_YOGA_TARGET",
    "litho_android_library",
)

litho_android_library(
    name = "subcomponents",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_ASSERTJ_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JSR_TARGET,
        LITHO_YOGA_TARGET,
    ],
)
