# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

include_defs("//LITHO_DEFS.bzl")

components_robolectric_test(
    name = "widget",
    srcs = glob([
        "*Test.java",
        "Test*.java",
    ]),
    contacts = ["oncall+components_for_android@xmail.facebook.com"],
    provided_deps = [
        LITHO_ROBOLECTRIC_TARGET,
    ],
    source = "8",
    target = "8",
    deps = [
        LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_ASSERTJ_TARGET,
        LITHO_BUILD_CONFIG_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JUNIT_TARGET,
        LITHO_MOCKITO_TARGET,
        LITHO_POWERMOCK_REFLECT_TARGET,
        LITHO_SOLOADER_TARGET,
        LITHO_TESTING_TARGET,
        LITHO_VIEWCOMPAT_TARGET,
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/assertj:assertj"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/eventhandler:eventhandler"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/testrunner:testrunner"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/util:util"),
        make_dep_path("litho-widget/src/main/java/com/facebook/litho/widget:widget"),
    ],
)
