include_defs("//COMPONENTS_DEFS")

android_library(
    name = "annotations",
    srcs = glob(["*.java"]),
    proguard_config = "proguard_annotations.pro",
    visibility = [
        COMPONENTS_VISIBILITY,
    ],
    deps = [
    ],
)
