# Copyright (c) Facebook, Inc. and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_FRESCO_INTERFACES_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_KOTLIN_TARGET",
    "LITHO_LITHO_FRESCO_TARGET",
    "litho_android_library",
)

litho_android_library(
    name = "fresco-kotlin",
    srcs = glob(["*.kt"]),
    language = "KOTLIN",
    provided_deps =
        LITHO_FRESCO_INTERFACES_TARGET + [
            LITHO_JAVA_TARGET,
        ],
    required_for_source_only_abi = True,
    visibility = ["PUBLIC"],
    deps = [
        LITHO_KOTLIN_TARGET,
        LITHO_LITHO_FRESCO_TARGET,
    ],
)
