include_defs("//COMPONENTS_DEFS")

litho_android_library(
    name = "assertj",
    srcs = glob(["*.java"]),
    exported_deps = [
        COMPONENTS_ASSERTJ_TARGET,
    ],
    visibility = [
        "//javatests/...",
        make_dep_path("litho-it/src/test/..."),
    ],
    deps = [
        COMPONENTS_ANDROIDSUPPORT_TARGET,
        COMPONENTS_JAVA_TARGET,
        COMPONENTS_POWERMOCK_REFLECT_TARGET,
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/viewtree:viewtree"),
        COMPONENTS_TESTING_TARGET,
    ],
)
