load("//tools/build_defs/oss:litho_defs.bzl", "LITHO_ANDROIDSUPPORT_TARGET", "LITHO_ASSERTJ_TARGET", "LITHO_HAMCREST_CORE_TARGET", "LITHO_JAVA_TARGET", "LITHO_JSR_TARGET", "LITHO_TESTING_HELPER_V3_TARGET", "LITHO_TESTING_SUBCOMPONENTS_TARGET", "LITHO_TESTING_WHITEBOX_TARGET", "litho_android_library", "make_dep_path")

litho_android_library(
    name = "assertj",
    srcs = glob(["*.java"]),
    is_androidx = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JSR_TARGET,
        LITHO_TESTING_WHITEBOX_TARGET,
        LITHO_TESTING_HELPER_V3_TARGET,
        LITHO_TESTING_SUBCOMPONENTS_TARGET,
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/viewtree:viewtree"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/state:state"),
        LITHO_HAMCREST_CORE_TARGET,
    ],
    exported_deps = [
        LITHO_ASSERTJ_TARGET,
    ],
)
