load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_TESTING_CORE_TARGET",
    "LITHO_ASSERTJ_TARGET",
    "LITHO_HAMCREST_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_JSR_TARGET",
    "LITHO_KOTLIN_STDLIB_TARGET",
    "LITHO_TESTING_HELPER_TARGET",
    "LITHO_TESTING_SUBCOMPONENTS_TARGET",
    "LITHO_TESTING_TARGET",
    "LITHO_TESTING_VIEWTREE_TARGET",
    "LITHO_TESTING_WHITEBOX_TARGET",
    "litho_android_library",
    "make_dep_path",
)

COMMON_DEPS = [
    LITHO_JAVA_TARGET,
    LITHO_JSR_TARGET,
    LITHO_TESTING_WHITEBOX_TARGET,
    LITHO_TESTING_SUBCOMPONENTS_TARGET,
    LITHO_HAMCREST_TARGET,
]

litho_android_library(
    name = "assertj",
    pure_kotlin = False,
    visibility = [
        "PUBLIC",
    ],
    deps = COMMON_DEPS + [
        "//fbandroid/third-party/java/infer-annotations:infer-annotations",
        "//third-party/java/com/google/guava/guava:guava",
        LITHO_ANDROIDSUPPORT_TESTING_CORE_TARGET,
        LITHO_KOTLIN_STDLIB_TARGET,
        LITHO_TESTING_HELPER_TARGET,
        LITHO_TESTING_TARGET,
        LITHO_TESTING_VIEWTREE_TARGET,
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/componentsfinder:componentsfinder"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/state:state"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/viewtree:viewtree"),
    ],
    exported_deps = [
        LITHO_ASSERTJ_TARGET,
    ],
)
