# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_ASSERTJ_TARGET",
    "LITHO_COMPILE_TESTING_TARGET",
    "LITHO_GUAVA_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_JUNIT_TARGET",
    "LITHO_PROCESSOR_LIB_TARGET",
    "LITHO_ROBOLECTRIC_V4_TARGET",
    "LITHO_TESTING_ASSERTJ_TARGET",
    "LITHO_TESTING_CORE_TARGET",
    "LITHO_TESTING_TARGET",
    "LITHO_TRUTH_TARGET",
    "fb_java_test",
    "make_dep_path",
)

fb_java_test(
    name = "integration",
    srcs = glob(["*Test.java"]),
    contacts = ["oncall+litho_components_for_android@xmail.facebook.com"],
    source = "1.8",
    target = "1.8",
    deps = [
        "//fbandroid/third-party/java/robolectric/android-all:android-all-10",
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_ASSERTJ_TARGET,
        LITHO_COMPILE_TESTING_TARGET,
        LITHO_GUAVA_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JUNIT_TARGET,
        LITHO_PROCESSOR_LIB_TARGET,
        LITHO_ROBOLECTRIC_V4_TARGET,
        LITHO_TESTING_ASSERTJ_TARGET,
        LITHO_TESTING_CORE_TARGET,
        LITHO_TESTING_TARGET,
        LITHO_TRUTH_TARGET,
        make_dep_path("litho-it/src/test/resources:resources"),
    ],
)
