# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_JAVAPOET_TARGET",
    "LITHO_JSR_TARGET",
    "fb_java_library",
    "make_dep_path",
)

fb_java_library(
    name = "internal",
    srcs = glob(["*.java"]),
    java_version = "8",
    labels = ["supermodule:android/default/litho.core"],
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/specmodels:specmodels"),
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_JAVAPOET_TARGET,
        LITHO_JSR_TARGET,
    ],
)
