load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")

# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_JAVAPOET_TARGET",
    "LITHO_JSR_TARGET",
    "fb_java_library",
    "make_dep_path",
)

fb_java_library(
    name = "internal",
    srcs = glob(["*.java"]),
    feature = FBApp_UIFrameworks_Litho_Litho,
    java_version = "8",
    labels = [],
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/specmodels:specmodels"),
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_JAVAPOET_TARGET,
        LITHO_JSR_TARGET,
    ],
)

# Copy of the target to use in intellij plugin with provided deps
fb_java_library(
    name = "internal4idea",
    srcs = glob(["*.java"]),
    feature = FBApp_UIFrameworks_Litho_Litho,
    labels = [],
    provided_deps = [
        LITHO_JAVAPOET_TARGET,
        LITHO_JSR_TARGET,
    ],
    source = "8",
    target = "8",
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/specmodels:specmodels"),
    ],
    visibility = [
        "PUBLIC",
    ],
)
