load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_ANDROIDSUPPORT_TESTING_CORE_TARGET",
    "LITHO_ASSERTJ_TARGET",
    "LITHO_INFERANNOTATIONS_TARGET",
    "LITHO_JUNIT_TARGET",
    "LITHO_RENDERCORE_TARGET",
    "LITHO_ROBOLECTRIC_V4_TARGET",
    "litho_android_library",
)

litho_android_library(
    name = "litho-rendercore-testing",
    srcs = glob(["src/main/java/**/*.java"]),
    autoglob = False,
    source = "8",
    target = "8",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_ANDROIDSUPPORT_TESTING_CORE_TARGET,
        LITHO_ASSERTJ_TARGET,
        LITHO_INFERANNOTATIONS_TARGET,
        LITHO_JUNIT_TARGET,
        LITHO_RENDERCORE_TARGET,
        LITHO_ROBOLECTRIC_V4_TARGET,
    ],
)
