# BUILD FILE SYNTAX: SKYLARK
# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//:LITHO_DEFS.bzl", "LITHO_VISIBILITY")

prebuilt_jar(
    name = "screenshot",
    binary_jar = ":screenshot.jar",
    visibility = LITHO_VISIBILITY,
)

remote_file(
    name = "screenshot.jar",
    sha1 = "3157c3868899f5ca982c1c084692a553d47f60fa",
    url = "mvn:com.facebook.testing.screenshot:core:jar:0.5.0",
)
