# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load("//:LITHO_DEFS", "LITHO_VISIBILITY")

prebuilt_jar(
    name = "screenshot",
    binary_jar = ":screenshot.jar",
    visibility = LITHO_VISIBILITY,
)

remote_file(
    name = "screenshot.jar",
    sha1 = "3157c3868899f5ca982c1c084692a553d47f60fa",
    url = "mvn:com.facebook.testing.screenshot:core:jar:0.5.0",
)
