# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//tools/build_defs/oss:fb_native_wrapper.bzl", "fb_native")
load("//tools/build_defs/oss:litho_defs.bzl", "LITHO_VISIBILITY")

fb_native.prebuilt_jar(
    name = "screenshot",
    binary_jar = ":screenshot.jar",
    visibility = LITHO_VISIBILITY,
)

fb_native.remote_file(
    name = "screenshot.jar",
    sha1 = "3157c3868899f5ca982c1c084692a553d47f60fa",
    url = "mvn:com.facebook.testing.screenshot:core:jar:0.5.0",
)
