include_defs("//COMPONENTS_DEFS")

java_library(
    name = "annotations",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        COMPONENTS_ANDROIDSUPPORT_TARGET,
    ],
)
