# Copyright (c) Facebook, Inc. and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load(
    "@fbsource//tools/build_defs/android:primary_dex_patterns.bzl",
    "NORMAL_PRIMARY_DEX_PATTERNS",
)
load("//tools/build_defs/oss:fb_native_wrapper.bzl", "fb_native")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "CARIBOU_PREVIEW",
    "DEBUG_KEYSTORE",
    "LITHO_ANDROIDSUPPORT_APPCOMPAT_TARGET",
    "LITHO_SAMPLE",
    "fb_android_resource",
)

fb_native.android_binary(
    name = "sample",
    aapt_mode = "aapt2",
    allow_r_dot_java_in_secondary_dex = True,
    includes_vector_drawables = True,
    keystore = DEBUG_KEYSTORE,
    manifest = ":manifest",
    primary_dex_patterns = NORMAL_PRIMARY_DEX_PATTERNS,
    use_split_dex = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_SAMPLE,
        CARIBOU_PREVIEW,
    ],
)

fb_native.android_manifest(
    name = "manifest",
    skeleton = "src/main/AndroidManifest.xml",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        CARIBOU_PREVIEW,
    ],
)

fb_android_resource(
    name = "res",
    package = "com.facebook.samples.litho",
    res = "src/main/res",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_ANDROIDSUPPORT_APPCOMPAT_TARGET,
    ],
)

fb_native.keystore(
    name = "debug_keystore",
    properties = "debug.keystore.properties",
    store = "debug.keystore",
)

fb_native.android_library(
    name = "activity",
)
