android_binary(
    name = "sample",
    keystore = ":debug_keystore",
    manifest = "src/main/AndroidManifest.xml",
    deps = [
        "//libraries/components/sample/src/main/java/com/facebook/samples/components:components",
    ],
)

android_resource(
    name = "res",
    package = "com.facebook.samples.components",
    res = "src/main/res",
    visibility = [
        "PUBLIC",
    ],
)

keystore(
    name = "debug_keystore",
    properties = "debug.keystore.properties",
    store = "debug.keystore",
)

project_config(
    src_target = ":sample",
)
