# Copyright (c) 2019-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_KOTLIN_TARGET",
    "LITHO_PROCESSOR_TARGET",
    "LITHO_WIDGET_TARGET",
    "LITHO_YOGA_TARGET",
    "litho_android_test_library",
    "make_dep_path",
)

litho_android_test_library(
    name = "widget",
    srcs = glob([
        "**/*.java",
        "*.kt",
    ]),
    autoglob = False,
    is_androidx = True,
    language = "KOTLIN",
    plugins = [
        LITHO_PROCESSOR_TARGET,
    ],
    pure_kotlin = False,
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_KOTLIN_TARGET,
        LITHO_WIDGET_TARGET,
        LITHO_YOGA_TARGET,
        make_dep_path("litho-it/src/main/java/com/facebook/litho:litho-testing"),
    ],
)
