# Copyright (c) 2019-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//tools/build_defs/oss:litho_defs.bzl", "LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET", "LITHO_ANDROIDSUPPORT_TARGET", "LITHO_JAVA_TARGET", "LITHO_WIDGET_TARGET", "litho_android_library", "make_dep_path")

litho_android_library(
    name = "widget",
    srcs = glob(["*.java"]),
    is_androidx = True,
    visibility = [
        make_dep_path("litho-it/src/test/..."),
    ],
    deps = [
        LITHO_JAVA_TARGET,
        LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_WIDGET_TARGET,
    ],
)
