load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_ANNOTATION_TARGET",
    "LITHO_RENDERCORE_TARGET",
    "fb_android_library",
)

fb_android_library(
    name = "mountable-canvas",
    srcs = glob(
        ["src/main/java/**/*.kt"],
    ),
    autoglob = False,
    feature = FBApp_UIFrameworks_Litho,
    labels = [],
    provided_deps = [
        LITHO_ANDROIDSUPPORT_ANNOTATION_TARGET,
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_RENDERCORE_TARGET,
        "//fbandroid/third-party/android/androidx:collection",
        "//third-party/java/androidx/core/core-ktx:core-ktx",
    ],
    exported_deps = [
        "//fbandroid/libraries/rendercore/rendercore-mountables/mountable-utils:mountable-utils",
    ],
)
