load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")

# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_JAVA_TARGET",
    "LITHO_TESTING_UTIL_VISIBILITY",
    "fb_core_android_library",
)

fb_core_android_library(
    name = "inlinelayoutspec",
    srcs = glob(["*.java"]),
    feature = FBApp_UIFrameworks_Litho_Litho,
    labels = [],
    visibility = LITHO_TESTING_UTIL_VISIBILITY,
    deps = [
        LITHO_JAVA_TARGET,
    ],
)
