include_defs("//COMPONENTS_DEFS")

android_library(
    name = "widget",
    srcs = glob(["*.java"]),
    plugins = [
        COMPONENTS_PROCESSOR_TARGET,
    ],
    tests = [
        "//instrumentation_tests/com/facebook/components/widget:widget",
        "//javatests/com/facebook/components/widget:widget",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps =
        COMPONENTS_TEXTLAYOUTBUILDER_UTILS_TARGET + [
            COMPONENTS_WIDGET_ACCESSIBILITIES_TARGET,
            COMPONENTS_UTILS_TARGET,
            COMPONENTS_RES_TARGET,
            COMPONENTS_TEXTLAYOUTBUILDER_TARGET,
            COMPONENTS_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
            COMPONENTS_ANDROIDSUPPORT_TARGET,
            COMPONENTS_JSR_TARGET,
            COMPONENTS_OSS_TARGET,
            COMPONENTS_INFERANNOTATIONS_TARGET,
        ],
)
