android_library(
    name = "widget",
    srcs = glob(["*.java"]),
    tests = [
        "//instrumentation_tests/com/facebook/components/widget:widget",
        "//javatests/com/facebook/components/widget:widget",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//java/com/facebook/components:components_oss",
        "//libraries/components:res",
        "//libraries/components/src/main/java/com/facebook/components/utils:utils",
        "//libraries/components/src/main/java/com/facebook/components/widget/accessibility:accessibility",
        "//libraries/textlayoutbuilder/library/src/main/java/com/facebook/fbui/textlayoutbuilder:textlayoutbuilder",
        "//libraries/textlayoutbuilder/library/src/main/java/com/facebook/fbui/textlayoutbuilder/util:util",
        "//third-party/android/support/v4:lib-support-v4",
        "//third-party/android/support/v7/recyclerview:recyclerview",
        "//third-party/java/infer-annotations:infer-annotations",
        "//third-party/java/jsr-305:jsr-305",
    ],
)
