# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

prebuilt_jar(
    name = "hamcrest",
    binary_jar = ":hamcrest-core.jar",
    visibility = [
        COMPONENTS_VISIBILITY,
    ],
)

remote_file(
    name = "hamcrest-core.jar",
    sha1 = "42a25dc3219429f0e5d060061f71acb49bf010a0",
    url = "mvn:org.hamcrest:hamcrest-core:jar:1.3",
)
