# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load("//:COMPONENTS_DEFS", "COMPONENTS_VISIBILITY")

java_library(
    name = "hamcrest",
    exported_deps = [
        ":hamcrest-core",
        ":hamcrest-library",
    ],
    visibility = COMPONENTS_VISIBILITY,
)

prebuilt_jar(
    name = "hamcrest-core",
    binary_jar = ":hamcrest-core.jar",
)

remote_file(
    name = "hamcrest-core.jar",
    sha1 = "42a25dc3219429f0e5d060061f71acb49bf010a0",
    url = "mvn:org.hamcrest:hamcrest-core:jar:1.3",
)

prebuilt_jar(
    name = "hamcrest-library",
    binary_jar = ":hamcrest-library.jar",
)

remote_file(
    name = "hamcrest-library.jar",
    sha1 = "4785a3c21320980282f9f33d0d1264a69040538f",
    url = "mvn:org.hamcrest:hamcrest-library:jar:1.3",
)
