# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load("//:LITHO_DEFS", "LITHO_BUILD_CONFIG_TARGET", "LITHO_YOGA_TARGET", "litho_android_library", "make_dep_path")

litho_android_library(
    name = "config",
    srcs = glob(["*.java"]),
    provided_deps = [
        LITHO_BUILD_CONFIG_TARGET,
        LITHO_YOGA_TARGET,
        make_dep_path("litho-core/src/main/java/com/facebook/litho/internal:internal"),
    ],
    visibility = ["PUBLIC"],
)
