# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_BUILD_CONFIG_TARGET",
    "LITHO_PERFBOOST_TARGET",
    "LITHO_YOGA_TARGET",
    "litho_android_library",
)

litho_android_library(
    name = "config",
    srcs = glob([
        "*.java",
        "*.kt",
    ]),
    autoglob = False,
    feature = FBApp_UIFrameworks_Litho_Litho,
    labels = [],
    provided_deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_PERFBOOST_TARGET,
        LITHO_BUILD_CONFIG_TARGET,
        LITHO_YOGA_TARGET,
    ],
    pure_kotlin = False,
    visibility = ["PUBLIC"],
    deps = [
        "//fbandroid/third-party/java/infer-annotations:infer-annotations",
    ],
)
