# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

litho_android_library(
    name = "testing",
    srcs = glob(["*.java"]),
    provided_deps = [
        COMPONENTS_ROBOLECTRIC_TARGET,
    ],
    visibility = [
        "PUBLIC",
    ],
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/testing/viewtree:viewtree"),
    ],
    deps = [
        COMPONENTS_ANDROIDSUPPORT_TARGET,
        COMPONENTS_JAVA_TARGET,
        COMPONENTS_RES_TARGET,
        COMPONENTS_JSR_TARGET,
        COMPONENTS_FRESCO_TARGET,
        COMPONENTS_POWERMOCK_REFLECT_TARGET,
        COMPONENTS_YOGA_TARGET,
        COMPONENTS_WIDGET_TARGET,
        COMPONENTS_ASSERTJ_TARGET,
    ],
)
