# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")
load("//tools/build_defs/oss:litho_defs.bzl", "fb_java_library")

fb_java_library(
    name = "annotations",
    srcs = glob(["*.java"]),
    feature = FBApp_UIFrameworks_Litho_Litho,
    labels = [],
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
    ],
)
