# BUILD FILE SYNTAX: SKYLARK
# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load(
    "//:LITHO_DEFS.bzl",
    "fb_core_android_library",
    "make_dep_path",
    "LITHO_JSR_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_WIDGET_TARGET",
    "LITHO_SECTIONS_TARGET",
    "LITHO_SECTIONS_WIDGET_TARGET",
    "LITHO_SECTIONS_ANNOTATIONS_TARGET",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_SECTIONS_COMMON_TARGET",
    "LITHO_SECTIONS_PROCESSOR_TARGET",
    "LITHO_PROCESSOR_TARGET",
)

fb_core_android_library(
    name = "treeprops",
    srcs = glob(["*.java"]),
    plugins = [
        LITHO_PROCESSOR_TARGET,
        LITHO_SECTIONS_PROCESSOR_TARGET,
    ],
    visibility = [
        make_dep_path("litho-instrumentation-tests/src/androidTest/..."),
    ],
    deps = [
        LITHO_JSR_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_WIDGET_TARGET,
        LITHO_SECTIONS_TARGET,
        LITHO_SECTIONS_WIDGET_TARGET,
        LITHO_SECTIONS_ANNOTATIONS_TARGET,
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_SECTIONS_COMMON_TARGET,
    ],
)
