# Copyright 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE-examples file in the root directory of this source tree.

include_defs("//LITHO_DEFS")

android_library(
    name = "litho",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps =
        LITHO_SAMPLE_APP_EXTRAS +
        LITHO_FRESCO_PIPELINE_TARGET +
        LITHO_FRESCO_CONTROLLER_TARGET +
        LITHO_FRESCO_INTERFACES_TARGET +
        LITHO_FRESCO_TARGETS + [
            LITHO_ROOT_TARGET,
            LITHO_LITHO_FRESCO_TARGET,
            LITHO_RES_TARGET,
            LITHO_UTILS_TARGET,
            LITHO_WIDGET_TARGET,
            LITHO_SAMPLE_RES,
            LITHO_SOLOADER_TARGET,
            LITHO_ANDROIDSUPPORT_TARGET,
            LITHO_ANDROIDSUPPORT_APPCOMPAT_TARGET,
            LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
            LITHO_JSR_TARGET,
            LITHO_YOGA_TARGET,
        ],
)
