include_defs("//COMPONENTS_DEFS")

components_robolectric_test(
    name = "viewtree",
    srcs = glob(["*Test.java"]),
    contacts = ["oncall+components_for_android@xmail.facebook.com"],
    deps = [
        COMPONENTS_BUILD_CONFIG_TARGET,
        COMPONENTS_GUAVA_TARGET,
        COMPONENTS_JAVA_TARGET,
        COMPONENTS_JSR_TARGET,
        COMPONENTS_JUNIT_TARGET,
        COMPONENTS_ROBOLECTRIC_TARGET,
        make_dep_path("litho-widget/src/main/java/com/facebook/litho/widget:widget"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/testrunner:testrunner"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/viewtree:viewtree"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/shadows:shadows"),
        COMPONENTS_TESTING_TARGET,
        COMPONENTS_TEST_RES,
        make_dep_path("litho-it/src/test/java/com/facebook/litho:testutil"),
    ],
)
