load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_TESTING_TARGET",
    "LITHO_BUILD_CONFIG_TARGET",
    "LITHO_ESPRESSO_TARGET",
    "LITHO_JUNIT_TARGET",
    "LITHO_TESTING_ESPRESSO_TARGET",
    "fb_instrumentation_test",
    "make_dep_path",
)

fb_instrumentation_test(
    name = "tti",
    srcs = glob(["*Test.java"]),
    is_androidx = True,
    manifest = "AndroidManifest.xml",
    deps = [
        LITHO_ANDROIDSUPPORT_TESTING_TARGET,
        LITHO_BUILD_CONFIG_TARGET,
        LITHO_ESPRESSO_TARGET,
        LITHO_JUNIT_TARGET,
        LITHO_TESTING_ESPRESSO_TARGET,
        make_dep_path("litho-instrumentation-tests/src/main/java/com/facebook/litho/sections/tti:tti"),
    ],
)
