# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

android_prebuilt_aar(
    name = "textlayoutbuilder",
    aar = ":textlayoutbuilder-aar",
    visibility = COMPONENTS_VISIBILITY,
)

remote_file(
    name = "textlayoutbuilder-aar",
    url = "mvn:com.facebook.fbui.textlayoutbuilder:textlayoutbuilder:aar:1.1.0",
    sha1 = "297030029bbe61bd2504323e850b5fb33e0a5cf3",
)
