# BUILD FILE SYNTAX: SKYLARK
# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//:LITHO_DEFS.bzl", "LITHO_VISIBILITY")

android_prebuilt_aar(
    name = "textlayoutbuilder",
    aar = ":textlayoutbuilder-aar",
    visibility = LITHO_VISIBILITY,
)

remote_file(
    name = "textlayoutbuilder-aar",
    sha1 = "eedbbe94924232e1fe2ee602f04241b2769a7d96",
    url = "mvn:com.facebook.fbui.textlayoutbuilder:textlayoutbuilder:aar:1.3.0",
)
