# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//:LITHO_DEFS.bzl", "LITHO_VISIBILITY", "fb_java_library")

fb_java_library(
    name = "textlayoutbuilder",
    visibility = LITHO_VISIBILITY,
    exported_deps = [
        ":textlayoutbuilder-prebuilt-aar",
        ":textlayoutbuilder-prebuilt-staticlayout-proxy-jar",
    ],
)

android_prebuilt_aar(
    name = "textlayoutbuilder-prebuilt-aar",
    aar = ":textlayoutbuilder-aar",
)

remote_file(
    name = "textlayoutbuilder-aar",
    sha1 = "eedbbe94924232e1fe2ee602f04241b2769a7d96",
    url = "mvn:com.facebook.fbui.textlayoutbuilder:textlayoutbuilder:aar:1.3.0",
)

prebuilt_jar(
    name = "textlayoutbuilder-prebuilt-staticlayout-proxy-jar",
    binary_jar = ":textlayoutbuilder-staticlayout-proxy.jar",
)

remote_file(
    name = "textlayoutbuilder-staticlayout-proxy.jar",
    sha1 = "12b83e0095b17b6fda8641f7caff56b0cf8e7d79",
    url = "mvn:com.facebook.fbui.textlayoutbuilder:staticlayout-proxy:jar:1.3.0",
)
