# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

include_defs("//LITHO_DEFS.bzl")

fb_core_android_library(
    name = "rules",
    srcs = glob(["*.java"]),
    exported_deps = [
        LITHO_ROOT + "litho-espresso/src/main/java/com/facebook/litho/testing/espresso:espresso",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_ANDROIDSUPPORT_APPCOMPAT_TARGET,
        LITHO_ANDROIDSUPPORT_TESTING_TARGET,
        LITHO_ESPRESSO_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JUNIT_TARGET,
    ],
)
