# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//LITHO_DEFS")

android_library(
    name = "rules",
    srcs = glob(["*.java"]),
    exported_deps = [
        LITHO_ROOT + "litho-espresso/src/main/java/com/facebook/litho/testing/espresso:espresso",
    ],
    tests = [
        "//instrumentation_tests/com/facebook/testing/instrumentation:instrumentation",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_ANDROIDSUPPORT_APPCOMPAT_TARGET,
        LITHO_ANDROIDSUPPORT_TESTING_TARGET,
        LITHO_ESPRESSO_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JUNIT_TARGET,
    ],
)
