# Copyright (c) Facebook, Inc. and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@fbsource//xplat/pfh/FBApp/UIFrameworks/Litho/Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_KOTLIN_TARGET",
    "LITHO_UTILS_TARGET",
    "LITHO_WIDGET_RES_TARGET",
    "LITHO_WIDGET_TARGET",
    "LITHO_YOGA_FACTORY_TARGET",
    "litho_android_library",
)

litho_android_library(
    name = "widget",
    feature = FBApp_UIFrameworks_Litho_Litho,
    is_androidx = True,
    labels = ["supermodule:android/default/litho.core"],
    language = "KOTLIN",
    provided_deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
    ],
    required_for_source_only_abi = True,
    visibility = ["PUBLIC"],
    deps = [
        LITHO_UTILS_TARGET,
        LITHO_KOTLIN_TARGET,
        LITHO_WIDGET_RES_TARGET,
        LITHO_YOGA_FACTORY_TARGET,
    ],
    exported_deps = [
        LITHO_WIDGET_TARGET,
    ],
)
