# Copyright (c) Facebook, Inc. and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_KOTLIN_SECTIONS_TARGET",
    "LITHO_PERF_LOGGER",
    "LITHO_PROCESSOR_TARGET",
    "LITHO_RES_TARGET",
    "LITHO_SECTIONS_PROCESSOR_TARGET",
    "LITHO_SECTIONS_TARGET",
    "LITHO_WIDGET_RES_TARGET",
    "LITHO_WIDGET_TARGET",
    "litho_android_library",
    "make_dep_path",
)

litho_android_library(
    name = "widget",
    feature = FBApp_UIFrameworks_Litho_Litho,
    labels = [],
    plugins = [
        LITHO_PROCESSOR_TARGET,
        LITHO_SECTIONS_PROCESSOR_TARGET,
    ],
    provided_deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
    ],
    required_for_source_only_abi = True,
    tests = [make_dep_path("litho-widget-kotlin/src/test/kotlin/com/facebook/litho/widget:widget")],
    visibility = ["PUBLIC"],
    deps = [
        LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        LITHO_KOTLIN_SECTIONS_TARGET,
        LITHO_SECTIONS_TARGET,
        LITHO_PERF_LOGGER,
        LITHO_JAVA_TARGET,
        LITHO_RES_TARGET,
        LITHO_WIDGET_RES_TARGET,
    ],
    exported_deps = [
        LITHO_WIDGET_TARGET,
    ],
)
