# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET",
    "LITHO_ANDROIDSUPPORT_SWIPEREFRESHLAYOUT_TARGET",
    "LITHO_INFERANNOTATIONS_TARGET",
    "LITHO_JSR_TARGET",
    "LITHO_OSS_TARGET",
    "LITHO_PERF_LOGGER",
    "LITHO_PROCESSOR_TARGET",
    "LITHO_RENDERCORE_PRIMITIVES_TARGET",
    "LITHO_RENDERCORE_RES_TARGET",
    "LITHO_RENDERCORE_TARGET",
    "LITHO_RENDERCORE_TEXT_TARGET",
    "LITHO_RES_TARGET",
    "LITHO_TEXTLAYOUTBUILDER_TARGET",
    "LITHO_TEXTLAYOUTBUILDER_UTILS_TARGET",
    "LITHO_WIDGET_ACCESSIBILITIES_TARGET",
    "LITHO_WIDGET_RES_TARGET",
    "LITHO_YOGA_TARGET",
    "litho_android_library",
    "make_dep_path",
)

oncall("litho_components_for_android")

litho_android_library(
    name = "widget",
    autoglob = False,
    feature = FBApp_UIFrameworks_Litho_Litho,
    labels = [],
    visibility = [
        "PUBLIC",
    ],
    exported_deps = [
        ":widget-bare",
        LITHO_TEXTLAYOUTBUILDER_TARGET,
    ],
)

litho_android_library(
    name = "widget-bare",
    srcs = glob([
        "*.java",
        "*.kt",
        "**/*.kt",
    ]),
    autoglob = False,
    exported_provided_deps = [
        LITHO_ANDROIDSUPPORT_SWIPEREFRESHLAYOUT_TARGET,
    ],
    feature = FBApp_UIFrameworks_Litho_Litho,
    labels = [],
    plugins = [
        LITHO_PROCESSOR_TARGET,
    ],
    provided_deps = [
        LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        LITHO_INFERANNOTATIONS_TARGET,
        LITHO_JSR_TARGET,
        LITHO_OSS_TARGET,
        LITHO_TEXTLAYOUTBUILDER_TARGET,
        LITHO_YOGA_TARGET,
    ],
    pure_kotlin = False,
    required_for_source_only_abi = True,
    tests = [
        make_dep_path("litho-it/src/test/com/facebook/litho:litho"),
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = LITHO_TEXTLAYOUTBUILDER_UTILS_TARGET + [
        LITHO_RES_TARGET,
        LITHO_WIDGET_RES_TARGET,
        LITHO_WIDGET_ACCESSIBILITIES_TARGET,
        LITHO_PERF_LOGGER,
        LITHO_RENDERCORE_RES_TARGET,
    ],
    exported_deps = [
        LITHO_RENDERCORE_TARGET,
        LITHO_RENDERCORE_TEXT_TARGET,
        LITHO_RENDERCORE_PRIMITIVES_TARGET,
    ],
)
