load("//tools/build_defs/oss:litho_defs.bzl", "fb_java_library")

fb_java_library(
    name = "lib",
    srcs = glob(["*.java"]),
    source = "8",
    target = "8",
    visibility = [
        "PUBLIC",
    ],
)
