# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_VISIBILITY",
    "litho_android_library",
)

litho_android_library(
    name = "annotations",
    srcs = glob(["*.java"]),
    autoglob = False,
    proguard_config = "proguard_annotations.pro",
    visibility = LITHO_VISIBILITY,
    deps = [
    ],
)
