# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

java_library(
    name = "shadows-prebuilt-core",
    exported_deps = [
        ":shadows-core-16-jar",
    ],
    visibility = [
        "//lib/robolectric3:robolectric3",
        "//libraries/components/lib/robolectric3:robolectric3",
    ],
)

prebuilt_jar(
    name = "shadows-core-16-jar",
    binary_jar = "shadows-core-3.0-16.jar",
)
