# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load("//tools/build_defs/oss:fb_native_wrapper.bzl", "fb_native")
load("//tools/build_defs/oss:litho_defs.bzl", "LITHO_VISIBILITY", "fb_java_library")

fb_java_library(
    name = "shadows-prebuilt-core",
    visibility = [
        "//lib/robolectric3:robolectric3",
        "//libraries/components/lib/robolectric3:robolectric3",
    ],
    exported_deps = [
        ":shadows-core-16-jar",
    ],
)

fb_native.prebuilt_jar(
    name = "shadows-core-16-jar",
    binary_jar = "shadows-core-3.0-16.jar",
)

fb_native.prebuilt_jar(
    name = "android-all-5.0.0",
    binary_jar = "android-all-5.0.0_r2-robolectric-1.jar",
    visibility = LITHO_VISIBILITY,
)
