# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

java_binary(
    name = "litho-sections-processor",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        make_dep_path("litho-sections-processor/src/main/java/com/facebook/litho/sections/processor:processor-lib"),
    ],
)
