# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//tools/build_defs/oss:litho_defs.bzl", "fb_java_binary", "make_dep_path")

fb_java_binary(
    name = "litho-sections-processor",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        make_dep_path("litho-sections-processor/src/main/java/com/facebook/litho/sections/specmodels/processor:processor-lib"),
    ],
)
