# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ASSERTJ_TARGET",
    "LITHO_BUILD_CONFIG_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_JUNIT_TARGET",
    "LITHO_MOCKITO_TARGET",
    "LITHO_ROBOLECTRIC_V4_TARGET",
    "LITHO_TESTING_V4_TARGET",
    "components_robolectric_test",
    "make_dep_path",
)

components_robolectric_test(
    name = "helper",
    srcs = glob(["*Test.java"]),
    contacts = ["oncall+components_for_android@xmail.facebook.com"],
    provided_deps = [
        LITHO_ROBOLECTRIC_V4_TARGET,
    ],
    source = "8",
    target = "8",
    deps = [
        LITHO_ASSERTJ_TARGET,
        LITHO_BUILD_CONFIG_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JUNIT_TARGET,
        LITHO_MOCKITO_TARGET,
        LITHO_TESTING_V4_TARGET,
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/helper:helper-v4"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/testrunner:testrunner-v4"),
    ],
)
