include_defs("//COMPONENTS_DEFS")

components_robolectric_test(
    name = "components",
    srcs = glob([
        "*Test.java",
    ]),
    contacts = ["oncall+components_for_android@xmail.facebook.com"],
    deps = [
        "//libraries/components/src/debug/java/com/facebook/components/testing:testing",
        "//libraries/components/src/debug/java/com/facebook/components/testing/testrunner:testrunner",
        "//libraries/components/src/main/java/com/facebook/components:components",
        "//libraries/components/src/main/java/com/facebook/components/widget:widget",
        "//libraries/components/src/test/java/com/facebook/components:res",
        "//third-party/java/assertj:assertj-core",
        "//third-party/java/mockito:mockito",
        "//third-party/java/powermock/reflect:reflect",
        COMPONENTS_ROBOLECTRIC_TARGET,
    ],
)

android_resource(
    name = "res",
    res = "res",
    visibility = [
        "//javatests/com/facebook/components/...",
    ],
)
