include_defs("//COMPONENTS_DEFS")

OSS_TESTS = [
    "FastMathTest.java",
    "LayoutOutputTest.java",
    "TestItemTest.java",
]

oss_components_robolectric_test(
    name = "oss_components",
    srcs = OSS_TESTS,
    contacts = ["oncall+components_for_android@xmail.facebook.com"],
    provided_deps = [
        COMPONENTS_ROBOLECTRIC_TARGET,
    ],
    deps = [
        COMPONENTS_JAVA_TARGET,
        COMPONENTS_JUNIT_TARGET,
        COMPONENTS_ASSERTJ_TARGET,
        COMPONENTS_MOCKITO_TARGET,
        COMPONENTS_POWERMOCK_REFLECT_TARGET,
        COMPONENTS_SOLOADER_TARGET,
        make_dep_path("src/main/java/com/facebook/components/widget:widget"),
        make_dep_path("src/test/java/com/facebook/components:res"),
        make_dep_path("src/debug/java/com/facebook/components/testing:testing"),
        make_dep_path("src/debug/java/com/facebook/components/testing/testrunner:testrunner"),
    ],
)

components_robolectric_test(
    name = "components",
    srcs = glob(
        ["*Test.java"],
        excludes = OSS_TESTS,
    ),
    contacts = ["oncall+components_for_android@xmail.facebook.com"],
    provided_deps = [
        COMPONENTS_ROBOLECTRIC_TARGET,
    ],
    deps = [
        make_dep_path("src/main/java/com/facebook/components/widget:widget"),
        make_dep_path("src/debug/java/com/facebook/components/testing:testing"),
        make_dep_path("src/debug/java/com/facebook/components/testing/testrunner:testrunner"),
        make_dep_path("src/test/java/com/facebook/components:res"),
        COMPONENTS_ASSERTJ_TARGET,
        COMPONENTS_MOCKITO_TARGET,
        COMPONENTS_ROBOLECTRIC_TARGET,
        COMPONENTS_JAVA_TARGET,
        COMPONENTS_JUNIT_TARGET,
        COMPONENTS_POWERMOCK_REFLECT_TARGET,
    ],
)

android_resource(
    name = "res",
    package = "com.facebook",
    res = "res",
    visibility = [
        "//javatests/com/facebook/components/...",
    ],
)
