# This is a package of stubs, to allow the calling of a hidden DisplayList
# methods. They must be referenced as provided_deps. Since future platforms
# may change this hidden API, callers should handle LinkageError gracefully.

java_library(
    name = "stubs",
    srcs = glob([
        "src/**/*.java",
    ]),
    visibility = ["PUBLIC"],
)
