# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//tools/build_defs/oss:fb_native_wrapper.bzl", "fb_native")
load("//tools/build_defs/oss:litho_defs.bzl", "make_dep_path")

fb_native.java_binary(
    name = "litho-annotations",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        make_dep_path("litho-annotations/src/main/java/com/facebook/litho/annotations:annotations"),
    ],
)
