# BUILD FILE SYNTAX: SKYLARK
# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//:LITHO_DEFS.bzl", "make_dep_path")

java_binary(
    name = "litho-annotations",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        make_dep_path("litho-annotations/src/main/java/com/facebook/litho/annotations:annotations"),
    ],
)
