# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("@fbsource//third-party/java/jarjar:unshade.bzl", "unshade_kotlin_compiler_plugin_rule")
load("@fbsource//tools/build_defs:fb_native_wrapper.bzl", "fb_native")
load("@fbsource//tools/build_defs/features:native_feature_wrapper.bzl", "feature_native")
load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")

oncall("litho_components_for_android")

fb_native.java_binary(
    name = "litho-compiler-plugin-shaded",
    blacklist = [
        # It's probably possible to reduce this restriction to specific list of classes
        "com.intellij",
        "kotlinx.collections.immutable",
        "org.jetbrains.kotlin.it.unimi.dsi.fastutil",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//fbandroid/libraries/components/litho-compiler-plugin/compiler:litho-compiler",
    ],
)

feature_native.prebuilt_jar(
    name = "litho-compiler-plugin",
    binary_jar = unshade_kotlin_compiler_plugin_rule(":litho-compiler-plugin-shaded"),
    feature = FBApp_UIFrameworks_Litho_Litho,
    visibility = ["PUBLIC"],
)
