# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("@fbsource//tools/build_defs:fb_native_wrapper.bzl", "fb_native")

oncall("litho_components_for_android")

fb_native.java_binary(
    name = "litho-compiler-plugin",
    visibility = ["PUBLIC"],
    deps = [
        "//fbandroid/libraries/components/litho-compiler-plugin/compiler:litho-compiler",
    ],
)
