# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load("@fbsource//tools/build_defs/android:litho_jni.bzl", "LITHO_JNI_DEPS")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_TESTING_JUNIT_TARGET",
    "LITHO_ASSERTJ_TARGET",
    "LITHO_BUILD_CONFIG_TARGET",
    "LITHO_JSR_TARGET",
    "LITHO_JUNIT_TARGET",
    "LITHO_KOTLIN_TARGET",
    "LITHO_MOCKITO_KOTLIN_V2_TARGET",
    "LITHO_PROCESSOR_TARGET",
    "LITHO_RENDERCORE_TESTING_TARGET",
    "LITHO_ROBOLECTRIC_V4_TARGET",
    "LITHO_SECTIONS_WIDGET_KOTLIN_TARGET",
    "LITHO_SOLOADER_TARGET",
    "LITHO_STATS_TARGET",
    "LITHO_TESTING_ASSERTJ_TARGET",
    "LITHO_TESTING_TARGET",
    "LITHO_WIDGET_KOTLIN_COLLECTION_TARGET",
    "LITHO_WIDGET_KOTLIN_TARGET",
    "LITHO_YOGA_TARGET",
    "litho_robolectric4_test",
)

litho_robolectric4_test(
    name = "flipper",
    srcs = glob(["**/*.kt"]),
    contacts = ["oncall+components_for_android@xmail.facebook.com"],
    fork_mode = "per_test",
    jni_deps = LITHO_JNI_DEPS,
    language = "KOTLIN",
    plugins = [
        LITHO_PROCESSOR_TARGET,
    ],
    provided_deps = [
        LITHO_ROBOLECTRIC_V4_TARGET,
    ],
    source = "8",
    target = "8",
    deps = [
        LITHO_TESTING_TARGET,
        LITHO_TESTING_ASSERTJ_TARGET,
        LITHO_SECTIONS_WIDGET_KOTLIN_TARGET,
        LITHO_ANDROIDSUPPORT_TESTING_JUNIT_TARGET,
        LITHO_ASSERTJ_TARGET,
        LITHO_BUILD_CONFIG_TARGET,
        LITHO_JUNIT_TARGET,
        LITHO_KOTLIN_TARGET,
        LITHO_MOCKITO_KOTLIN_V2_TARGET,
        LITHO_RENDERCORE_TESTING_TARGET,
        LITHO_WIDGET_KOTLIN_COLLECTION_TARGET,
        LITHO_WIDGET_KOTLIN_TARGET,
        LITHO_SOLOADER_TARGET,
        LITHO_STATS_TARGET,
        LITHO_YOGA_TARGET,
        LITHO_JSR_TARGET,
        "//fbandroid/libraries/components/litho-editor-flipper/src/main/java/com/facebook/litho/editor/flipper:flipper",
        #"//fbandroid/libraries/components/litho-it-spec/src/test/java/com/facebook/litho:litho",
        "//xplat/sonar/android/src/main/java/com/facebook/flipper/core:core",
        "//xplat/sonar/android/src/main/java/com/facebook/flipper/plugins/inspector:inspectorAndroid",
        "//third-party/java/org/jetbrains/annotations:annotations",
    ],
)
