# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load("@fbsource//tools/build_defs/android:litho_jni.bzl", "LITHO_JNI_DEPS")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_SWIPEREFRESHLAYOUT_TARGET",
    "LITHO_ANDROIDSUPPORT_TESTING_CORE_TARGET",
    "LITHO_ANDROIDSUPPORT_TESTING_JUNIT_TARGET",
    "LITHO_ASSERTJ_TARGET",
    "LITHO_JUNIT_TARGET",
    "LITHO_KOTLIN_TARGET",
    "LITHO_MOCKITO_KOTLIN_V2_TARGET",
    "LITHO_PROCESSOR_TARGET",
    "LITHO_ROBOLECTRIC_V4_TARGET",
    "LITHO_TESTING_CORE_TARGET",
    "LITHO_TESTING_TEST_RUNNER_TARGET",
    "LITHO_WIDGET_KOTLIN_COLLECTION_TARGET",
    "LITHO_WIDGET_KOTLIN_TARGET",
    "LITHO_WIDGET_TARGET",
    "LITHO_YOGA_TARGET",
    "litho_robolectric4_test",
    "make_dep_path",
)

litho_robolectric4_test(
    name = "api",
    srcs = glob(
        [
            "**/*.java",
            "**/*.kt",
        ],
    ),
    contacts = ["oncall+components_for_android@xmail.facebook.com"],
    jni_deps = LITHO_JNI_DEPS,
    plugins = [
        LITHO_PROCESSOR_TARGET,
    ],
    provided_deps = [
        LITHO_ROBOLECTRIC_V4_TARGET,
    ],
    pure_kotlin = False,
    tests = [
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/api:api"),
    ],
    deps = [
        LITHO_ANDROIDSUPPORT_SWIPEREFRESHLAYOUT_TARGET,
        LITHO_ANDROIDSUPPORT_TESTING_CORE_TARGET,
        LITHO_ANDROIDSUPPORT_TESTING_JUNIT_TARGET,
        LITHO_ASSERTJ_TARGET,
        LITHO_JUNIT_TARGET,
        LITHO_KOTLIN_TARGET,
        LITHO_MOCKITO_KOTLIN_V2_TARGET,
        LITHO_TESTING_CORE_TARGET,
        LITHO_TESTING_TEST_RUNNER_TARGET,
        LITHO_WIDGET_KOTLIN_COLLECTION_TARGET,
        LITHO_WIDGET_KOTLIN_TARGET,
        LITHO_WIDGET_TARGET,
        LITHO_YOGA_TARGET,
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/api:api"),
    ],
)
