load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_INFERANNOTATIONS_TARGET",
    "LITHO_JSR_TARGET",
    "LITHO_PROGUARD_ANNOTATIONS_TARGET",
    "LITHO_RENDERCORE_TARGET",
    "fb_android_library",
)

fb_android_library(
    name = "rendercore-incremental-mount-stub",
    srcs = glob(["src/main/java/**/*.java"]),
    autoglob = False,
    labels = ["supermodule:android/default/rendercore"],
    provided_deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_JSR_TARGET,
        LITHO_PROGUARD_ANNOTATIONS_TARGET,
    ],
    required_for_source_only_abi = True,
    visibility = ["PUBLIC"],
    deps = [
        LITHO_RENDERCORE_TARGET,
        LITHO_INFERANNOTATIONS_TARGET,
    ],
)
