#
# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

android_library(
    name = "widget",
    srcs = glob([
        "**/*.java",
    ]),
    plugins = [
        COMPONENTS_PROCESSOR_TARGET,
        COMPONENTS_SECTIONS_PROCESSOR_TARGET,
    ],
    visibility = [
        "PUBLIC",
    ],
    provided_deps = [
        COMPONENTS_SECTIONS_ANNOTATIONS_TARGET,
        COMPONENTS_ANNOTATIONS_TARGET,
    ],
    deps = [
        COMPONENTS_SECTIONS_TARGET,
        COMPONENTS_SECTIONS_CONFIG_TARGET,
        COMPONENTS_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        COMPONENTS_ANDROIDSUPPORT_TARGET,
        COMPONENTS_JSR_TARGET,
        COMPONENTS_WIDGET_TARGET,
        COMPONENTS_YOGA_TARGET,
        COMPONENTS_JAVA_TARGET,
    ],
)
