# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
# of patent rights can be found in the PATENTS file in the same directory.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_ANNOTATIONS_TARGET",
    "LITHO_INFERANNOTATIONS_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_JSR_TARGET",
    "LITHO_KOTLIN_STDLIB_TARGET",
    "LITHO_PROCESSOR_TARGET",
    "LITHO_SECTIONS_ANNOTATIONS_TARGET",
    "LITHO_SECTIONS_COMMON_TARGET",
    "LITHO_SECTIONS_CONFIG_TARGET",
    "LITHO_SECTIONS_PROCESSOR_TARGET",
    "LITHO_SECTIONS_TARGET",
    "LITHO_WIDGET_TARGET",
    "LITHO_YOGA_TARGET",
    "litho_android_library",
)

litho_android_library(
    name = "widget",
    is_androidx = True,
    labels = ["supermodule:android/default/litho.core"],
    plugins = [
        LITHO_PROCESSOR_TARGET,
        LITHO_SECTIONS_PROCESSOR_TARGET,
    ],
    provided_deps = [
        LITHO_ANNOTATIONS_TARGET,
        LITHO_SECTIONS_ANNOTATIONS_TARGET,
    ],
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//fbandroid/third-party/java/infer-annotations:infer-annotations",
        LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_INFERANNOTATIONS_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JSR_TARGET,
        LITHO_KOTLIN_STDLIB_TARGET,
        LITHO_SECTIONS_COMMON_TARGET,
        LITHO_SECTIONS_CONFIG_TARGET,
        LITHO_SECTIONS_TARGET,
        LITHO_WIDGET_TARGET,
        LITHO_YOGA_TARGET,
    ],
)
