# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

android_prebuilt_aar(
    name = "fbcore",
    aar = ":fbcore-aar",
    visibility = ["PUBLIC"],
)

remote_file(
    name = "fbcore-aar",
    sha1 = "d9ea35752271fcc7674f4e1dd399600dfeca075b",
    url = "mvn:com.facebook.fresco:fbcore:aar:1.1.0",
)
