# BUILD FILE SYNTAX: SKYLARK
# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

android_prebuilt_aar(
    name = "fbcore",
    aar = ":fbcore-aar",
    visibility = ["PUBLIC"],
)

remote_file(
    name = "fbcore-aar",
    sha1 = "8b8deec16a978e97aacad85012797661efe69a61",
    url = "mvn:com.facebook.fresco:fbcore:aar:1.5.0",
)
