# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load("//:LITHO_DEFS", "LITHO_ANDROIDSUPPORT_TARGET", "LITHO_JAVA_TARGET", "LITHO_JSR_TARGET", "LITHO_MOCKITO_TARGET", "LITHO_SECTIONS_ANNOTATIONS_TARGET", "LITHO_SECTIONS_COMMON_TARGET", "LITHO_SECTIONS_PROCESSOR_TARGET", "LITHO_SECTIONS_TARGET", "LITHO_WIDGET_TARGET")

android_library(
    name = "sections",
    srcs = glob(["*.java"]),
    plugins = [
        LITHO_SECTIONS_PROCESSOR_TARGET,
    ],
    visibility = ["PUBLIC"],
    deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JSR_TARGET,
        LITHO_MOCKITO_TARGET,
        LITHO_SECTIONS_ANNOTATIONS_TARGET,
        LITHO_SECTIONS_TARGET,
        LITHO_WIDGET_TARGET,
        LITHO_SECTIONS_COMMON_TARGET,
    ],
)
