# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load("//tools/build_defs/oss:litho_defs.bzl", "LITHO_ANDROIDSUPPORT_TARGET", "LITHO_JAVA_TARGET", "LITHO_JSR_TARGET", "LITHO_MOCKITO_TARGET", "LITHO_SECTIONS_ANNOTATIONS_TARGET", "LITHO_SECTIONS_COMMON_TARGET", "LITHO_SECTIONS_PROCESSOR_TARGET", "LITHO_SECTIONS_TARGET", "LITHO_WIDGET_TARGET", "fb_core_android_library")

fb_core_android_library(
    name = "sections",
    srcs = glob(["*.java"]),
    is_androidx = True,
    plugins = [
        LITHO_SECTIONS_PROCESSOR_TARGET,
    ],
    visibility = ["PUBLIC"],
    deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JSR_TARGET,
        LITHO_MOCKITO_TARGET,
        LITHO_SECTIONS_ANNOTATIONS_TARGET,
        LITHO_SECTIONS_TARGET,
        LITHO_WIDGET_TARGET,
        LITHO_SECTIONS_COMMON_TARGET,
    ],
)
