# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_PERF_LOGGER",
    "LITHO_SECTIONS_ANNOTATIONS_TARGET",
    "LITHO_SECTIONS_CONFIG_TARGET",
    "LITHO_SECTIONS_PROCESSOR_TARGET",
    "LITHO_SECTIONS_TARGET",
    "LITHO_WIDGET_TARGET",
    "litho_android_library",
    "make_dep_path",
)

oncall("litho_components_for_android")

litho_android_library(
    name = "common",
    feature = FBApp_UIFrameworks_Litho_Litho,
    labels = [],
    language = "JAVA",
    nullchecker_mode = "log",
    plugins = [
        LITHO_SECTIONS_PROCESSOR_TARGET,
    ],
    provided_deps = [
        LITHO_SECTIONS_ANNOTATIONS_TARGET,
    ],
    required_for_source_only_abi = True,
    tests = [
        make_dep_path("litho-it/src/test/com/facebook/litho:litho"),
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//fbandroid/libraries/components/litho-sections-core/src/main/java/com/facebook/litho/sections/logger:logger",
        "//fbandroid/third-party/java/infer-annotations:infer-annotations",
        LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_PERF_LOGGER,
        LITHO_SECTIONS_CONFIG_TARGET,
        LITHO_SECTIONS_TARGET,
        LITHO_WIDGET_TARGET,
    ],
)
