# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//tools/build_defs/oss:litho_defs.bzl", "LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET", "LITHO_ANDROIDSUPPORT_TARGET", "LITHO_JAVA_TARGET", "LITHO_SECTIONS_ANNOTATIONS_TARGET", "LITHO_SECTIONS_CONFIG_TARGET", "LITHO_SECTIONS_PROCESSOR_TARGET", "LITHO_SECTIONS_TARGET", "LITHO_UTILS_TARGET", "LITHO_WIDGET_TARGET", "litho_android_library", "make_dep_path")

litho_android_library(
    name = "common",
    srcs = glob(["*.java"]),
    plugins = [
        LITHO_SECTIONS_PROCESSOR_TARGET,
    ],
    provided_deps = [
        LITHO_SECTIONS_ANNOTATIONS_TARGET,
        make_dep_path("litho-sections-debug/src/main/java/com/facebook/litho/sections/debug/widget:widget"),
    ],
    required_for_source_only_abi = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_JAVA_TARGET,
        LITHO_UTILS_TARGET,
        LITHO_SECTIONS_TARGET,
        LITHO_SECTIONS_CONFIG_TARGET,
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_WIDGET_TARGET,
        LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
    ],
)
