# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_JAVA_TARGET",
    "LITHO_JSR_TARGET",
    "litho_android_library",
)

litho_android_library(
    name = "accessibility",
    feature = FBApp_UIFrameworks_Litho_Litho,
    labels = [],
    language = "JAVA",
    provided_deps = [
        LITHO_JAVA_TARGET,
        LITHO_JSR_TARGET,
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//fbandroid/third-party/java/infer-annotations:infer-annotations",
    ],
)
