load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "fb_java_library",
)

# Files without javac deps for intellij plugin compilation
fb_java_library(
    name = "files4idea",
    srcs = glob(
        ["*.java"],
    ),
    source = "8",
    target = "8",
    visibility = ["PUBLIC"],
)
