# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_ANDROIDSUPPORT_TESTING_CORE_TARGET",
    "LITHO_ASSERTJ_TARGET",
    "LITHO_BUILD_CONFIG_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_JUNIT_TARGET",
    "LITHO_MOCKITO_V2_TARGET",
    "LITHO_ROBOLECTRIC_V4_TARGET",
    "LITHO_SECTIONS_ANNOTATIONS_TARGET",
    "LITHO_SECTIONS_COMMON_TARGET",
    "LITHO_SECTIONS_PROCESSOR_TARGET",
    "LITHO_SECTIONS_TARGET",
    "LITHO_UTILS_TARGET",
    "LITHO_WIDGET_TARGET",
    "litho_robolectric4_test",
    "make_dep_path",
)

litho_robolectric4_test(
    name = "common",
    srcs = glob(["*.java"]),
    plugins = [
        LITHO_SECTIONS_PROCESSOR_TARGET,
    ],
    source = "8",
    target = "8",
    deps = [
        LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_ANDROIDSUPPORT_TESTING_CORE_TARGET,
        LITHO_ASSERTJ_TARGET,
        LITHO_BUILD_CONFIG_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JUNIT_TARGET,
        LITHO_MOCKITO_V2_TARGET,
        LITHO_ROBOLECTRIC_V4_TARGET,
        LITHO_SECTIONS_ANNOTATIONS_TARGET,
        LITHO_SECTIONS_COMMON_TARGET,
        LITHO_SECTIONS_TARGET,
        LITHO_UTILS_TARGET,
        LITHO_WIDGET_TARGET,
        make_dep_path("litho-it/src/main/java/com/facebook/litho/sections/common:common"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/internal:internal"),
        make_dep_path("litho-sections-core/src/main/java/com/facebook/litho/sections/logger:logger"),
        make_dep_path("litho-sections-widget/src/main/java/com/facebook/litho/sections/widget:widget"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/sections:sections-v4"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/testrunner:testrunner-v4"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/viewtree:viewtree-v4"),
    ],
)
