# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

android_prebuilt_aar(
    name = "appcompat-aar",
    aar = ":android-appcompat-v7.aar",
)

remote_file(
    name = "android-appcompat-v7.aar",
    sha1 = "99ba6ed8d35e089c35ce4d6a09d083a2829a81b3",
    url = "mvn:com.android.support:appcompat-v7:aar:25.3.1",
)

java_library(
    name = "appcompat",
    exported_deps = [
        ":appcompat-aar",
    ],
    visibility = COMPONENTS_VISIBILITY,
)
