# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

android_prebuilt_aar(
    name = "appcompat",
    aar = "appcompat-v7-24.1.1.aar",
    visibility = [
        COMPONENTS_VISIBILITY,
    ],
)
