# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

litho_android_library(
    name = "shadows",
    srcs = glob(["*.java"]),
    visibility = [
        make_dep_path("litho-it/src/test/..."),
        make_dep_path("litho-it-powermock/src/test/..."),
    ],
    deps = [
        COMPONENTS_ANDROIDSUPPORT_TARGET,
        COMPONENTS_ROBOLECTRIC_TARGET,
        COMPONENTS_YOGA_TARGET,
    ],
)
