# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ROBOLECTRIC_V4_TARGET",
    "LITHO_YOGA_TARGET",
    "litho_android_library",
    "make_dep_path",
)

litho_android_library(
    name = "shadows",
    language = "JAVA",
    visibility = [
        make_dep_path("litho-it/src/test/..."),
    ],
    deps = [
        "//fbandroid/third-party/java/infer-annotations:infer-annotations",
        LITHO_ROBOLECTRIC_V4_TARGET,
        LITHO_YOGA_TARGET,
    ],
)
