load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")
load("//tools/build_defs/oss:litho_defs.bzl", "LITHO_JAVA_TARGET", "LITHO_JSR_TARGET", "LITHO_KOTLIN_STDLIB_TARGET", "fb_android_library")

oncall("litho_components_for_android")

DEPS = [
    LITHO_JSR_TARGET,
    LITHO_KOTLIN_STDLIB_TARGET,
    LITHO_JAVA_TARGET,
]

fb_android_library(
    name = "editor",
    srcs = glob([
        "**/*.kt",
    ]),
    autoglob = False,
    feature = FBApp_UIFrameworks_Litho_Litho,
    k2 = True,
    labels = [],
    visibility = [
        "PUBLIC",
    ],
    deps = DEPS + [
        "//fbandroid/third-party/java/infer-annotations:infer-annotations",
        "//third-party/java/androidx/annotation/annotation:annotation",
    ],
)
