load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")
load("//tools/build_defs/oss:litho_defs.bzl", "LITHO_ANDROIDSUPPORT_TARGET", "LITHO_JSR_TARGET", "LITHO_KOTLIN_STDLIB_TARGET", "LITHO_KOTLIN_TARGET", "fb_android_library")

DEPS = [
    LITHO_JSR_TARGET,
    LITHO_ANDROIDSUPPORT_TARGET,
    LITHO_KOTLIN_STDLIB_TARGET,
    LITHO_KOTLIN_TARGET,
]

fb_android_library(
    name = "editor",
    srcs = glob([
        "**/*.java",
        "**/*.kt",
    ]),
    autoglob = False,
    feature = FBApp_UIFrameworks_Litho_Litho,
    labels = [],
    pure_kotlin = False,
    visibility = [
        "PUBLIC",
    ],
    deps = DEPS,
)
