# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_ANNOTATIONS_TARGET",
    "LITHO_ASSERTJ_TARGET",
    "LITHO_HAMCREST_CORE_TARGET",
    "LITHO_HAMCREST_LIBRARY_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_JSR_TARGET",
    "LITHO_JUNIT_TARGET",
    "LITHO_PROCESSOR_LIB_TARGET",
    "LITHO_ROBOLECTRIC_V4_TARGET",
    "LITHO_TESTING_ASSERTJ_TARGET",
    "LITHO_TESTING_CORE_TARGET",
    "LITHO_TESTING_SUBCOMPONENTS_TARGET",
    "LITHO_TESTING_TARGET",
    "LITHO_WIDGET_TARGET",
    "litho_android_library",
)

litho_android_library(
    name = "widget",
    srcs = glob(["*Spec.java"]),
    annotation_processor_deps = [
        LITHO_PROCESSOR_LIB_TARGET,
    ],
    annotation_processors = [
        "com.facebook.litho.specmodels.processor.testing.ComponentsTestingProcessor",
    ],
    is_androidx = True,
    visibility = ["PUBLIC"],
    deps = [
        LITHO_WIDGET_TARGET,
        LITHO_JSR_TARGET,
        LITHO_HAMCREST_CORE_TARGET,
        LITHO_HAMCREST_LIBRARY_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_ANNOTATIONS_TARGET,
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        LITHO_TESTING_ASSERTJ_TARGET,
        LITHO_TESTING_CORE_TARGET,
        LITHO_TESTING_TARGET,
    ],
    exported_deps = [
        LITHO_TESTING_CORE_TARGET,
    ],
)

litho_android_library(
    name = "widget_conditions",
    srcs = glob(["**/*.java"]),
    is_androidx = True,
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_ANNOTATIONS_TARGET,
        LITHO_ASSERTJ_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JUNIT_TARGET,
        LITHO_ROBOLECTRIC_V4_TARGET,
        LITHO_TESTING_SUBCOMPONENTS_TARGET,
        LITHO_WIDGET_TARGET,
    ],
)
