# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

include_defs("//LITHO_DEFS.bzl")

litho_android_library(
    name = "widget",
    srcs = glob(["*Spec.java"]),
    annotation_processor_deps = [
        LITHO_PROCESSOR_LIB_TARGET,
    ],
    annotation_processors = [
        "com.facebook.litho.specmodels.processor.testing.ComponentsTestingProcessor",
    ],
    exported_deps = [
        LITHO_TESTING_CORE_TARGET,
    ],
    visibility = ["PUBLIC"],
    deps = [
        LITHO_JAVA_TARGET,
        LITHO_WIDGET_TARGET,
        LITHO_ANNOTATIONS_TARGET,
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        LITHO_TESTING_TARGET,
        LITHO_TESTING_CORE_TARGET,
        LITHO_TESTING_ASSERTJ_TARGET,
        LITHO_JSR_TARGET,
        LITHO_HAMCREST_CORE_TARGET,
        LITHO_HAMCREST_LIBRARY_TARGET,
    ],
)
