# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

litho_android_library(
    name = "widget",
    srcs = glob(["*Spec.java"]),
    annotation_processor_deps = [
        COMPONENTS_PROCESSOR_LIB_TARGET,
    ],
    annotation_processors = [
        "com.facebook.litho.specmodels.processor.testing.ComponentsTestingProcessor",
    ],
    visibility = ["PUBLIC"],
    deps = [
        COMPONENTS_JAVA_TARGET,
        COMPONENTS_WIDGET_TARGET,
        COMPONENTS_ANNOTATIONS_TARGET,
        COMPONENTS_ANDROIDSUPPORT_TARGET,
        COMPONENTS_TESTING_TARGET,
        COMPONENTS_TESTING_ASSERTJ_TARGET,
        COMPONENTS_JSR_TARGET,
        COMPONENTS_HAMCREST_CORE_TARGET,
        COMPONENTS_HAMCREST_LIBRARY_TARGET,
    ],
)
