# Copyright (c) Facebook, Inc. and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_KOTLIN_STDLIB_TARGET",
    "LITHO_KOTLIN_TARGET",
    "LITHO_RENDERCORE_PRIMITIVE_COMPONENTS_CANVAS_TARGET",
    "LITHO_RENDERCORE_PRIMITIVE_COMPONENTS_UTILS_TARGET",
    "litho_android_library",
)

litho_android_library(
    name = "canvas",
    feature = FBApp_UIFrameworks_Litho_Litho,
    labels = [],
    visibility = ["PUBLIC"],
    deps = [
        LITHO_KOTLIN_TARGET,
        LITHO_KOTLIN_STDLIB_TARGET,
        LITHO_RENDERCORE_PRIMITIVE_COMPONENTS_CANVAS_TARGET,
    ],
    exported_deps = [
        LITHO_RENDERCORE_PRIMITIVE_COMPONENTS_UTILS_TARGET,
    ],
)
