# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

java_annotation_processor(
    name = "processor",
    processor_class = "com.facebook.litho.processor.ComponentsProcessor",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":processor-lib",
    ],
)

java_library(
    name = "processor-lib",
    exported_deps = [
        ":processor-lib-bare",
        COMPONENTS_FBCORE_TARGET,
        COMPONENTS_JAVAPOET_TARGET,
    ],
