# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

java_annotation_processor(
    name = "processor",
    processor_class = "com.facebook.litho.processor.ComponentsProcessor",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":processor-lib",
    ],
)

java_library(
    name = "processor-lib",
    exported_deps = [
        ":processor-lib-bare",
        COMPONENTS_FBCORE_TARGET,
        COMPONENTS_JAVAPOET_TARGET,
    ],
    tests = [
        "//javatests/com/facebook/components/processor:processor",
    ],
    visibility = [
        "PUBLIC",
    ],
)

java_library(
    name = "processor-lib-bare",
    srcs = glob(["*.java"]),
    provided_deps = [
        COMPONENTS_FBCORE_TARGET,
        COMPONENTS_JAVAPOET_TARGET,
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels:specmodels-bare"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/processor:processor"),
        make_dep_path("src/main/java/com/facebook/components/javapoet:javapoet"),
        COMPONENTS_ANNOTATIONS_TARGET,
