# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

include_defs("//LITHO_DEFS.bzl")

components_robolectric_test(
    name = "utils",
    srcs = glob(["*Test.java"]),
    provided_deps = [
        LITHO_ROBOLECTRIC_TARGET,
    ],
    source = "8",
    target = "8",
    deps = [
        LITHO_ASSERTJ_TARGET,
        LITHO_BUILD_CONFIG_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JUNIT_TARGET,
        LITHO_MOCKITO_TARGET,
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/testrunner:testrunner"),
        make_dep_path("litho-core/src/main/java/com/facebook/litho/utils:utils"),
    ],
)
