# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

components_robolectric_test(
    name = "utils",
    srcs = glob(["*Test.java"]),
    provided_deps = [
        COMPONENTS_ROBOLECTRIC_TARGET,
    ],
    deps = [
        COMPONENTS_ASSERTJ_TARGET,
        COMPONENTS_BUILD_CONFIG_TARGET,
        COMPONENTS_JAVA_TARGET,
        COMPONENTS_JUNIT_TARGET,
        COMPONENTS_MOCKITO_TARGET,
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/testrunner:testrunner"),
        make_dep_path("litho-core/src/main/java/com/facebook/litho/utils:utils"),
    ],
)
