load("//tools/build_defs/oss:fb_native_wrapper.bzl", "fb_native")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_INFERANNOTATIONS_TARGET",
    "LITHO_RENDERCORE_PRIMITIVES_TARGET",
    "LITHO_RENDERCORE_TARGET",
    "LITHO_RENDERCORE_TEXT_TARGET",
    "LITHO_TEXTLAYOUTBUILDER_TARGET",
    "LITHO_TEXTLAYOUTBUILDER_UTILS_TARGET",
    "fb_android_resource",
    "litho_android_library",
)

litho_android_library(
    name = "litho-rendercore-text",
    srcs = glob([
        "src/main/java/**/*.java",
        "src/main/java/**/*.kt",
    ]),
    autoglob = False,
    pure_kotlin = False,
    visibility = [
        "PUBLIC",
    ],
    deps = LITHO_TEXTLAYOUTBUILDER_UTILS_TARGET + [
        ":res",
        "//fbandroid/android_res/rendercore:rendercore",
        "//fbandroid/java/com/facebook/annotations:annotations",
        "//fbandroid/java/com/facebook/proguard/annotations:annotations",
        "//fbandroid/third-party/java/infer-annotations:infer-annotations",
        "//third-party/java/androidx/core/core-ktx:core-ktx",
        "//third-party/java/androidx/customview/customview:customview",
        LITHO_INFERANNOTATIONS_TARGET,
        LITHO_RENDERCORE_PRIMITIVES_TARGET,
        LITHO_RENDERCORE_TARGET,
        LITHO_TEXTLAYOUTBUILDER_TARGET,
    ],
)

fb_android_resource(
    name = "res",
    package = "com.facebook.rendercore.text",
    res = "src/main/res",
    visibility = [
        LITHO_RENDERCORE_TEXT_TARGET,
    ],
)

fb_native.android_aar(
    name = "rendercore-text-res",
    manifest_skeleton = "AndroidManifestSkeleton.xml",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":res",
    ],
)
