load("//tools/build_defs/oss:fb_native_wrapper.bzl", "fb_native")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_INFERANNOTATIONS_TARGET",
    "LITHO_RENDERCORE_TARGET",
    "LITHO_RENDERCORE_TEXT_TARGET",
    "LITHO_TEXTLAYOUTBUILDER_TARGET",
    "LITHO_TEXTLAYOUTBUILDER_UTILS_TARGET",
    "fb_android_resource",
    "litho_android_library",
)

litho_android_library(
    name = "litho-rendercore-text",
    srcs = glob(["src/main/java/**/*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = LITHO_TEXTLAYOUTBUILDER_UTILS_TARGET + [
        ":res",
        LITHO_RENDERCORE_TARGET,
        LITHO_TEXTLAYOUTBUILDER_TARGET,
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_INFERANNOTATIONS_TARGET,
        "//fbandroid/java/com/facebook/proguard/annotations:annotations",
    ],
)

fb_android_resource(
    name = "res",
    package = "com.facebook.rendercore.text",
    res = "src/main/res",
    visibility = [
        LITHO_RENDERCORE_TEXT_TARGET,
    ],
)

fb_native.android_aar(
    name = "rendercore-text-res",
    manifest_skeleton = "AndroidManifestSkeleton.xml",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        ":res",
    ],
)
