# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load("//:LITHO_DEFS", "LITHO_JAVA_TARGET", "LITHO_TESTING_UTIL_VISIBILITY")

android_library(
    name = "util",
    srcs = glob(["*.java"]),
    visibility = LITHO_TESTING_UTIL_VISIBILITY,
    deps = [
        LITHO_JAVA_TARGET,
    ],
)
