# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//:LITHO_DEFS", "LITHO_JAVA_TARGET", "LITHO_TESTING_UTIL_VISIBILITY")

android_library(
    name = "util",
    srcs = glob(["*.java"]),
    visibility = LITHO_TESTING_UTIL_VISIBILITY,
    deps = [
        LITHO_JAVA_TARGET,
    ],
)
