load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_VISIBILITY",
    "LITHO_YOGA_TARGET",
    "litho_android_library",
)

litho_android_library(
    name = "yoga",
    feature = FBApp_UIFrameworks_Litho_Litho,
    labels = [],
    language = "JAVA",
    visibility = LITHO_VISIBILITY,
    exported_deps = [
        LITHO_YOGA_TARGET,
    ],
)
