load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_VISIBILITY",
    "LITHO_YOGA_TARGET",
    "litho_android_library",
)

litho_android_library(
    name = "yoga",
    labels = ["supermodule:android/default/litho.core"],
    visibility = LITHO_VISIBILITY,
    exported_deps = [
        LITHO_YOGA_TARGET,
    ],
)
