# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

android_library(
    name = "yoga",
    srcs = glob(["yoga/*.java"]),
    visibility = [COMPONENTS_VISIBILITY],
    deps = [
        COMPONENTS_PROGUARDANNOTATIONS_TARGET,
        COMPONENTS_SOLOADER_TARGET,
        COMPONENTS_INFERANNOTATIONS_TARGET,
        COMPONENTS_JSR_TARGET,
    ],
)

android_prebuilt_aar(
    name = "yoga-prebuilt",
    aar = ":yoga-aar",
    visibility = [COMPONENTS_VISIBILITY],
)

remote_file(
    name = "yoga-aar",
    sha1 = "915fd94e05ac73508d4bfc8d9b3c6917350463c5",
    url = "mvn:com.facebook.yoga:yoga:aar:1.3.0",
)
