# BUILD FILE SYNTAX: SKYLARK
# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//:LITHO_DEFS.bzl", "LITHO_FBJNI_JAVA_TARGET", "LITHO_INFERANNOTATIONS_TARGET", "LITHO_JSR_TARGET", "LITHO_PROGUARDANNOTATIONS_TARGET", "LITHO_SOLOADER_TARGET", "LITHO_VISIBILITY", "litho_android_library")

litho_android_library(
    name = "yoga",
    srcs = glob(["src/main/java/**/*.java"]),
    visibility = LITHO_VISIBILITY,
    deps = [
        LITHO_PROGUARDANNOTATIONS_TARGET,
        LITHO_SOLOADER_TARGET,
        LITHO_INFERANNOTATIONS_TARGET,
        LITHO_JSR_TARGET,
        LITHO_FBJNI_JAVA_TARGET,
    ],
)
