load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_JAVA_TARGET",
    "LITHO_KOTLIN_TARGET",
    "LITHO_MOCKITO_KOTLIN_V2_TARGET",
    "LITHO_SAMPLE",
    "LITHO_WIDGET_KOTLIN_TARGET",
    "LITHO_YOGA_TARGET",
    "litho_android_library",
    "make_dep_path",
)

litho_android_library(
    name = "previews",
    caribou_preview = True,
    visibility = [
        make_dep_path("sample/..."),
    ],
    deps = [
        LITHO_MOCKITO_KOTLIN_V2_TARGET,
        LITHO_SAMPLE,
        LITHO_JAVA_TARGET,
        LITHO_KOTLIN_TARGET,
        LITHO_YOGA_TARGET,
        LITHO_WIDGET_KOTLIN_TARGET,
    ],
)
