include_defs("//COMPONENTS_DEFS")

android_library(
    name = "assertj",
    srcs = glob(["*.java"]),
    exported_deps = [
        COMPONENTS_ASSERTJ_TARGET,
    ],
    visibility = [
        "//javatests/...",
        make_dep_path("src/test/..."),
