include_defs("//COMPONENTS_DEFS")

java_library(
    name = "generator",
    srcs = glob(["*.java"]),
    tests = [
        "//javatests/com/facebook/components/specmodels/generator:generator",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        make_dep_path("src/main/java/com/facebook/components/javapoet:javapoet"),
        make_dep_path("src/main/java/com/facebook/components/specmodels/model:model"),
        COMPONENTS_FBCORE_TARGET,
        COMPONENTS_JSR_TARGET,
    ],
)
