# Copyright 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE-examples file in the root directory of this source tree.

include_defs("//COMPONENTS_DEFS")

android_library(
    name = "litho",
    srcs = glob(["**/*.java"]),
