# Copyright 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE-examples file in the root directory of this source tree.

include_defs("//COMPONENTS_DEFS")

android_library(
    name = "litho",
    srcs = glob(["**/*.java"]),
    annotation_processor_deps = [
        COMPONENTS_PROCESSOR_LIB_TARGET,
    ],
    annotation_processors = [
        "com.facebook.litho.processor.ComponentsProcessor",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps =
        COMPONENTS_FRESCO_PIPELINE_TARGET +
        COMPONENTS_FRESCO_CONTROLLER_TARGET +
        COMPONENTS_FRESCO_INTERFACES_TARGET +
        COMPONENTS_FRESCO_TARGETS + [
            COMPONENTS_ROOT_TARGET,
