# Copyright 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE-examples file in the root directory of this source tree.

load("//tools/build_defs/oss:litho_defs.bzl", "LITHO_ANDROIDSUPPORT_APPCOMPAT_TARGET", "LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET", "LITHO_ANDROIDSUPPORT_TARGET", "LITHO_FLIPPER_TARGETS", "LITHO_FRESCO_CONTROLLER_TARGET", "LITHO_FRESCO_INTERFACES_TARGET", "LITHO_FRESCO_PIPELINE_TARGET", "LITHO_FRESCO_TARGETS", "LITHO_GUAVA_TARGET", "LITHO_JSR_TARGET", "LITHO_LITHO_FRESCO_TARGET", "LITHO_PROCESSOR_LIB_TARGET", "LITHO_RES_TARGET", "LITHO_ROOT_TARGET", "LITHO_SAMPLE_RES", "LITHO_SECTIONS_ANNOTATIONS_TARGET", "LITHO_SECTIONS_COMMON_TARGET", "LITHO_SECTIONS_PROCESSOR_LIB_TARGET", "LITHO_SECTIONS_TARGET", "LITHO_SECTIONS_WIDGET_TARGET", "LITHO_SOLOADER_TARGET", "LITHO_STATS_TARGET", "LITHO_UTILS_TARGET", "LITHO_WIDGET_TARGET", "LITHO_YOGAJNI_TARGET", "LITHO_YOGA_TARGET", "fb_core_android_library")

fb_core_android_library(
    name = "litho",
    srcs = glob(["**/*.java"]),
    annotation_processor_deps = [
        LITHO_PROCESSOR_LIB_TARGET,
        LITHO_SECTIONS_PROCESSOR_LIB_TARGET,
    ],
    annotation_processors = [
        "com.facebook.litho.specmodels.processor.ComponentsProcessor",
        "com.facebook.litho.sections.specmodels.processor.SectionsComponentProcessor",
    ],
    is_androidx = True,
    visibility = [
        "PUBLIC",
    ],
    deps =
        LITHO_FRESCO_PIPELINE_TARGET +
        LITHO_FRESCO_CONTROLLER_TARGET +
        LITHO_FRESCO_INTERFACES_TARGET +
        LITHO_FLIPPER_TARGETS +
        LITHO_FRESCO_TARGETS + [
            LITHO_ROOT_TARGET,
            LITHO_LITHO_FRESCO_TARGET,
            LITHO_RES_TARGET,
            LITHO_UTILS_TARGET,
            LITHO_WIDGET_TARGET,
            LITHO_SAMPLE_RES,
            LITHO_SOLOADER_TARGET,
            LITHO_ANDROIDSUPPORT_TARGET,
            LITHO_ANDROIDSUPPORT_APPCOMPAT_TARGET,
            LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
            LITHO_JSR_TARGET,
            LITHO_YOGA_TARGET,
            LITHO_YOGAJNI_TARGET,
            LITHO_SECTIONS_TARGET,
            LITHO_SECTIONS_ANNOTATIONS_TARGET,
            LITHO_SECTIONS_COMMON_TARGET,
            LITHO_SECTIONS_WIDGET_TARGET,
            LITHO_STATS_TARGET,
            LITHO_GUAVA_TARGET,
        ],
)
