# BUILD FILE SYNTAX: SKYLARK
# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load("//:LITHO_DEFS.bzl", "LITHO_VISIBILITY", "fb_core_android_library", "make_dep_path")

fb_core_android_library(
    name = "espresso",
    exported_deps = [
        ":espresso-core-prebuilt",
        make_dep_path("lib/hamcrest:hamcrest"),
    ],
    visibility = LITHO_VISIBILITY,
)

android_prebuilt_aar(
    name = "espresso-core-prebuilt",
    aar = ":espresso-core-aar",
)

remote_file(
    name = "espresso-core-aar",
    sha1 = "4625e05585025ac9feee0ca2e29557ca61d4789e",
    url = "mvn:com.android.support.test.espresso:espresso-core:aar:3.0.2",
)
