# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load("//tools/build_defs/oss:fb_native_wrapper.bzl", "fb_native")
load("//tools/build_defs/oss:litho_defs.bzl", "LITHO_VISIBILITY", "fb_core_android_library", "make_dep_path")

fb_core_android_library(
    name = "espresso",
    visibility = LITHO_VISIBILITY,
    exported_deps = [
        ":espresso-core-prebuilt",
        make_dep_path("lib/hamcrest:hamcrest"),
    ],
)

fb_native.android_prebuilt_aar(
    name = "espresso-core-prebuilt",
    aar = ":espresso-core-aar",
)

fb_native.remote_file(
    name = "espresso-core-aar",
    sha1 = "fbc74f331a022c09be5775bbb0573b6ef3f38ae9",
    url = "mvn:androidx.test.espresso:espresso-core:aar:3.1.1",
)
