# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load("//:LITHO_DEFS", "LITHO_VISIBILITY")

prebuilt_jar(
    name = "javac-tools",
    binary_jar = ":javac-tools.jar",
    visibility = LITHO_VISIBILITY,
)

remote_file(
    name = "javac-tools.jar",
    sha1 = "b131b8c9b481c4860cc3e08ede96f2c545a369ad",
    url = "mvn:com.sun:tools:jar:1.7.0.13",
)
