# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load("//:COMPONENTS_DEFS", "COMPONENTS_ANDROIDSUPPORT_RECYCLERVIEW_TARGET", "COMPONENTS_ANDROIDSUPPORT_TARGET", "COMPONENTS_JAVA_TARGET", "COMPONENTS_JSR_TARGET", "litho_android_library", "make_dep_path")

litho_android_library(
    name = "utils",
    srcs = glob(["*.java"]),
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/utils:utils"),
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        COMPONENTS_JAVA_TARGET,
        COMPONENTS_ANDROIDSUPPORT_TARGET,
        COMPONENTS_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        COMPONENTS_JSR_TARGET,
    ],
)
