# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//tools/build_defs/oss:litho_defs.bzl", "LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET", "LITHO_ANDROIDSUPPORT_TARGET", "LITHO_JAVA_TARGET", "LITHO_JSR_TARGET", "litho_android_library", "make_dep_path")

litho_android_library(
    name = "utils",
    srcs = glob(["*.java"]),
    is_androidx = True,
    labels = ["supermodule:android/default/litho.core"],
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/utils:utils"),
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_JAVA_TARGET,
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        LITHO_JSR_TARGET,
    ],
)
