# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("@fbsource//xplat/pfh/FBApp/UIFrameworks/Litho/Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_JSR_TARGET",
    "litho_android_library",
    "make_dep_path",
)

litho_android_library(
    name = "utils",
    feature = FBApp_UIFrameworks_Litho_Litho,
    is_androidx = True,
    labels = ["supermodule:android/default/litho.core"],
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho:litho"),
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//fbandroid/third-party/java/infer-annotations:infer-annotations",
        LITHO_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_JSR_TARGET,
    ],
)
