# Copyright (c) Facebook, Inc. and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_JAVA_TARGET",
    "LITHO_RENDERCORE_PRIMITIVES_TARGET",
    "LITHO_RENDERCORE_PRIMITIVE_COMPONENTS_UTILS_TARGET",
    "LITHO_RENDERCORE_SIMPLELIST_TARGET",
    "LITHO_RENDERCORE_TARGET",
    "LITHO_RENDERCORE_ZOOMABLE_TARGET",
    "litho_android_library",
)

litho_android_library(
    name = "zoomable",
    feature = FBApp_UIFrameworks_Litho_Litho,
    k2 = True,
    labels = [],
    visibility = ["PUBLIC"],
    deps = [
        LITHO_RENDERCORE_PRIMITIVES_TARGET,
        LITHO_RENDERCORE_ZOOMABLE_TARGET,
        LITHO_RENDERCORE_SIMPLELIST_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_RENDERCORE_TARGET,
        "//fbandroid/java/com/facebook/common/sdk34workaround:gesturelistener",
        "//fbandroid/third-party/java/rebound:rebound",
        "//fbandroid/third-party/java/rebound/rebound-android:src",
        "//fbandroid/third-party/java/rebound/rebound-core:src",
        "//third-party/java/androidx/activity/activity:activity",
    ],
    exported_deps = [
        LITHO_RENDERCORE_PRIMITIVE_COMPONENTS_UTILS_TARGET,
    ],
)
