# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.
load("//:LITHO_DEFS", "LITHO_ANDROIDSUPPORT_TARGET", "LITHO_ANNOTATIONS_TARGET", "LITHO_JAVAPOET_TARGET", "LITHO_JSR_TARGET", "make_dep_path", "fb_java_library")

fb_java_library(
    name = "specmodels",
    exported_deps = [
        ":specmodels-bare",
        LITHO_JAVAPOET_TARGET,
        LITHO_JSR_TARGET,
    ],
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/specmodels:specmodels"),
    ],
    visibility = [
        "PUBLIC",
    ],
)

fb_java_library(
    name = "specmodels-bare",
    srcs = glob(
        ["**/*.java"],
        excludes = glob([
            "processor/**/*.java",
            "internal/*.java",
            "*/testing/*.java",
        ]),
    ),
    exported_deps = [
        LITHO_ANNOTATIONS_TARGET,
    ],
    provided_deps = [
        LITHO_JAVAPOET_TARGET,
        LITHO_JSR_TARGET,
    ],
    source = "8",
    target = "8",
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/internal:internal"),
    ],
)
