load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")

# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_JAVAPOET_TARGET",
    "LITHO_JSR_TARGET",
    "LITHO_VISIBILITY",
    "fb_java_library",
    "make_dep_path",
)

fb_java_library(
    name = "testing",
    srcs = glob(["*.java"]),
    feature = FBApp_UIFrameworks_Litho_Litho,
    labels = [],
    source = "8",
    target = "8",
    tests = [
        make_dep_path("litho-it/src/test/java/com/facebook/litho/specmodels:specmodels"),
    ],
    visibility = LITHO_VISIBILITY,
    deps = [
        LITHO_JAVAPOET_TARGET,
        LITHO_JSR_TARGET,
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels:specmodels-bare"),
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/internal:internal"),
    ],
)
