# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//tools/build_defs/oss:litho_defs.bzl", "LITHO_ANDROIDSUPPORT_TARGET", "LITHO_ASSERTJ_TARGET", "LITHO_BUILD_CONFIG_TARGET", "LITHO_GUAVA_TARGET", "LITHO_JAVAC_TOOLS_TARGET", "LITHO_JAVA_TARGET", "LITHO_JUNIT_TARGET", "LITHO_MOCKITO_TARGET", "LITHO_PROCESSOR_LIB_TARGET", "LITHO_ROBOLECTRIC_V3_TARGET", "LITHO_SECTIONS_TARGET", "LITHO_TESTING_ASSERTJ_TARGET", "LITHO_TESTING_TARGET", "LITHO_TESTING_WHITEBOX_TARGET", "LITHO_WIDGET_TARGET", "components_robolectric_test", "make_dep_path")

components_robolectric_test(
    name = "sections",
    srcs = glob(["*Test.java"]),
    is_androidx = True,
    source = "8",
    target = "8",
    deps = [
        LITHO_ASSERTJ_TARGET,
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_TESTING_TARGET,
        LITHO_TESTING_ASSERTJ_TARGET,
        LITHO_GUAVA_TARGET,
        LITHO_JAVAC_TOOLS_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_WIDGET_TARGET,
        LITHO_JUNIT_TARGET,
        LITHO_PROCESSOR_LIB_TARGET,
        LITHO_ROBOLECTRIC_V3_TARGET,
        LITHO_PROCESSOR_LIB_TARGET,
        LITHO_SECTIONS_TARGET,
        LITHO_BUILD_CONFIG_TARGET,
        LITHO_MOCKITO_TARGET,
        LITHO_TESTING_WHITEBOX_TARGET,
        make_dep_path("litho-processor/src/main/java/com/facebook/litho/specmodels/internal:internal"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/testrunner:testrunner"),
        make_dep_path("litho-sections-core/src/main/java/com/facebook/litho/sections/logger:logger"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/viewtree:viewtree"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/sections:sections"),
    ],
)
