# BUILD FILE SYNTAX: SKYLARK
# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.
load("//:LITHO_DEFS.bzl", "fb_java_library")

fb_java_library(
    name = "objenesis",
    exported_deps = [
        ":objenesis-prebuilt",
    ],
    visibility = ["PUBLIC"],
)

prebuilt_jar(
    name = "objenesis-prebuilt",
    binary_jar = ":objenesis.jar",
)

remote_file(
    name = "objenesis.jar",
    sha1 = "9b473564e792c2bdf1449da1f0b1b5bff9805704",
    url = "mvn:org.objenesis:objenesis:jar:1.0",
)
