# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

java_library(
    name = "objenesis",
    exported_deps = [
        ":objenesis-prebuilt",
    ],
    visibility = ["PUBLIC"],
)

prebuilt_jar(
    name = "objenesis-prebuilt",
    binary_jar = ":objenesis.jar",
)

remote_file(
    name = "objenesis.jar",
    sha1 = "9b473564e792c2bdf1449da1f0b1b5bff9805704",
    url = "mvn:org.objenesis:objenesis:jar:1.0",
)
