# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs("//COMPONENTS_DEFS")

components_robolectric_test(
    name = "widget",
    srcs = glob(["*.java"]),
    source = "8",
    target = "8",
    deps = [
        COMPONENTS_ASSERTJ_TARGET,
        COMPONENTS_JUNIT_TARGET,
        COMPONENTS_ROBOLECTRIC_TARGET,
        COMPONENTS_JAVA_TARGET,
        COMPONENTS_WIDGET_TARGET,
        COMPONENTS_BUILD_CONFIG_TARGET,
        COMPONENTS_SECTIONS_TARGET,
        COMPONENTS_ANDROIDSUPPORT_TARGET,
        COMPONENTS_POWERMOCK_REFLECT_TARGET,
        make_dep_path("litho-sections-widget/src/main/java/com/facebook/litho/sections/widget:widget"),
        make_dep_path("litho-sections-core/src/main/java/com/facebook/litho/sections/common:common"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/testrunner:testrunner"),
        COMPONENTS_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing:testing"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/assertj:assertj"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/util:util"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/viewtree:viewtree"),
        make_dep_path("litho-testing/src/main/java/com/facebook/litho/testing/sections:sections"),
    ],
)
