name: Push a new tag on correct release!

on: push

jobs:
  push-tags-job:
    name: Push tags for release
    runs-on: ubuntu-latest
    # needs: []
    steps:
    - uses: actions/checkout@v2
    - name: Set version info
      id: version_info
      run: echo ::set-output name=VERSION_INFO::`git log --format=%B -n 1 . | sed 's|\[litho\] Release version \([0-9\.]*\).*|\1|'`
    - name: Print version info
      if: ${{ steps.version_info.outputs.VERSION_INFO != '' }}
      env:
        VERSION_INFO: ${{ steps.version_info.outputs.VERSION_INFO }}
      run: echo $VERSION_INFO
