name: Push a new tag on correct release!

on: push

jobs:
  push-tags-job:
    name: Push tags for release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set version info
      id: version_info
      run: echo ::set-output name=VERSION_INFO::`git log --format=%B -n 1 . | egrep '\[[lL]itho\] [rR]elease version' | egrep -o '([[:digit:]]+\.){2}[[:digit:]]+'`
    - name: Print version info
      if: ${{ steps.version_info.outputs.VERSION_INFO != '' }}
      id: tag_info
      env:
        VERSION_INFO: ${{ steps.version_info.outputs.VERSION_INFO }}
      run: |
        echo ::set-output name=TAG_VERSION::`echo v${VERSION_INFO}` && \
        echo ::set-output name=TAG_MESSAGE::`echo Release v${VERSION_INFO}`
    - name: Tag version from info
      if: ${{ steps.tag_info.outputs.TAG_VERSION != '' }}
      env:
        TAG_VERSION: ${{ steps.tag_info.outputs.TAG_VERSION }}
        TAG_MESSAGE: ${{ steps.tag_info.outputs.TAG_MESSAGE }}
      run: |
        git tag -a $TAG_VERSION -m $TAG_MESSAGE
