name: Push a new tag on correct release!

on: push

jobs:
  push-tags-job:
    name: Push tags for release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set version info
      id: version_info
      run: echo ::set-output name=VERSION_INFO::`git log --format=%B -n 1 . | egrep '\[[lL]itho\] [rR]elease version' | egrep -o '([[:digit:]]+\.){2}[[:digit:]]+'`
    - name: Print version info
      if: ${{ steps.version_info.outputs.VERSION_INFO != '' }}
      env:
        VERSION_INFO: ${{ join('v', ${{ steps.version_info.outputs.VERSION_INFO) }} }}
      run: echo $VERSION_INFO
    - name: Tag version from info
      if: ${{ steps.version_info.outputs.VERSION_INFO != '' }}
      env:
        VERSION_INFO: ${{ join('v', steps.version_info.outputs.VERSION_INFO) }}
      run: |
        git tag -m "Release $VERSION_INFO" -a $VERSION_INFO
