name: Push a new tag on correct release!

on: push

jobs:
  push-tags-job:
    name: Push tags for release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set version info
      id: version_info
      run: echo ::set-output name=VERSION_INFO::`git log --format=%B -n 1 . | \
      egrep '\[[lL]itho\] [rR]elease version' | egrep -o '([[:digit:]]+\.){2}[[:digit:]]+' | \
      xargs -0 printf v%s`
    - name: Set Git tag
      if: ${{ steps.version_info.outputs.VERSION_INFO != '' }}
      uses: weareyipyip/walking-tag-action@v2
      with:
        tag-name: ${{ steps.version_info.outputs.VERSION_INFO }}
        tag-message: See [CHANGELOG.md](https://github.com/facebook/litho/blob/master/CHANGELOG.md) for the complete list of updates
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
