name: Release on new version tags

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  # get-buck:
  #   name: Fetch latest buck binary
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Fetch buck
  #     run: |
  #       wget https://jitpack.io/com/github/facebook/buck/master/buck-master.pex
  #   - name: Elevate buck
  #     run: |
  #       chmod +x buck-master.pex
  #   - name: Rename buck
  #     run: |
  #       mv buck-master.pex buck && ls -l buck
  #   - name: Export buck
  #     run: |
  #       export PATH="`realpath buck`:$PATH"
  test-job:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch buck
      run: |
        wget https://jitpack.io/com/github/facebook/buck/master/buck-master.pex
    - name: Elevate buck
      run: |
        chmod +x buck-master.pex
    - name: Rename buck
      run: |
        mv buck-master.pex buck && ls -l buck
    - name: Export buck
      run: |
        export PATH="`realpath buck`:$PATH"
    - name: Run all tests
      run: echo $PATH && ./gradlew test --stacktrace
  sample-java-job:
    name: Assemble sample app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch buck
      run: |
        wget https://jitpack.io/com/github/facebook/buck/master/buck-master.pex
    - name: Elevate buck
      run: |
        chmod +x buck-master.pex
    - name: Rename buck
      run: |
        mv buck-master.pex buck && ls -l buck
    - name: Export buck
      run: |
        export PATH="`realpath buck`:$PATH"
    - name: Run all tests
      run: echo $PATH && ./gradlew :sample:assembleDebug --stacktrace
  sample-kotlin-job:
    name: Assemble kotlin app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch buck
      run: |
        wget https://jitpack.io/com/github/facebook/buck/master/buck-master.pex
    - name: Elevate buck
      run: |
        chmod +x buck-master.pex
    - name: Rename buck
      run: |
        mv buck-master.pex buck && ls -l buck
    - name: Export buck
      run: |
        export PATH="`realpath buck`:$PATH"
    - name: Assemble kotlin sample
      run: echo $PATH && ./gradlew :sample-kotlin:assembleDebug --stacktrace
  publish-job:
    name: Maven Publish
    runs-on: ubuntu-latest
    needs: [test-job, sample-java-job, sample-kotlin-job]
    steps:
    - uses: actions/checkout@v2
    - name: Fetch buck
      run: |
        wget https://jitpack.io/com/github/facebook/buck/master/buck-master.pex
    - name: Elevate buck
      run: |
        chmod +x buck-master.pex
    - name: Rename buck
      run: |
        mv buck-master.pex buck && ls -l buck
    - name: Export buck
      run: |
        export PATH="`realpath buck`:$PATH"
    - name: Publish to maven
      env:
        BINTRAY_USERNAME: ${{ secrets.bintrayUsername }}
        BINTRAY_API_KEY: ${{ secrets.bintrayApiKey }}
      run: |
        ./gradlew bintrayUpload -PbintrayUsername=$BINTRAY_USERNAME -PbintrayApiKey=$BINTRAY_API_KEY --stacktrace
  validate-job:
    name: Validate uploads
    runs-on: ubuntu-latest
    needs: [publish-job]
    steps:
    - uses: actions/checkout@v2
    - name: Run validation script
      env:
          TAG: ${GITHUB_REF#refs/tags/}
      run: |
        scripts/verify-bintray-upload.hs
