name: Release on new version tags

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  # test-job:
  #   name: Run all tests
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Fetch buck
  #     run: |
  #       wget https://jitpack.io/com/github/facebook/buck/master/buck-master.pex && \
  #       chmod +x buck-master.pex && \
  #       mv buck-master.pex buck && \
  #       ls -l buck
  #   - name: Run all tests
  #     run: BUCK_PATH=`realpath buck` ./gradlew test --stacktrace
  # sample-java-job:
  #   name: Assemble sample app
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Fetch buck
  #     run: |
  #       wget https://jitpack.io/com/github/facebook/buck/master/buck-master.pex && \
  #       chmod +x buck-master.pex && \
  #       mv buck-master.pex buck && \
  #       ls -l buck
  #   - name: Assemble sample app
  #     run: BUCK_PATH=`realpath buck` ./gradlew :sample:assembleDebug --stacktrace
  # sample-kotlin-job:
  #   name: Assemble kotlin app
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Fetch buck
  #     run: |
  #       wget https://jitpack.io/com/github/facebook/buck/master/buck-master.pex && \
  #       chmod +x buck-master.pex && \
  #       mv buck-master.pex buck && \
  #       ls -l buck
  #   - name: Assemble kotlin sample
  #     run: BUCK_PATH=`realpath buck` ./gradlew :sample-kotlin:assembleDebug --stacktrace
  # publish-job:
  #   name: Maven Publish
  #   runs-on: ubuntu-latest
  #   needs: [test-job, sample-java-job, sample-kotlin-job]
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Fetch buck
  #     run: |
  #       wget https://jitpack.io/com/github/facebook/buck/master/buck-master.pex && \
  #       chmod +x buck-master.pex && \
  #       mv buck-master.pex buck && \
  #       ls -l buck
  #   - name: Publish to maven
  #     env:
  #       BINTRAY_USERNAME: ${{ secrets.bintrayUsername }}
  #       BINTRAY_API_KEY: ${{ secrets.bintrayApiKey }}
  #     run: |
  #       BUCK_PATH=`realpath buck` ./gradlew bintrayUpload -PbintrayUsername=$BINTRAY_USERNAME -PbintrayApiKey=$BINTRAY_API_KEY --stacktrace
  validate-job:
    name: Validate uploads
    runs-on: ubuntu-latest
    # needs: [publish-job]
    steps:
    - uses: actions/checkout@v2
    - uses: mstksg/setup-stack@v1
    - name: Run validation script
      env:
          TAG: ${GITHUB_REF#refs/tags/}
      run: |
        stack scripts/verify-bintray-upload.hs $TAG
