name: TagIt

on:
  schedule:
    - cron: '0 0 * * 1' # Every Monday

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get tag for the current date
        id: tag_info
        run: echo "::set-output name=TAG_NAME::$(date +'v%Y.%m.%d')"

      - name: Tag the latest commit
        uses: weareyipyip/walking-tag-action@v2
        with:
          tag-name: ${{ steps.tag_info.outputs.TAG_NAME }}
          tag-message: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
