# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load("//:COMPONENTS_DEFS", "COMPONENTS_ANDROIDSUPPORT_RECYCLERVIEW_TARGET", "COMPONENTS_ANDROIDSUPPORT_TARGET", "COMPONENTS_ANDROIDSUPPORT_TESTING_TARGET", "COMPONENTS_JAVA_TARGET", "COMPONENTS_JSR_TARGET", "COMPONENTS_POWERMOCK_REFLECT_TARGET", "COMPONENTS_RES_TARGET", "COMPONENTS_ROBOLECTRIC_TARGET", "COMPONENTS_TESTING_ASSERTJ_TARGET", "COMPONENTS_TESTING_HELPER_TARGET", "COMPONENTS_TESTING_SUBCOMPONENTS_TARGET", "COMPONENTS_WIDGET_TARGET", "COMPONENTS_YOGA_TARGET", "litho_android_library", "make_dep_path")

litho_android_library(
    name = "state",
    srcs = glob(["*.java"]),
    exported_deps = [
        COMPONENTS_TESTING_SUBCOMPONENTS_TARGET,
        COMPONENTS_TESTING_HELPER_TARGET,
    ],
    provided_deps = [
        COMPONENTS_ROBOLECTRIC_TARGET,
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        COMPONENTS_ANDROIDSUPPORT_TARGET,
        COMPONENTS_JAVA_TARGET,
        COMPONENTS_JSR_TARGET,
        COMPONENTS_POWERMOCK_REFLECT_TARGET,
        COMPONENTS_ANDROIDSUPPORT_RECYCLERVIEW_TARGET,
        COMPONENTS_ANDROIDSUPPORT_TESTING_TARGET,
    ],
)
