# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

prebuilt_jar(
    name = "infer-annotations",
    binary_jar = ":infer-annotations.jar",
    visibility = [
        "PUBLIC",
    ],
)

remote_file(
    name = "infer-annotations.jar",
    sha1 = "3932ca6a3e1aa16df91ef994d6ecfba0ddd3a90e",
    url = "mvn:com.facebook.infer.annotation:infer-annotation:jar:0.10.0.2",
)
