# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

prebuilt_jar(
    name = "infer-annotations",
    binary_jar = ":infer-annotations.jar",
    visibility = [
        "PUBLIC",
    ],
)

remote_file(
    name = "infer-annotations.jar",
    sha1 = "f514ff4ca022a579d9cf7524846988b646ae4491",
    url = "mvn:com.facebook.infer.annotation:infer-annotation:jar:0.11.2",
)
