# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_TARGET",
    "LITHO_JAVA_TARGET",
    "LITHO_PROCESSOR_TARGET",
    "LITHO_SECTIONS_PROCESSOR_TARGET",
    "LITHO_WIDGET_TARGET",
    "LITHO_YOGA_TARGET",
    "litho_android_library",
)

litho_android_library(
    name = "drawable",
    srcs = glob(["*.java"]),
    is_androidx = True,
    plugins = [
        LITHO_PROCESSOR_TARGET,
        LITHO_SECTIONS_PROCESSOR_TARGET,
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_JAVA_TARGET,
        LITHO_WIDGET_TARGET,
        LITHO_YOGA_TARGET,
    ],
)
