# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("//:LITHO_DEFS", "LITHO_ANDROIDSUPPORT_TARGET", "LITHO_ANNOTATIONS_TARGET", "LITHO_CONFIG_TARGET", "LITHO_DISPLAYLISTSTUBS_TARGET", "LITHO_INFERANNOTATIONS_TARGET", "LITHO_JSR_TARGET", "LITHO_PROGUARDANNOTATIONS_TARGET", "LITHO_RES_TARGET", "LITHO_TEST_TARGET", "LITHO_VIEWCOMPAT_TARGET", "LITHO_VISIBILITY", "LITHO_YOGA_TARGET", "litho_android_library", "make_dep_path")

litho_android_library(
    name = "litho",
    srcs = glob([
        "*.java",
        "animation/*.java",
        "dataflow/**/*.java",
        "displaylist/*.java",
        "reference/*.java",
    ]),
    exported_deps = [
        LITHO_ANNOTATIONS_TARGET,
        LITHO_CONFIG_TARGET,
        LITHO_PROGUARDANNOTATIONS_TARGET,
        make_dep_path("litho-core/src/main/java/com/facebook/litho/internal:internal"),
    ],
    provided_deps = [
        LITHO_ANDROIDSUPPORT_TARGET,
        LITHO_DISPLAYLISTSTUBS_TARGET,
        LITHO_YOGA_TARGET,
        LITHO_JSR_TARGET,
    ],
    required_for_source_only_abi = True,
    tests = [
        LITHO_TEST_TARGET,
    ],
    visibility = LITHO_VISIBILITY,
    deps = [
        LITHO_INFERANNOTATIONS_TARGET,
        LITHO_RES_TARGET,
        LITHO_VIEWCOMPAT_TARGET,
    ],
)
