# Copyright (c) 2017-present, Facebook, Inc.
#
# This source code is licensed under the Apache 2.0 license found in the
# LICENSE file in the root directory of this source tree.

load("@fbsource//xplat/pfh/FBApp_UIFrameworks_Litho_Litho:DEFS.bzl", "FBApp_UIFrameworks_Litho_Litho")
load(
    "//tools/build_defs/oss:litho_defs.bzl",
    "LITHO_ANDROIDSUPPORT_ANNOTATION_TARGET",
    "LITHO_ANDROIDSUPPORT_DYNAMICANIMATION_TARGET",
    "LITHO_ANNOTATIONS_TARGET",
    "LITHO_BUILD_CONFIG_TARGET",
    "LITHO_FLEXLAYOUT_TARGET",
    "LITHO_INFERANNOTATIONS_TARGET",
    "LITHO_JSR_TARGET",
    "LITHO_PERF_LOGGER",
    "LITHO_PROGUARDANNOTATIONS_TARGET",
    "LITHO_PROGUARD_ANNOTATIONS_TARGET",
    "LITHO_RENDERCORE_EXTENSIONS_RES_TARGET",
    "LITHO_RENDERCORE_EXTENSIONS_TARGET",
    "LITHO_RENDERCORE_INCREMENTAL_MOUNT_RES_TARGET",
    "LITHO_RENDERCORE_INCREMENTAL_MOUNT_TARGET",
    "LITHO_RENDERCORE_PRIMITIVES_TARGET",
    "LITHO_RENDERCORE_TARGET",
    "LITHO_RENDERCORE_TRANSITIONS_TARGET",
    "LITHO_RENDERCORE_VISIBILITY_TARGET",
    "LITHO_RES_TARGET",
    "LITHO_TEST_TARGET",
    "LITHO_VISIBILITY",
    "LITHO_YOGA_TARGET",
    "litho_android_library",
    "make_dep_path",
)

oncall("litho_components_for_android")

litho_android_library(
    name = "litho",
    srcs = glob([
        "**/*.java",
        "**/*.kt",
    ]),
    autoglob = False,
    exported_provided_deps = [
    ],
    feature = FBApp_UIFrameworks_Litho_Litho,
    incremental = True,
    k2 = False,
    labels = [],
    provided_deps = [
        LITHO_JSR_TARGET,
        LITHO_PROGUARD_ANNOTATIONS_TARGET,
    ],
    pure_kotlin = False,
    required_for_source_only_abi = True,
    tests = [
        LITHO_TEST_TARGET,
        make_dep_path("litho-it-spec/src/test/java/com/facebook/litho:litho"),
    ],
    visibility = LITHO_VISIBILITY,
    deps = [
        "//fbandroid/third-party/java/infer-annotations:infer-annotations",
        "//third-party/java/androidx/activity/activity:activity",
        "//third-party/java/androidx/lifecycle/lifecycle-runtime:lifecycle-runtime",
        "//third-party/java/androidx/viewpager/viewpager:viewpager",
        "//third-party/java/androidx/viewpager2/viewpager2:viewpager2",
        LITHO_ANDROIDSUPPORT_ANNOTATION_TARGET,
        LITHO_ANDROIDSUPPORT_DYNAMICANIMATION_TARGET,
        LITHO_BUILD_CONFIG_TARGET,
        LITHO_FLEXLAYOUT_TARGET,
        LITHO_INFERANNOTATIONS_TARGET,
        LITHO_PERF_LOGGER,
        LITHO_RENDERCORE_EXTENSIONS_RES_TARGET,
        LITHO_RENDERCORE_EXTENSIONS_TARGET,
        LITHO_RENDERCORE_INCREMENTAL_MOUNT_RES_TARGET,
        LITHO_RENDERCORE_INCREMENTAL_MOUNT_TARGET,
        LITHO_RES_TARGET,
    ],
    exported_deps = [
        "//fbandroid/java/com/facebook/kotlin/compilerplugins/dataclassgenerate/annotation:dataclassgenerate-annotation",
        LITHO_ANNOTATIONS_TARGET,
        LITHO_PROGUARDANNOTATIONS_TARGET,
        LITHO_RENDERCORE_TARGET,
        LITHO_RENDERCORE_EXTENSIONS_TARGET,
        LITHO_RENDERCORE_VISIBILITY_TARGET,
        LITHO_RENDERCORE_TRANSITIONS_TARGET,
        LITHO_RENDERCORE_PRIMITIVES_TARGET,
        LITHO_RENDERCORE_INCREMENTAL_MOUNT_TARGET,
        LITHO_YOGA_TARGET,
        LITHO_PERF_LOGGER,
        LITHO_FLEXLAYOUT_TARGET,
        "//third-party/java/androidx/annotation/annotation:annotation",
        "//third-party/java/androidx/core/core:core",
        "//third-party/java/androidx/fragment/fragment:fragment",
    ],
)
